(function(hostWindow){"use strict";
"use strict";
// Complex orthogonal factorization adapted from the independently checked research-tebd kernel.
 const z=()=>[0,0],add=(a,b)=>[a[0]+b[0],a[1]+b[1]],sub=(a,b)=>[a[0]-b[0],a[1]-b[1]],mul=(a,b)=>[a[0]*b[0]-a[1]*b[1],a[0]*b[1]+a[1]*b[0]],scale=(a,s)=>[a[0]*s,a[1]*s],conj=a=>[a[0],-a[1]],abs2=a=>a[0]*a[0]+a[1]*a[1];
 const dot=(a,b)=>a.reduce((s,x,i)=>add(s,mul(conj(x),b[i])),z()),norm2=a=>a.reduce((s,x)=>s+abs2(x),0),dag=A=>A[0].map((_,j)=>A.map(r=>conj(r[j]))),mm=(A,B)=>A.map(row=>B[0].map((_,j)=>row.reduce((s,x,k)=>add(s,mul(x,B[k][j])),z())));
 function columnJacobi(M){
  const n=M[0].length,cols=Array.from({length:n},(_,j)=>M.map(row=>row[j].slice())),R=Array.from({length:n},(_,j)=>Array.from({length:n},(_,i)=>[+(i===j),0]));
  let converged=false;
  for(let sweep=0;sweep<100;sweep++){
   let changed=false;
   for(let p=0;p<n;p++)for(let q=p+1;q<n;q++){
    const a=norm2(cols[p]),b=norm2(cols[q]),c=dot(cols[p],cols[q]),size=Math.hypot(...c);
    if(size<=2e-14*Math.sqrt(a*b)||size<1e-300)continue;
    const phase=scale(c,1/size),angle=.5*Math.atan2(2*size,b-a),co=Math.cos(angle),si=Math.sin(angle);
    for(const rows of [cols,R]){const u=rows[p],v=rows[q];rows[p]=u.map((x,i)=>sub(scale(mul(phase,x),co),scale(v[i],si)));rows[q]=u.map((x,i)=>add(scale(mul(phase,x),si),scale(v[i],co)));}
    changed=true;
   }
   if(!changed){converged=true;break;}
  }
  if(!converged)throw Error("复数Jacobi SVD未收敛");
  const order=Array.from({length:n},(_,j)=>j).sort((i,j)=>norm2(cols[j])-norm2(cols[i]));
  return {columns:order.map(i=>cols[i]),right:order.map(i=>R[i])};
 }
 function svdLeft(M){
  const m=M.length,n=M[0].length,Q=[];
  if(m<n){const s=columnJacobi(dag(M));Q.push(...s.right);}
  else{
   const s=columnJacobi(M),largest=Math.sqrt(norm2(s.columns[0]));
   const append=candidate=>{let q=candidate.map(x=>x.slice());for(let pass=0;pass<2;pass++)for(const p of Q){const c=dot(p,q);q=q.map((x,i)=>sub(x,mul(p[i],c)));}const norm=Math.sqrt(norm2(q));if(norm>1e-12)Q.push(q.map(x=>scale(x,1/norm)));};
   for(const col of s.columns){const norm=Math.sqrt(norm2(col));if(norm>largest*1e-14)append(col.map(x=>scale(x,1/norm)));}
   for(let i=0;Q.length<m&&i<m;i++)append(Array.from({length:m},(_,j)=>[+(i===j),0]));
  }
  if(Q.length!==m)throw Error("复奇异向量基不完整");
  const U=Array.from({length:m},(_,i)=>Q.map(q=>q[i])),B=mm(dag(U),M),weights=B.map(norm2);
  return {U,B,weights};
 }
 function split(M,chi,direction=1,normalize=true){
  const source=direction===1?M:dag(M),s=svdLeft(source),rank=Math.min(chi,source.length,source[0].length);
  if(!Number.isInteger(rank)||rank<1)throw Error("无效截断维数");
  const kept=s.weights.slice(0,rank).reduce((a,b)=>a+b,0),lost=s.weights.slice(rank).reduce((a,b)=>a+b,0),total=kept+lost;
  if(!(kept>0))throw Error("零态不能归一化");
  const L=s.U.map(row=>row.slice(0,rank)),R=s.B.slice(0,rank).map(row=>row.map(x=>scale(x,normalize?1/Math.sqrt(kept):1))),A=direction===1?L:dag(R),B=direction===1?R:dag(L),epsilon=lost/total;
  return {A,B,epsilon,delta:Math.sqrt(2*epsilon/(1+Math.sqrt(Math.max(0,1-epsilon)))),weights:s.weights,total};
 }

const LIMITS={state:[0,6],cut:[1,5],chi:[1,8],tailPower:[1,12],phaseSteps:[0,24],seed:[1,17],couplingTenths:[-20,20],fieldTenths:[0,20]};
const DEFAULTS={state:1,cut:3,chi:1,tailPower:8,phaseSteps:0,seed:7,couplingTenths:10,fieldTenths:10};
const STATE_NAMES=['乘积态','GHZ','开放链cluster','相邻Bell对','低熵的三权重态','微小满秩尾部','固定复随机态'];
const PRESETS=[['ghz','GHZ压成一条通道',{}],['exact','GHZ保留两条通道',{chi:2}],['product','乘积态与节点方差',{state:0}],['cluster','链式cluster',{state:2,chi:2}],['bells','交替宽窄的Bell对',{state:3,chi:2}],['entropy','低熵不等于低秩',{state:4,chi:2}],['tail','高秩与微小尾部',{state:5,chi:1}],['tiny','更小的非零尾部',{state:5,chi:1,tailPower:12}],['random','复随机态压缩',{state:6,chi:2}],['full','复随机态保留全维',{state:6,chi:8}],['phase','局部相位旋转',{state:6,chi:2,phaseSteps:5}],['diagonal','零横场的本征态',{state:0,fieldTenths:0}]].map(([id,name,parameters])=>({id,name,parameters}));
function config(input={}){if(!input||typeof input!=='object'||Array.isArray(input))throw Error('参数必须是对象');const out={...DEFAULTS};for(const [key,val]of Object.entries(input)){if(!Object.hasOwn(LIMITS,key)||!Number.isInteger(val)||val<LIMITS[key][0]||val>LIMITS[key][1])throw Error('无效参数 '+key);out[key]=val;}return out;}
const sum=a=>a.reduce((s,x)=>s+x,0),normalize=v=>{const n=Math.sqrt(norm2(v));if(!(n>0))throw Error('零态');return v.map(x=>scale(x,1/n));};
function stateVector(c){let v=Array.from({length:64},z);switch(c.state){
case 0:v[0]=[1,0];break;
case 1:v[0]=v[63]=[Math.SQRT1_2,0];break;
case 2:for(let b=0;b<64;b++){let parity=0;for(let j=0;j<5;j++)parity^=((b>>j)&3)===3?1:0;v[b]=[(parity?-1:1)/8,0];}break;
case 3:for(let b=0;b<64;b++)if([0,2,4].every(j=>((b>>j)&1)===((b>>(j+1))&1)))v[b]=[1/Math.sqrt(8),0];break;
case 4:[.8,.1,.1].forEach((p,i)=>v[i*9]=[Math.sqrt(p),0]);break;
case 5:{const e=10**(-c.tailPower);for(let i=0;i<8;i++)v[i*9]=[Math.sqrt(i===0?1-e:e/7),0];break;}
case 6:{let seed=c.seed>>>0;const random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return(seed+.5)/4294967296-.5;};v=v.map(()=>[random(),random()]);break;}
}v=normalize(v);return v.map((x,b)=>{let phase=0;for(let j=0;j<6;j++)phase+=(j+1)*((b>>(5-j))&1);phase*=Math.PI*c.phaseSteps/12;return mul(x,[Math.cos(phase),Math.sin(phase)]);});}
const reshape=(v,rows)=>Array.from({length:rows},(_,i)=>v.slice(i*v.length/rows,(i+1)*v.length/rows));
const distance2=(a,b)=>sum(a.map((x,i)=>abs2(sub(x,b[i]))));
function orthError(U){const G=mm(dag(U),U);return Math.sqrt(sum(G.flatMap((row,i)=>row.map((x,j)=>abs2(sub(x,[+(i===j),0]))))));}
function spectrum(v,k,chi){const C=reshape(v,2**k),s=svdLeft(C),count=Math.min(C.length,C[0].length),weights=s.weights.slice(0,count),sigmas=weights.map(Math.sqrt),keep=Math.min(chi,count),U=s.U.map(row=>row.slice(0,keep)),B=s.B.slice(0,keep),raw=mm(U,B).flat(),normalized=normalize(raw),lost=sum(s.weights.slice(keep)),kept=norm2(raw),ov=dot(v,normalized);return{cut:k,rows:C.length,columns:C[0].length,weights,sigmas,entanglementEnergies:weights.map(p=>p>0?-Math.log(p):null),entropy:-sum(weights.filter(p=>p>0).map(p=>p*Math.log(p))),numericalRank:sigmas.filter(x=>x>1e-6).length,rankThreshold:1e-6,retained:keep,discardedWeight:lost,retainedNormSquared:kept,overlapAmplitude:Math.sqrt(abs2(ov)),squaredFidelity:abs2(ov),errorSquared:distance2(v,raw),orthogonalityError:orthError(s.U),factorizationError:Math.sqrt(distance2(v,mm(s.U,s.B).flat())),coefficients:C,raw,normalized};}
function expand(tensors){let M=[[[1,0]]];for(const A of tensors){const next=[];for(const row of M)for(let bit=0;bit<2;bit++)next.push(A[bit][0].map((_,r)=>row.reduce((s,x,l)=>add(s,mul(x,A[bit][l][r])),z())));M=next;}return M.flat();}
function compress(v,chi){let rest=v.map(x=>x.slice()),left=1;const tensors=[],steps=[];for(let site=0;site<5;site++){const rows=2*left,M=reshape(rest,rows),s=svdLeft(M),keep=Math.min(chi,rows,M[0].length),L=s.U.map(row=>row.slice(0,keep));const A=Array.from({length:2},(_,bit)=>Array.from({length:left},(_,l)=>L[2*l+bit]));tensors.push(A);rest=s.B.slice(0,keep).flat();steps.push({cut:site+1,inputRows:rows,inputColumns:M[0].length,leftDimension:left,rightDimension:keep,weights:s.weights.slice(0,Math.min(rows,M[0].length)),incomingNormSquared:norm2(M.flat()),discardedWeight:sum(s.weights.slice(keep)),retainedNormSquared:norm2(rest),leftCanonicalError:orthError(L)});left=keep;}
tensors.push(Array.from({length:2},(_,bit)=>Array.from({length:left},(_,l)=>[rest[2*l+bit]])));const raw=expand(tensors),normalized=normalize(raw),overlap=dot(v,normalized),n=norm2(raw),discarded=sum(steps.map(x=>x.discardedWeight));return{chi,tensors,steps,raw,normalized,retainedNormSquared:n,sumDiscarded:discarded,errorSquared:distance2(v,raw),squaredFidelity:abs2(overlap),overlapAmplitude:Math.sqrt(abs2(overlap)),normalizedDistanceSquared:distance2(v,normalized),projectionOverlap:dot(v,raw),maxCanonicalError:Math.max(...steps.map(x=>x.leftCanonicalError)),tensorEntries:sum(tensors.map(A=>A.flat(2).length))};}
function applyH(v,J,h){return v.map((x,b)=>{let zz=0;for(let j=0;j<5;j++)zz+=((b>>j)&1)===((b>>(j+1))&1)?1:-1;let out=scale(x,-J*zz);for(let j=0;j<6;j++)out=sub(out,scale(v[b^(1<<j)],h));return out;});}
function observables(v,J,h){const n=norm2(v),hv=applyH(v,J,h),mean=dot(v,hv),E=mean[0]/n,res=hv.map((x,i)=>sub(x,scale(v[i],E)));let magnet=0,zz=0,localEnergy=[0,0],sampledVariance=0,nodeResidual=0,nodes=0;const local=[];for(let b=0;b<64;b++){const p=abs2(v[b])/n;let m=0,c=0;for(let j=0;j<6;j++)m+=1-2*((b>>j)&1);for(let j=0;j<5;j++)c+=((b>>j)&1)===((b>>(j+1))&1)?1:-1;magnet+=p*m/6;zz+=p*c/5;let e=null;if(p>0){e=scale(mul(conj(v[b]),hv[b]),1/abs2(v[b]));localEnergy=add(localEnergy,scale(e,p));sampledVariance+=p*abs2(sub(e,[E,0]));}else{nodes++;nodeResidual+=abs2(hv[b])/n;}local.push({basis:b,probability:p,localEnergy:e,residualWeight:abs2(res[b])/n});}return{normSquared:n,energy:E,energyImaginary:mean[1]/n,variance:norm2(res)/n,magnetization:magnet,neighborZZ:zz,localEnergyMean:localEnergy,sampledLocalVariance:sampledVariance,nodeResidual,nodes,local};}
function compute(input={}){const c=config(input),v=stateVector(c),J=c.couplingTenths/10,h=c.fieldTenths/10,original=observables(v,J,h),cuts=Array.from({length:5},(_,i)=>spectrum(v,i+1,c.chi)),selected=cuts[c.cut-1],chain=compress(v,c.chi),after=observables(chain.normalized,J,h),scan=Array.from({length:8},(_,i)=>{const q=compress(v,i+1),obs=observables(q.normalized,J,h);return{chi:i+1,sumDiscarded:q.sumDiscarded,errorSquared:q.errorSquared,retainedNormSquared:q.retainedNormSquared,squaredFidelity:q.squaredFidelity,energy:obs.energy,variance:obs.variance,tensorEntries:q.tensorEntries,maxCanonicalError:q.maxCanonicalError};}),knownRanks=[[1,1,1,1,1],[2,2,2,2,2],[2,2,2,2,2],[2,1,2,1,2],[1,2,3,3,2],[2,4,8,4,2],null][c.state],normBound=5*Math.abs(J)+6*Math.abs(h),energyBound=2*normBound*Math.sqrt(chain.sumDiscarded);
const boundaries={complexAmplitudesRetained:true,exactRankFromAnalyticFamilyOnly:true,numericalRankThresholdExplicit:true,tinyTailSummedDirectly:true,selectedCutIsOptimalAtOneCut:true,chainReconstructedFromSavedTensors:true,stepWeightsAreNotOriginalCutTails:true,globalOptimalMPSNotClaimed:true,degenerateVectorsNotUnique:true,localPhasePreservesSpectra:true,varianceIsFullResidual:true,zeroVarianceNotGroundCertificate:true,nodeContributionExplicit:true,finiteSixSiteToyNotScalingTheorem:true};
return{schema:'tensor203-v1',parameters:c,units:{N:6,hbar:1,entropy:'natural logarithm',phaseStep:'pi/12',energy:'fixed reference energy',rankThreshold:1e-6},state:{name:STATE_NAMES[c.state],amplitudes:v,knownExactRanks:knownRanks},selected,cuts,chain,chiScan:scan,observables:{J,h,original,compressed:after,normBound,energyShift:after.energy-original.energy,energyShiftBound:energyBound},comparison:{productOriginalCutFidelities:cuts.reduce((s,x)=>s*x.squaredFidelity,1),sumOriginalCutTails:sum(cuts.map(x=>x.discardedWeight)),sumActualStepTails:chain.sumDiscarded},boundaries};}
const QUESTIONS=[
['GHZ态在五个原始切口上用χ=1，各自保真度都是1/2。全链逐步压缩的保真度是(1/2)⁵吗？',['不是；首步丢掉一半，后面已是乘积态','是；五个独立截断的保真度相乘'],0,'这些切口分析都针对原始GHZ态；实际逐步算法每次处理上一步留下的态。首步保留一个分支后，后续没有相同的半权重可丢。全链F²=1/2。'],
['Schmidt权重为(0.8,0.1,0.1)，熵小于ln2，所以χ=2可以精确表示吗？',['可以；熵没有超过两条通道的容量','不可以；仍有第三条非零通道，丢弃权重0.1'],1,'熵是所有权重的汇总；S≤lnχ不是原始态rank≤χ的充分条件。精确秩为3，最优两通道归一化近似F²=0.9。'],
['对每个自旋分别施加相位门，会改变各切口的Schmidt权重吗？',['不会；每个切口两侧都只受到局部幺正变换','会；系数矩阵变成复数就会增加纠缠'],0,'变换形式C→U_A C U_Bᵀ，左右乘幺正矩阵不改变奇异值。复振幅和物理观测可以变，纠缠谱不因此改变。'],
['|000000〉在H=−JΣZZ−hΣX、h≠0下，只采到一个构型且局部能量不变，完整量子方差就是0吗？',['是；样本的局部能量完全没有波动','不是；Hψ在零振幅构型上仍有分量，方差为6h²'],1,'局部能量(Hψ)_s/ψ_s在节点上无定义。只按|ψ|²采样会漏掉节点处的残差；本例均值−5J，完整残差范数平方为6h²。零方差即使成立，也只能证明本征态。']
];
function feedback(i,j){if(!Number.isInteger(i)||i<0||i>=4||![0,1].includes(j))throw Error('无效预测');return{correct:j===QUESTIONS[i][2],text:(j===QUESTIONS[i][2]?'正确。':'需要修正。')+QUESTIONS[i][3]};}
const LABELS={state:'态族（编号见当前读数）',cut:'观察切口 k',chi:'每条键最多保留 χ',tailPower:'微小尾部 ε=10的负p次方：p',phaseSteps:'局部相位步数（每步π/12）',seed:'复随机态种子',couplingTenths:'Ising耦合 J ×10',fieldTenths:'横场 h ×10',complexAmplitudesRetained:'复振幅完整保留',exactRankFromAnalyticFamilyOnly:'精确秩仅对可解析态族声明',numericalRankThresholdExplicit:'数值秩阈值显式给出',tinyTailSummedDirectly:'微小尾部直接相加避免相消',selectedCutIsOptimalAtOneCut:'单切口最优性的适用范围明确',chainReconstructedFromSavedTensors:'从保存的张量实际收缩重建全链',stepWeightsAreNotOriginalCutTails:'实际步骤权重不同于原始切口尾部',globalOptimalMPSNotClaimed:'没有宣称全局最优MPS',degenerateVectorsNotUnique:'简并奇异向量不是唯一的',localPhasePreservesSpectra:'局部相位不改变纠缠谱',varianceIsFullResidual:'方差用完整残差计算',zeroVarianceNotGroundCertificate:'零方差不自动证明基态',nodeContributionExplicit:'零振幅节点的残差单列',finiteSixSiteToyNotScalingTheorem:'六站点例子不是渐近规模定理',normSquared:'范数平方',energy:'能量均值',energyImaginary:'能量虚部（浮点检查）',variance:'完整残差方差',magnetization:'平均Z磁化',neighborZZ:'平均相邻ZZ',localEnergyMean:'按概率求和的局部能量均值',sampledLocalVariance:'仅非零振幅处的局部能量方差',nodeResidual:'零振幅节点贡献',nodes:'精确零振幅构型数'};
function fmt(x){if(x===null||x===undefined)return'不适用';if(typeof x==='boolean')return x?'是':'否';if(Array.isArray(x))return'['+x.map(fmt).join(', ')+']';if(typeof x==='object')return JSON.stringify(x);if(typeof x==='number')return Number.isInteger(x)&&Math.abs(x)<1e6?String(x):Math.abs(x)<1e-4||Math.abs(x)>=1e5?x.toExponential(5):Number(x.toPrecision(7)).toString();return LABELS[x]??String(x);}
const COLORS=['#3875ba','#c55b32','#368661','#9860a8','#856722','#646e7c'];
function frame(key,title,xLabel,yLabel,series,domain){const ys=series.flatMap(s=>s.points.filter(Boolean).map(p=>p[1]));let lo=Math.min(0,...ys),hi=Math.max(0,...ys);if(hi===lo)hi=lo+1;const pad=.07*(hi-lo);return{key,title,xLabel,yLabel,xMin:domain[0],xMax:domain[1],yMin:lo-pad,yMax:hi+pad,series};}
function plots(s){const line=(name,i,points)=>({name,color:COLORS[i],points});let acc=0;return[
frame('spectrum','当前切口的权重：大尾巴与小尾巴都要记账','奇异值序号 i','pᵢ=σᵢ²',[
line('保留权重',0,s.selected.weights.map((p,i)=>i<s.selected.retained?[i+1,p]:null)),line('丢弃权重',1,s.selected.weights.map((p,i)=>i>=s.selected.retained?[i+1,p]:null))],[1,Math.max(2,s.selected.weights.length)]),
frame('tail','对数视图：正的微小权重不会被线性坐标藏掉','奇异值序号 i','log₁₀ pᵢ；精确0不画在有限位置',[
line('全部正权重的对数',0,s.selected.weights.map((p,i)=>p>0?[i+1,Math.log10(p)]:null)),line('数值秩阈值σ=10⁻⁶的平方',3,[[1,-12],[Math.max(2,s.selected.weights.length),-12]])],[1,Math.max(2,s.selected.weights.length)]),
frame('cuts','每个原始切口的熵与可解析秩','切口 k','自然对数单位（无量纲）',[
line('纠缠熵 S',0,s.cuts.map(p=>[p.cut,p.entropy])),line('可解析精确秩的 ln r',2,s.state.knownExactRanks?s.state.knownExactRanks.map((r,i)=>[i+1,Math.log(r)]):[]),line('当前键容量 ln χ',1,[[1,Math.log(s.parameters.chi)],[5,Math.log(s.parameters.chi)]])],[1,5]),
frame('fidelity','真正收缩全链，再测归一化保真度','统一键维 χ','F²与保留范数平方',[
line('实际全链F²',0,s.chiScan.map(p=>[p.chi,p.squaredFidelity])),line('未归一化重建态范数平方',2,s.chiScan.map(p=>[p.chi,p.retainedNormSquared]))],[1,8]),
frame('steps','逐步丢弃的是当前余量，不是每个原始切口','从左向右处理的切口','相对于原始归一化态的权重',[
line('当前步骤丢弃δk',0,s.chain.steps.map(p=>[p.cut,p.discardedWeight])),line('实际步骤累计丢弃',1,s.chain.steps.map(p=>[p.cut,acc+=p.discardedWeight])),line('原始态在该切口的尾部',3,s.cuts.map(p=>[p.cut,p.discardedWeight]))],[1,5]),
frame('energy','压缩改变能量；本实验没有优化基态','统一键维 χ','能量（固定参考单位）',[
line('压缩态能量',0,s.chiScan.map(p=>[p.chi,p.energy])),line('原始态能量',2,[[1,s.observables.original.energy],[8,s.observables.original.energy]])],[1,8])];}
function tables(s){const scalar=o=>Object.entries(o).filter(([k])=>k!=='local'),bits=b=>b.toString(2).padStart(6,'0');return[
{key:'parameters',title:'8项输入、态族与单位',headers:['量','值'],rows:[...Object.entries(s.parameters),['态族',s.state.name],['自旋数N',6],['相位门','第j站点乘exp(i j θ sⱼ)，θ=步数×π/12'],['数值秩阈值',s.selected.rankThreshold],['熵单位','自然对数'],['复数格式','[实部, 虚部]']]},
{key:'cuts',title:'五个原始切口：精确秩、数值秩、熵与单切口截断',headers:['k','行','列','解析精确秩','数值秩σ>10⁻⁶','S','保留维数','尾部ε','F','F²','误差平方','分解残差','正交残差'],rows:s.cuts.map((p,i)=>[p.cut,p.rows,p.columns,s.state.knownExactRanks?.[i]??null,p.numericalRank,p.entropy,p.retained,p.discardedWeight,p.overlapAmplitude,p.squaredFidelity,p.errorSquared,p.factorizationError,p.orthogonalityError])},
{key:'coefficients',title:'当前切口全部64个复系数',headers:['左索引','右索引','实部','虚部','模平方'],rows:s.selected.coefficients.flatMap((row,i)=>row.map((z,j)=>[i,j,z[0],z[1],abs2(z)]))},
{key:'spectrum',title:'当前切口完整奇异值与纠缠谱',headers:['i','σᵢ','pᵢ','ξᵢ=−ln pᵢ','保留'],rows:s.selected.weights.map((p,i)=>[i+1,s.selected.sigmas[i],p,s.selected.entanglementEnergies[i],i<s.selected.retained])},
{key:'amplitudes',title:'全部64构型：原始态、单切口近似和全链重建',headers:['二进制基底','原始复振幅','单切口归一化振幅','全链未归一化振幅','全链归一化振幅'],rows:s.state.amplitudes.map((z,i)=>[bits(i),z,s.selected.normalized[i],s.chain.raw[i],s.chain.normalized[i]])},
{key:'steps',title:'五步TT-SVD的形状、权重与规范检查',headers:['cut','输入行','输入列','左键维','保留右键维','输入范数平方','当前丢弃δk','输出范数平方','左规范残差'],rows:s.chain.steps.map(p=>[p.cut,p.inputRows,p.inputColumns,p.leftDimension,p.rightDimension,p.incomingNormSquared,p.discardedWeight,p.retainedNormSquared,p.leftCanonicalError])},
{key:'step-spectrum',title:'每次真正被截断矩阵的完整权重',headers:['步骤cut','序号i','未归一化权重','保留'],rows:s.chain.steps.flatMap(p=>p.weights.map((v,i)=>[p.cut,i+1,v,i<p.rightDimension]))},
{key:'tensors',title:'可直接收缩重建的六个MPS张量',headers:['站点j','物理位s','左索引','右索引','实部','虚部'],rows:s.chain.tensors.flatMap((A,j)=>A.flatMap((M,b)=>M.flatMap((row,l)=>row.map((z,r)=>[j+1,b,l,r,z[0],z[1]]))))},
{key:'chi',title:'χ=1至8的全部全链压缩结果',headers:['χ','当前步尾和','实际误差平方','保留范数平方','实际F²','能量','完整方差','复数参数个数','最大规范残差'],rows:s.chiScan.map(p=>[p.chi,p.sumDiscarded,p.errorSquared,p.retainedNormSquared,p.squaredFidelity,p.energy,p.variance,p.tensorEntries,p.maxCanonicalError])},
{key:'observables',title:'完整态观测与不同误差口径的核对',headers:['对象','量','值'],rows:[...scalar(s.observables.original).map(([k,v])=>['原始态',k,v]),...scalar(s.observables.compressed).map(([k,v])=>['全链近似',k,v]),['比较','能量变化',s.observables.energyShift],['比较','能量变化保守界',s.observables.energyShiftBound],['比较','原始切口F²乘积（一般不等于全链）',s.comparison.productOriginalCutFidelities],['比较','原始切口尾部之和',s.comparison.sumOriginalCutTails],['比较','实际步骤尾部之和',s.comparison.sumActualStepTails],['比较','原态与未归一化重建态内积',s.chain.projectionOverlap]]},
{key:'local',title:'原始态全部构型：局部能量与节点残差',headers:['基底','概率','局部能量（节点不适用）','完整残差权重'],rows:s.observables.original.local.map(p=>[bits(p.basis),p.probability,p.localEnergy,p.residualWeight])},
{key:'boundaries',title:'结论、算法与有限精度边界',headers:['边界','是否明确'],rows:Object.entries(s.boundaries)}];}
const axisFmt=v=>v===0?'0':Math.abs(v)<.001||Math.abs(v)>=10000?v.toExponential(2):Number(v.toFixed(3)).toString();
function svg(p){const left=100,right=855,top=95,bottom=385,X=v=>left+(v-p.xMin)/(p.xMax-p.xMin)*(right-left),Y=v=>bottom-(v-p.yMin)/(p.yMax-p.yMin)*(bottom-top),esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let out='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 900 580" role="img" aria-label="'+esc(p.title)+'"><title>'+esc(p.title)+'</title><style>text{font:15px system-ui;fill:currentColor}</style><text x="30" y="30" font-weight="700">'+esc(p.title)+'</text><text x="25" y="70">'+esc(p.yLabel)+'</text>';
const discrete=true;const xticks=Array.from({length:p.xMax-p.xMin+1},(_,i)=>p.xMin+i);for(let i=0;i<=4;i++){const x=p.xMin+(p.xMax-p.xMin)*i/4,y=p.yMin+(p.yMax-p.yMin)*i/4;out+='<line x1="100" x2="855" y1="'+Y(y)+'" y2="'+Y(y)+'" stroke="currentColor" opacity=".18"/><text x="85" y="'+(Y(y)+5)+'" text-anchor="end">'+axisFmt(y)+'</text>';}for(const x of xticks){out+='<text x="'+X(x)+'" y="410" text-anchor="middle">'+axisFmt(x)+'</text>';}
out+='<text x="477" y="442" text-anchor="middle">'+esc(p.xLabel)+'</text>';
p.series.forEach((s,i)=>{let pen=false;const path=s.points.map(q=>{if(!q){pen=false;return '';}const d=(pen&&!s.markersOnly?'L':'M')+X(q[0]).toFixed(6)+','+Y(q[1]).toFixed(6);pen=true;return d;}).join(' ');out+='<path data-series="'+i+'" d="'+path+'" stroke="'+s.color+'" stroke-width="2.8" fill="none"/>';const marks=s.points.filter(Boolean);marks.forEach(q=>out+='<circle cx="'+X(q[0])+'" cy="'+Y(q[1])+'" r="'+(3.5+1.5*i)+'" stroke="'+s.color+'" fill="'+(i>0?'none':s.color)+'" stroke-width="'+(s.markerStrokeWidth??2.5)+'"/>');out+='<line x1="'+(40+430*(i%2))+'" x2="'+(60+430*(i%2))+'" y1="'+(473+32*Math.floor(i/2))+'" y2="'+(473+32*Math.floor(i/2))+'" stroke="'+s.color+'" stroke-width="3"/><text x="'+(68+430*(i%2))+'" y="'+(478+32*Math.floor(i/2))+'">'+esc(s.name)+'</text>';});if(!p.series.some(s=>s.points.some(Boolean)))out+='<text x="450" y="245" text-anchor="middle">当前模型在此参数下无适用数据</text>';return out+'</svg>';}

var mounted=new WeakMap();
function mount(root){const doc=root.ownerDocument,previous=mounted.get(root);if(previous)previous();root.replaceChildren();root.classList.add('tensor203');let c=config(PRESETS[0].parameters),choices={},revealed=false,url=null,current=null,view=0,valid=true;
 const el=(tag,attrs={},text)=>{const e=doc.createElement(tag);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,v);if(text!==undefined)e.textContent=text;return e;};
 if(!doc.querySelector('[data-tensor203-style]')){const style=el('style',{'data-tensor203-style':''});style.textContent='.tensor203{margin-inline:0!important;width:100%;min-width:0;color:var(--fg,#222);line-height:1.65}.tensor203 *{box-sizing:border-box}.tensor203 button,.tensor203 select{font:inherit;min-height:44px;padding:8px;border:1px solid var(--border,#aaa);border-radius:5px;background:var(--block-bg,#eee);color:inherit;max-width:100%;white-space:normal}.tensor203 button[aria-pressed="true"]{outline:2px solid var(--accent,#a33)}.tensor203 button:focus-visible,.tensor203 select:focus-visible,.tensor203 [tabindex]:focus-visible{outline:3px solid #2474bc}.tensor203 .tn-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.tensor203 label{display:grid;gap:4px;min-width:0}.tensor203 input{width:100%;min-height:44px;font:inherit;color:inherit;background:var(--bg,#fff)}.tensor203 .tn-row{display:flex;gap:8px;flex-wrap:wrap;margin:10px 0}.tensor203 .tn-pred>strong{display:block;margin-bottom:6px}.tensor203 .tn-pred{padding:10px 0;border-top:1px solid var(--border,#aaa)}.tensor203 .tn-feedback{margin:7px 0}.tensor203 .tn-scroll{max-width:100%;overflow:auto}.tensor203 svg{display:block;min-width:680px;width:100%;height:auto}.tensor203 table{display:table;overflow:visible;max-width:none;border-collapse:collapse;width:max-content;min-width:100%;font-variant-numeric:tabular-nums}.tensor203 td,.tensor203 th{white-space:nowrap;text-align:right;padding:7px;border:1px solid var(--border,#bbb)}.tensor203 [hidden]{display:none!important}.tensor203 details{margin:12px 0}.tensor203 summary{min-height:44px;cursor:pointer}.tensor203 .tn-status{border-left:3px solid var(--accent,#a33);padding:8px 12px}.tensor203 .tn-correct{color:var(--cl-green,#277540)}.tensor203 .tn-wrong{color:var(--cl-red,#a33)}@media(max-width:600px){.tensor203 .tn-grid{grid-template-columns:1fr}}';doc.head.append(style);}
 root.append(el('h3',{},'从一个切口到实际重建整条量子链'),el('p',{},'固定六个自旋，选择态和键维，保存每步张量、全部复振幅与误差。先预测，再核对单切口和全链压缩。'));
 const presets=el('div',{class:'tn-row','aria-label':'教学预设'});for(const p of PRESETS){const b=el('button',{type:'button','data-preset':p.id},p.name);b.onclick=()=>{c=config(p.parameters);valid=true;sync();reset();};presets.append(b);}root.append(presets);
 const fields={},outs={},grid=el('div',{class:'tn-grid'});




 for(const[key,title]of Object.entries(LABELS).filter(([key])=>Object.hasOwn(LIMITS,key))){const[min,max]=LIMITS[key],label=el('label',{},title),out=el('output'),input=el('input',{type:'range',min,max,step:1,'data-field':key,'aria-label':title});label.append(out,input);grid.append(label);fields[key]=input;outs[key]=out;input.oninput=input.onchange=change;}root.append(grid);
 function change(){try{c=config(Object.fromEntries(Object.entries(fields).map(([k,e])=>[k,e.value===''?NaN:Number(e.value)])));valid=true;sync();reset();}catch(e){valid=false;reset();status.textContent='请使用控件范围内的整数，再按标签倍率换成实际量。';}}
 const note=el('p'),prediction=el('section',{'aria-label':'先预测'});root.append(note,prediction);prediction.append(el('h4',{},'先预测：全链误差、低熵、局部相位与节点方差'),el('p',{},'四题的条件固定写在题干里；参数用来检查例子，不自动改变问题。'));
 const feedbacks=[],buttons=[];QUESTIONS.forEach((q,i)=>{const row=el('div',{class:'tn-pred'});row.append(el('strong',{},q[0]));buttons[i]=[];q[1].forEach((text,j)=>{const b=el('button',{type:'button','data-prediction':i,'data-choice':String(j===0),'aria-pressed':'false'},text);b.onclick=()=>{choices[i]=j;buttons[i].forEach((x,k)=>x.setAttribute('aria-pressed',String(j===k)));if(revealed)showFeedback();};row.append(b);buttons[i].push(b);});feedbacks[i]=el('p',{class:'tn-feedback','data-feedback':i});row.append(feedbacks[i]);prediction.append(row);});
 const check=el('button',{type:'button','data-check':''},'核对预测并显示完整结果'),status=el('p',{class:'tn-status','aria-live':'polite'});root.append(check,status);
 const stage=el('section',{'data-stage':'',hidden:'','aria-label':'实验结果'}),summary=el('p'),plotButtons=el('div',{class:'tn-row'}),plotWrap=el('div',{class:'tn-scroll',tabindex:0,role:'region','aria-label':'图表，可横向滚动'}),plotNote=el('p',{},'切口、键维和奇异值序号是离散数据，连线只辅助阅读。简并奇异向量的具体取法不唯一。约10⁻¹¹以下的绝对残差须结合浮点误差解释；微小尾部使用直接求和并独立核对。'),tableHost=el('div'),download=el('a',{'data-download':'',download:'tn-record.json'},'下载当前完整记录（JSON）');stage.append(summary,plotButtons,plotWrap,plotNote,tableHost,download);root.append(stage);
 function sync(){for(const[k,e]of Object.entries(fields))e.value=c[k];}
 function reset(){if(url){hostWindow.URL.revokeObjectURL(url);url=null;download.removeAttribute('href');}revealed=false;choices={};stage.hidden=true;delete root.__tensorSnapshot;for(let i=0;i<4;i++){feedbacks[i].textContent='';for(const b of buttons[i])b.setAttribute('aria-pressed','false');}for(const[k,o]of Object.entries(outs))o.textContent=fmt(c[k]);note.textContent='当前态族：'+STATE_NAMES[c.state]+'。χ限制每条键，cut只选择观察位置。局部相位门不改变纠缠谱，但可改变固定Hamiltonian的能量。能量与方差使用完整64维态；本页不运行DMRG优化。';status.textContent='完成四项预测后显示当前结果。';}
 function showFeedback(){let n=0;for(let i=0;i<4;i++){if(!Number.isInteger(choices[i]))continue;const f=feedback(i,choices[i]);n+=+f.correct;feedbacks[i].textContent=f.text;feedbacks[i].className='tn-feedback '+(f.correct?'tn-correct':'tn-wrong');}status.textContent='预测核对：'+n+'/4 正确。图、表和下载均对应当前参数。';}
 function draw(){const ps=plots(current);plotWrap.innerHTML=svg(ps[view]);Array.from(plotButtons.children).forEach((b,i)=>b.setAttribute('aria-pressed',String(i===view)));}
 function render(){current=compute(c);root.__tensorSnapshot=current;stage.hidden=false;summary.textContent='单切口F²='+fmt(current.selected.squaredFidelity)+'；实际全链F²='+fmt(current.chain.squaredFidelity)+'；原始切口F²乘积='+fmt(current.comparison.productOriginalCutFidelities)+'。实际步骤尾和='+fmt(current.chain.sumDiscarded)+'；直接重建误差平方='+fmt(current.chain.errorSquared)+'。原始态完整方差='+fmt(current.observables.original.variance)+'。';plotButtons.replaceChildren();plots(current).forEach((p,i)=>{const b=el('button',{type:'button','data-plot':p.key},p.title);b.onclick=()=>{view=i;draw();};plotButtons.append(b);});draw();tableHost.replaceChildren();for(const t of tables(current)){const d=el('details',{'data-table':t.key});d.append(el('summary',{},t.title));d.addEventListener('toggle',()=>{if(!d.open||d.children.length>1)return;const wrap=el('div',{class:'tn-scroll',tabindex:0,role:'region','aria-label':t.title+'，可横向滚动'}),table=el('table'),thead=el('thead'),tr=el('tr'),tbody=el('tbody');for(const h of t.headers)tr.append(el('th',{scope:'col'},h));thead.append(tr);for(const row of t.rows){const r=el('tr');for(const v of row)r.append(el('td',{},fmt(v)));tbody.append(r);}table.append(thead,tbody);wrap.append(table);d.append(wrap);});tableHost.append(d);}if(url)hostWindow.URL.revokeObjectURL(url);url=hostWindow.URL.createObjectURL(new hostWindow.Blob([JSON.stringify(current)],{type:'application/json'}));download.href=url;showFeedback();}
 check.onclick=()=>{if(!valid){status.textContent='请先修正无效参数。';return;}if(![0,1,2,3].every(i=>Number.isInteger(choices[i]))){status.textContent='请先为四个问题各选一个预测。';return;}revealed=true;render();};sync();reset();mounted.set(root,()=>{if(url)hostWindow.URL.revokeObjectURL(url);});
}

function selfTest(){let checks=0;const ok=v=>{if(!v)throw Error('Tensor203 view '+checks);checks++;};for(const p of PRESETS){const s=compute(p.parameters);ok(plots(s).length===6);ok(tables(s).length===12);for(const plot of plots(s))for(const q of plot.series)for(const v of q.points)if(v)ok(v.every(Number.isFinite));for(let i=0;i<4;i++)ok(feedback(i,QUESTIONS[i][2]).correct);}return {status:'PASS',checks};}
const API={LIMITS,DEFAULTS,PRESETS,STATE_NAMES,config,QUESTIONS,compute,snapshot:compute,plots,tables,svg,feedback,fmt,mount,selfTest,stateVector,spectrum,compress,expand,applyH,observables,svdLeft};if(typeof module!=="undefined"&&module.exports)module.exports=API;if(hostWindow&&hostWindow.CourseLearning)hostWindow.CourseLearning.register("entanglement-cut",mount);})(typeof window!=="undefined"?window:null);
