(function (root, factory) {
  "use strict";
  var exported = factory(root);
  if (typeof module === "object" && module.exports) module.exports = exported;
  if (root && root.CourseLearning && typeof root.CourseLearning.register === "function") root.CourseLearning.register("micro-yield", exported.mount);
  if (typeof module === "object" && module.exports && typeof require === "function" && require.main === module) {
    try { var report = exported.selfTest(); console.log("micro-yield self-test: PASS (" + report.checks + " checks)"); }
    catch (error) { console.error("micro-yield self-test: FAIL\n" + error.stack); process.exitCode = 1; }
  }
})(typeof window !== "undefined" ? window : typeof globalThis !== "undefined" ? globalThis : null, function (host) {
  "use strict";

  var LAB_ID = "micro-yield";
  var SVG_NS = "http://www.w3.org/2000/svg";
  var STYLE_ID = "micro-yield-styles";
  var USABLE_FRACTION = 0.9;
  var DEFAULTS = { dieArea: 200, defectDensity: 0.1, alpha: 2, redundancy: 0 };
  var STYLE_TEXT = [
    '[data-learning-lab="micro-yield"]{--my-blue:var(--cl-blue,#315f9d);--my-red:var(--cl-red,#b64335);--my-green:var(--cl-green,#39734d);display:block;min-width:0;color:var(--fg,currentColor);line-height:1.55;overflow-wrap:anywhere}',
    '[data-learning-lab="micro-yield"] *{box-sizing:border-box}[data-learning-lab="micro-yield"] h3,[data-learning-lab="micro-yield"] h4{margin:0 0 8px;letter-spacing:0}[data-learning-lab="micro-yield"] p{margin:8px 0}',
    '[data-learning-lab="micro-yield"] .my-layout{display:grid;grid-template-columns:minmax(210px,.72fr) minmax(0,1.28fr);gap:16px;align-items:start}[data-learning-lab="micro-yield"] .my-controls{display:grid;gap:11px;padding:12px;border:1px solid var(--border);border-radius:7px;background:var(--bg,transparent)}[data-learning-lab="micro-yield"] .my-control{display:grid;gap:5px}[data-learning-lab="micro-yield"] label{color:var(--fg-soft);font-size:13px;font-weight:700}[data-learning-lab="micro-yield"] output{color:var(--accent);font-variant-numeric:tabular-nums}',
    '[data-learning-lab="micro-yield"] select,[data-learning-lab="micro-yield"] input,[data-learning-lab="micro-yield"] button{font:inherit;letter-spacing:0}[data-learning-lab="micro-yield"] select{width:100%;min-height:44px;padding:7px 10px;border:1px solid var(--border);border-radius:6px;background:var(--bg);color:var(--fg)}[data-learning-lab="micro-yield"] input[type="range"]{width:100%;min-height:44px;accent-color:var(--accent)}[data-learning-lab="micro-yield"] button{min-height:44px;padding:8px 12px;border:1px solid var(--border);border-radius:6px;background:var(--bg);color:var(--fg);cursor:pointer}[data-learning-lab="micro-yield"] button:hover{border-color:var(--accent)}[data-learning-lab="micro-yield"] button:focus-visible,[data-learning-lab="micro-yield"] select:focus-visible,[data-learning-lab="micro-yield"] input:focus-visible{outline:3px solid var(--cl-focus,#1769aa);outline-offset:2px}',
    '[data-learning-lab="micro-yield"] .my-stage{min-width:0;padding:8px;border:1px solid var(--border);border-radius:7px;background:var(--bg,transparent);overflow:hidden}[data-learning-lab="micro-yield"] svg{display:block;width:100%;height:auto;color:var(--fg,currentColor)}[data-learning-lab="micro-yield"] svg text{fill:currentColor;font-family:inherit;letter-spacing:0}[data-learning-lab="micro-yield"] .my-grid{stroke:var(--border);stroke-width:1;stroke-opacity:.7}[data-learning-lab="micro-yield"] .my-base{fill:none;stroke:var(--my-blue);stroke-width:3}[data-learning-lab="micro-yield"] .my-recovered{fill:none;stroke:var(--my-green);stroke-width:2.5;stroke-dasharray:7 4}[data-learning-lab="micro-yield"] .my-point{fill:var(--my-red);stroke:var(--bg);stroke-width:2}',
    '[data-learning-lab="micro-yield"] .my-predict{display:grid;gap:7px;margin:12px 0;padding:11px 12px;border-left:3px solid var(--cl-gold,#9b6a12);background:var(--block-bg,var(--bg))}[data-learning-lab="micro-yield"] .my-feedback{min-height:1.6em;color:var(--fg-soft);font-size:13px}[data-learning-lab="micro-yield"] .my-ok{color:var(--my-green);font-weight:700}[data-learning-lab="micro-yield"] .my-no{color:var(--my-red);font-weight:700}[data-learning-lab="micro-yield"] .my-note{color:var(--fg-soft);font-size:13px;line-height:1.7}',
    '[data-learning-lab="micro-yield"] .my-metrics{display:grid;grid-template-columns:repeat(auto-fit,minmax(125px,1fr));gap:8px;margin:12px 0}[data-learning-lab="micro-yield"] .my-metric{min-width:0;padding:9px;border-top:2px solid var(--border);background:var(--bg)}[data-learning-lab="micro-yield"] .my-metric span{display:block;color:var(--fg-soft);font-size:11.5px}[data-learning-lab="micro-yield"] .my-metric strong{display:block;margin-top:3px;font-size:15px;font-variant-numeric:tabular-nums;overflow-wrap:anywhere}',
    '@media(max-width:820px){[data-learning-lab="micro-yield"] .my-layout{grid-template-columns:minmax(0,1fr)}}@media(prefers-reduced-motion:reduce){[data-learning-lab="micro-yield"] *{transition:none!important;animation:none!important}}'
  ].join("");

  function assert(condition, message) { if (!condition) throw new Error(message); }
  function near(a, b, tolerance) { return Math.abs(a - b) <= (tolerance || 1e-9) * Math.max(1, Math.abs(a), Math.abs(b)); }
  function format(value, digits) {
    var places = digits === undefined ? 2 : Number(digits);
    var text = Number(value).toFixed(places);
    return places === 0 ? text : text.replace(/0+$/, "").replace(/\.$/, "");
  }
  function element(doc, tag, attrs, children) { var node = doc.createElement(tag); Object.keys(attrs || {}).forEach(function (key) { var value = attrs[key]; if (value === undefined || value === null || value === false) return; if (key === "className") node.setAttribute("class", String(value)); else if (key === "htmlFor") node.setAttribute("for", String(value)); else if (key === "text") node.textContent = String(value); else if (value === true) node.setAttribute(key, ""); else node.setAttribute(key, String(value)); }); (Array.isArray(children) ? children : children === undefined ? [] : [children]).forEach(function (child) { if (child !== undefined && child !== null && child !== false) node.appendChild(child.nodeType ? child : doc.createTextNode(String(child))); }); return node; }
  function svgElement(doc, tag, attrs, children) { var node = doc.createElementNS(SVG_NS, tag); Object.keys(attrs || {}).forEach(function (key) { if (attrs[key] !== undefined && attrs[key] !== null) node.setAttribute(key, String(attrs[key])); }); (Array.isArray(children) ? children : children === undefined ? [] : [children]).forEach(function (child) { if (child !== undefined && child !== null) node.appendChild(child.nodeType ? child : doc.createTextNode(String(child))); }); return node; }
  function clear(node) { while (node.firstChild) node.removeChild(node.firstChild); }
  function installStyles(doc) { if (!doc || !doc.createElement || (doc.getElementById && doc.getElementById(STYLE_ID))) return; var style = doc.createElement("style"); style.id = STYLE_ID; style.textContent = STYLE_TEXT; (doc.head || doc.documentElement).appendChild(style); }
  function announce(api, rootNode, message) { if (api && typeof api.announce === "function") api.announce(rootNode, message); }
  function normalize(input) {
    var source = input || {}; var dieArea = Number(source.dieArea === undefined ? DEFAULTS.dieArea : source.dieArea); var defectDensity = Number(source.defectDensity === undefined ? DEFAULTS.defectDensity : source.defectDensity); var alpha = Number(source.alpha === undefined ? DEFAULTS.alpha : source.alpha); var redundancy = Number(source.redundancy === undefined ? DEFAULTS.redundancy : source.redundancy);
    if (dieArea < 50 || dieArea > 800 || defectDensity < 0.01 || defectDensity > 0.5 || [1, 2, 5].indexOf(alpha) === -1 || redundancy < 0 || redundancy > 0.5) throw new RangeError("invalid yield controls");
    return { dieArea: dieArea, defectDensity: defectDensity, alpha: alpha, redundancy: redundancy };
  }
  function yieldAt(areaMm2, defectDensity, alpha, redundancy) {
    var areaCm2 = areaMm2 / 100; var base = Math.pow(1 + areaCm2 * defectDensity / alpha, -alpha); var recovered = Math.min(0.995, base + redundancy * (1 - base)); return { base: base, recovered: recovered };
  }
  function simulate(input) {
    var config = normalize(input); var point = yieldAt(config.dieArea, config.defectDensity, config.alpha, config.redundancy); var waferArea = Math.PI * 150 * 150; var usableArea = USABLE_FRACTION * waferArea; var grossDies = Math.floor(usableArea / config.dieArea);
    return { config: config, point: point, waferArea: waferArea, usableArea: usableArea, grossDies: grossDies, goodBase: grossDies * point.base, goodRecovered: grossDies * point.recovered };
  }
  function mount(rootNode, api) {
    var doc = rootNode.ownerDocument || document; installStyles(doc); clear(rootNode);
    var title = element(doc, "h3", { text: "良率实验：面积、缺陷与冗余" }); var note = element(doc, "p", { className: "my-note", text: "先预测：把 die 面积加倍，负二项良率如何变化？" });
    var predict = element(doc, "div", { className: "my-predict" }, [element(doc, "label", { htmlFor: LAB_ID + "-prediction", text: "面积加倍后的良率趋势：" }), element(doc, "select", { id: LAB_ID + "-prediction", "aria-label": "面积良率趋势预测" }, [element(doc, "option", { value: "down", text: "下降，且不是线性相减" }), element(doc, "option", { value: "same", text: "保持不变" }), element(doc, "option", { value: "up", text: "上升" })]), element(doc, "button", { type: "button", text: "检验预测" }), element(doc, "div", { className: "my-feedback", "aria-live": "polite" })]);
    var controls = element(doc, "div", { className: "my-controls" });
    function addRange(label, id, min, max, step, value, suffix, digits) { var output = element(doc, "output", { for: id, text: format(value, digits) + suffix }); var input = element(doc, "input", { id: id, type: "range", min: min, max: max, step: step, value: value }); input.addEventListener("input", function () { output.textContent = format(Number(input.value), digits) + suffix; render(); }); controls.appendChild(element(doc, "div", { className: "my-control" }, [element(doc, "label", { htmlFor: id, text: label }), output, input])); return input; }
    var die = addRange("裸片面积", LAB_ID + "-die", 50, 800, 10, DEFAULTS.dieArea, " mm²", 0); var defect = addRange("缺陷密度 D0", LAB_ID + "-density", 0.01, 0.5, 0.01, DEFAULTS.defectDensity, " /cm²", 2);
    var alpha = element(doc, "select", { id: LAB_ID + "-alpha" }, [element(doc, "option", { value: "1", text: "alpha = 1" }), element(doc, "option", { value: "2", text: "alpha = 2" }), element(doc, "option", { value: "5", text: "alpha = 5" })]); alpha.value = "2"; alpha.addEventListener("change", render); controls.appendChild(element(doc, "div", { className: "my-control" }, [element(doc, "label", { htmlFor: alpha.id, text: "缺陷聚集因子" }), alpha]));
    var redundancy = addRange("可由冗余恢复的失效比例", LAB_ID + "-redundancy", 0, 0.5, 0.05, DEFAULTS.redundancy, "", 2);
    var stage = element(doc, "div", { className: "my-stage" }); var result = element(doc, "div"); rootNode.appendChild(title); rootNode.appendChild(note); rootNode.appendChild(predict); rootNode.appendChild(element(doc, "div", { className: "my-layout" }, [controls, element(doc, "div", {}, [stage, result])]));
    function renderStage(data) { var chart = svgElement(doc, "svg", { viewBox: "0 0 720 310", role: "img", "aria-label": "负二项良率随裸片面积变化的曲线" }); chart.appendChild(svgElement(doc, "title", {}, "良率曲线")); chart.appendChild(svgElement(doc, "desc", {}, "蓝线为基础良率，绿虚线为加入冗余恢复后的良率，红点是当前面积。")); var left = 55, top = 20, width = 635, height = 230; function x(area) { return left + (area - 50) / 750 * width; } function y(value) { return top + height * (1 - value); } [0, 0.25, 0.5, 0.75, 1].forEach(function (tick) { var yy = y(tick); chart.appendChild(svgElement(doc, "line", { x1: left, y1: yy, x2: left + width, y2: yy, class: "my-grid" })); chart.appendChild(svgElement(doc, "text", { x: left - 8, y: yy + 4, "text-anchor": "end", "font-size": 11 }, format(tick * 100, 0) + "%")); }); [50, 200, 400, 600, 800].forEach(function (tick) { chart.appendChild(svgElement(doc, "text", { x: x(tick), y: top + height + 22, "text-anchor": "middle", "font-size": 11 }, tick + " mm²")); }); var areas = []; for (var area = 50; area <= 800; area += 25) areas.push(area); function pathFor(key) { return areas.map(function (area, index) { var value = yieldAt(area, data.config.defectDensity, data.config.alpha, data.config.redundancy)[key]; return (index ? "L" : "M") + x(area).toFixed(2) + " " + y(value).toFixed(2); }).join(" "); } chart.appendChild(svgElement(doc, "path", { d: pathFor("base"), class: "my-base" })); chart.appendChild(svgElement(doc, "path", { d: pathFor("recovered"), class: "my-recovered" })); chart.appendChild(svgElement(doc, "line", { x1: x(data.config.dieArea), y1: top, x2: x(data.config.dieArea), y2: top + height, stroke: "var(--my-red)", "stroke-dasharray": "3 3" })); chart.appendChild(svgElement(doc, "circle", { cx: x(data.config.dieArea), cy: y(data.point.recovered), r: 5, class: "my-point" })); chart.appendChild(svgElement(doc, "text", { x: left, y: 286, "font-size": 11 }, "蓝：基础 Y   绿虚线：冗余恢复后 Y")); stage.replaceChildren(chart); }
    function render() { var data = simulate({ dieArea: Number(die.value), defectDensity: Number(defect.value), alpha: Number(alpha.value), redundancy: Number(redundancy.value) }); renderStage(data); result.replaceChildren(element(doc, "div", { className: "my-metrics" }, [element(doc, "div", { className: "my-metric" }, [element(doc, "span", { text: "基础 Y" }), element(doc, "strong", { text: format(data.point.base * 100, 1) + "%" })]), element(doc, "div", { className: "my-metric" }, [element(doc, "span", { text: "冗余后 Y" }), element(doc, "strong", { text: format(data.point.recovered * 100, 1) + "%" })]), element(doc, "div", { className: "my-metric" }, [element(doc, "span", { text: "全圆面积" }), element(doc, "strong", { text: format(data.waferArea, 0) + " mm²" })]), element(doc, "div", { className: "my-metric" }, [element(doc, "span", { text: "可用面积（90%）" }), element(doc, "strong", { text: format(data.usableArea, 0) + " mm²" })]), element(doc, "div", { className: "my-metric" }, [element(doc, "span", { text: "可用区几何裸片" }), element(doc, "strong", { text: String(data.grossDies) })]), element(doc, "div", { className: "my-metric" }, [element(doc, "span", { text: "好裸片估计" }), element(doc, "strong", { text: format(data.goodRecovered, 1) })]) ])); }
    predict.querySelector("button").addEventListener("click", function () { var answer = predict.querySelector("select").value; var before = yieldAt(200, 0.1, 2, 0).base; var after = yieldAt(400, 0.1, 2, 0).base; var feedback = predict.querySelector(".my-feedback"); var ok = answer === "down" && after < before; feedback.className = "my-feedback " + (ok ? "my-ok" : "my-no"); feedback.textContent = ok ? "正确：面积进入负二项项，良率下降；下降量由模型决定，不是简单减去一个固定百分比。" : "再代入 Y=(1+A*D0/alpha)^(-alpha)：面积变大时 Y 下降。"; announce(api, rootNode, feedback.textContent); });
    render();
  }
  function selfTest() { var checks = 0; function check(condition, message) { checks += 1; assert(condition, message); } var base = yieldAt(800, 0.1, 2, 0); var small = yieldAt(200, 0.1, 2, 0); check(near(base.base, Math.pow(1 + 8 * 0.1 / 2, -2)), "negative binomial formula"); check(base.base < small.base, "yield falls with area"); check(base.recovered === base.base, "zero redundancy is unchanged"); var repaired = yieldAt(200, 0.1, 2, 0.2); check(repaired.recovered > repaired.base && repaired.recovered <= 0.995, "redundancy recovery bound"); var data = simulate(DEFAULTS); check(near(data.usableArea, data.waferArea * USABLE_FRACTION), "usable wafer area"); check(data.grossDies === Math.floor(data.usableArea / DEFAULTS.dieArea), "usable-zone die count"); check(data.grossDies > 0 && data.goodRecovered <= data.grossDies, "wafer counts are bounded"); check(near(data.point.base, yieldAt(DEFAULTS.dieArea, DEFAULTS.defectDensity, DEFAULTS.alpha, 0).base), "simulation point"); check(format(DEFAULTS.dieArea, 0) === "200", "zero-decimal die area keeps trailing zero"); check(format(50, 0) === "50" && format(100, 0) === "100", "percentage axis labels keep trailing zero"); return { checks: checks }; }
  return { yieldAt: yieldAt, simulate: simulate, mount: mount, selfTest: selfTest, USABLE_FRACTION: USABLE_FRACTION };
});
