(function (root, factory) {
  "use strict";
  var exported = factory(root);
  if (typeof module === "object" && module.exports) module.exports = exported;
  if (root && root.CourseLearning && typeof root.CourseLearning.register === "function") root.CourseLearning.register("micro-chiplet", exported.mount);
  if (typeof module === "object" && module.exports && typeof require === "function" && require.main === module) {
    try { var report = exported.selfTest(); console.log("micro-chiplet self-test: PASS (" + report.checks + " checks)"); }
    catch (error) { console.error("micro-chiplet self-test: FAIL\n" + error.stack); process.exitCode = 1; }
  }
})(typeof window !== "undefined" ? window : typeof globalThis !== "undefined" ? globalThis : null, function (host) {
  "use strict";

  var LAB_ID = "micro-chiplet";
  var SVG_NS = "http://www.w3.org/2000/svg";
  var STYLE_ID = "micro-chiplet-styles";
  var DEFAULTS = { totalArea: 600, chiplets: 4, trafficGbit: 8, linkEnergy: 2, packageYield: 0.96, topology: "2.5D" };
  var STYLE_TEXT = [
    '[data-learning-lab="micro-chiplet"]{--mc-blue:var(--cl-blue,#315f9d);--mc-red:var(--cl-red,#b64335);--mc-green:var(--cl-green,#39734d);--mc-gold:var(--cl-gold,#9b6a12);display:block;min-width:0;color:var(--fg,currentColor);line-height:1.55;overflow-wrap:anywhere}',
    '[data-learning-lab="micro-chiplet"] *{box-sizing:border-box}[data-learning-lab="micro-chiplet"] h3,[data-learning-lab="micro-chiplet"] h4{margin:0 0 8px;letter-spacing:0}[data-learning-lab="micro-chiplet"] p{margin:8px 0}',
    '[data-learning-lab="micro-chiplet"] .mc-layout{display:grid;grid-template-columns:minmax(215px,.72fr) minmax(0,1.28fr);gap:16px;align-items:start}[data-learning-lab="micro-chiplet"] .mc-controls{display:grid;gap:11px;padding:12px;border:1px solid var(--border);border-radius:7px;background:var(--bg,transparent)}[data-learning-lab="micro-chiplet"] .mc-control{display:grid;gap:5px}[data-learning-lab="micro-chiplet"] label{color:var(--fg-soft);font-size:13px;font-weight:700}[data-learning-lab="micro-chiplet"] output{color:var(--accent);font-variant-numeric:tabular-nums}',
    '[data-learning-lab="micro-chiplet"] select,[data-learning-lab="micro-chiplet"] input,[data-learning-lab="micro-chiplet"] button{font:inherit;letter-spacing:0}[data-learning-lab="micro-chiplet"] select{width:100%;min-height:44px;padding:7px 10px;border:1px solid var(--border);border-radius:6px;background:var(--bg);color:var(--fg)}[data-learning-lab="micro-chiplet"] input[type="range"]{width:100%;min-height:44px;accent-color:var(--accent)}[data-learning-lab="micro-chiplet"] button{min-height:44px;padding:8px 12px;border:1px solid var(--border);border-radius:6px;background:var(--bg);color:var(--fg);cursor:pointer}[data-learning-lab="micro-chiplet"] button:hover{border-color:var(--accent)}[data-learning-lab="micro-chiplet"] button:focus-visible,[data-learning-lab="micro-chiplet"] select:focus-visible,[data-learning-lab="micro-chiplet"] input:focus-visible{outline:3px solid var(--cl-focus,#1769aa);outline-offset:2px}',
    '[data-learning-lab="micro-chiplet"] .mc-stage{min-width:0;padding:8px;border:1px solid var(--border);border-radius:7px;background:var(--bg,transparent);overflow:hidden}[data-learning-lab="micro-chiplet"] svg{display:block;width:100%;height:auto;color:var(--fg,currentColor)}[data-learning-lab="micro-chiplet"] svg text{fill:currentColor;font-family:inherit;letter-spacing:0}[data-learning-lab="micro-chiplet"] .mc-grid{stroke:var(--border);stroke-width:1;stroke-opacity:.7}[data-learning-lab="micro-chiplet"] .mc-point{fill:var(--mc-blue);stroke:var(--bg);stroke-width:2}[data-learning-lab="micro-chiplet"] .mc-selected{fill:var(--mc-red);stroke:var(--bg);stroke-width:2}',
    '[data-learning-lab="micro-chiplet"] .mc-predict{display:grid;gap:7px;margin:12px 0;padding:11px 12px;border-left:3px solid var(--cl-gold,#9b6a12);background:var(--block-bg,var(--bg))}[data-learning-lab="micro-chiplet"] .mc-feedback{min-height:1.6em;color:var(--fg-soft);font-size:13px}[data-learning-lab="micro-chiplet"] .mc-ok{color:var(--mc-green);font-weight:700}[data-learning-lab="micro-chiplet"] .mc-no{color:var(--mc-red);font-weight:700}[data-learning-lab="micro-chiplet"] .mc-note{color:var(--fg-soft);font-size:13px;line-height:1.7}',
    '[data-learning-lab="micro-chiplet"] .mc-metrics{display:grid;grid-template-columns:repeat(auto-fit,minmax(125px,1fr));gap:8px;margin:12px 0}[data-learning-lab="micro-chiplet"] .mc-metric{min-width:0;padding:9px;border-top:2px solid var(--border);background:var(--bg)}[data-learning-lab="micro-chiplet"] .mc-metric span{display:block;color:var(--fg-soft);font-size:11.5px}[data-learning-lab="micro-chiplet"] .mc-metric strong{display:block;margin-top:3px;font-size:15px;font-variant-numeric:tabular-nums;overflow-wrap:anywhere}',
    '@media(max-width:820px){[data-learning-lab="micro-chiplet"] .mc-layout{grid-template-columns:minmax(0,1fr)}}@media(prefers-reduced-motion:reduce){[data-learning-lab="micro-chiplet"] *{transition:none!important;animation:none!important}}'
  ].join("");

  function assert(condition, message) { if (!condition) throw new Error(message); }
  function near(a, b, tolerance) { return Math.abs(a - b) <= (tolerance || 1e-9) * Math.max(1, Math.abs(a), Math.abs(b)); }
  function format(value, digits) {
    var places = digits === undefined ? 2 : Number(digits);
    var text = Number(value).toFixed(places);
    return places === 0 ? text : text.replace(/0+$/, "").replace(/\.$/, "");
  }
  function element(doc, tag, attrs, children) { var node = doc.createElement(tag); Object.keys(attrs || {}).forEach(function (key) { var value = attrs[key]; if (value === undefined || value === null || value === false) return; if (key === "className") node.setAttribute("class", String(value)); else if (key === "htmlFor") node.setAttribute("for", String(value)); else if (key === "text") node.textContent = String(value); else if (value === true) node.setAttribute(key, ""); else node.setAttribute(key, String(value)); }); (Array.isArray(children) ? children : children === undefined ? [] : [children]).forEach(function (child) { if (child !== undefined && child !== null && child !== false) node.appendChild(child.nodeType ? child : doc.createTextNode(String(child))); }); return node; }
  function svgElement(doc, tag, attrs, children) { var node = doc.createElementNS(SVG_NS, tag); Object.keys(attrs || {}).forEach(function (key) { if (attrs[key] !== undefined && attrs[key] !== null) node.setAttribute(key, String(attrs[key])); }); (Array.isArray(children) ? children : children === undefined ? [] : [children]).forEach(function (child) { if (child !== undefined && child !== null) node.appendChild(child.nodeType ? child : doc.createTextNode(String(child))); }); return node; }
  function clear(node) { while (node.firstChild) node.removeChild(node.firstChild); }
  function installStyles(doc) { if (!doc || !doc.createElement || (doc.getElementById && doc.getElementById(STYLE_ID))) return; var style = doc.createElement("style"); style.id = STYLE_ID; style.textContent = STYLE_TEXT; (doc.head || doc.documentElement).appendChild(style); }
  function announce(api, rootNode, message) { if (api && typeof api.announce === "function") api.announce(rootNode, message); }
  function dieYield(areaMm2) { var areaCm2 = areaMm2 / 100; return Math.pow(1 + areaCm2 * 0.1 / 2, -2); }
  function normalize(input) {
    var source = input || {}; var totalArea = Number(source.totalArea === undefined ? DEFAULTS.totalArea : source.totalArea); var chiplets = Math.round(Number(source.chiplets === undefined ? DEFAULTS.chiplets : source.chiplets)); var trafficGbit = Number(source.trafficGbit === undefined ? DEFAULTS.trafficGbit : source.trafficGbit); var linkEnergy = Number(source.linkEnergy === undefined ? DEFAULTS.linkEnergy : source.linkEnergy); var packageYield = Number(source.packageYield === undefined ? DEFAULTS.packageYield : source.packageYield); var topology = source.topology === undefined ? DEFAULTS.topology : String(source.topology);
    if (totalArea < 200 || totalArea > 1200 || [1, 2, 4, 8].indexOf(chiplets) === -1 || trafficGbit < 0 || trafficGbit > 20 || linkEnergy < 0.1 || linkEnergy > 8 || packageYield <= 0 || packageYield > 1 || ["2.5D", "3D"].indexOf(topology) === -1) throw new RangeError("invalid chiplet controls");
    return { totalArea: totalArea, chiplets: chiplets, trafficGbit: trafficGbit, linkEnergy: linkEnergy, packageYield: packageYield, topology: topology };
  }
  function simulate(input) {
    var config = normalize(input); var dieArea = config.totalArea / config.chiplets; var localYield = dieYield(dieArea); var systemYield = Math.pow(localYield, config.chiplets) * (config.chiplets === 1 ? 1 : config.packageYield); var linkEnergyMJ = config.chiplets === 1 ? 0 : config.trafficGbit * config.linkEnergy; var thermalLoad = 120 * (1 + 0.03 * (config.chiplets - 1)) * (config.topology === "3D" ? 1.35 : 1); return { config: config, dieArea: dieArea, localYield: localYield, systemYield: systemYield, linkEnergyMJ: linkEnergyMJ, thermalLoad: thermalLoad, thermalPass: thermalLoad <= 150 };
  }
  function mount(rootNode, api) {
    var doc = rootNode.ownerDocument || document; installStyles(doc); clear(rootNode); var title = element(doc, "h3", { text: "Chiplet 实验：良率换通信" }); var note = element(doc, "p", { className: "mc-note", text: "先预测：默认 4 chiplet 的系统良率会超过单片吗？" });
    var predict = element(doc, "div", { className: "mc-predict" }, [element(doc, "label", { htmlFor: LAB_ID + "-prediction", text: "默认参数下，4 chiplet 相对单片的系统良率：" }), element(doc, "select", { id: LAB_ID + "-prediction", "aria-label": "Chiplet 良率预测" }, [element(doc, "option", { value: "lower", text: "更低（要乘四颗与封装）" }), element(doc, "option", { value: "higher", text: "更高，直接等于小片 Y" }), element(doc, "option", { value: "same", text: "相同" })]), element(doc, "button", { type: "button", text: "检验预测" }), element(doc, "div", { className: "mc-feedback", "aria-live": "polite" })]);
    var controls = element(doc, "div", { className: "mc-controls" });
    function addRange(label, id, min, max, step, value, suffix, digits) { var output = element(doc, "output", { for: id, text: format(value, digits) + suffix }); var input = element(doc, "input", { id: id, type: "range", min: min, max: max, step: step, value: value }); input.addEventListener("input", function () { output.textContent = format(Number(input.value), digits) + suffix; render(); }); controls.appendChild(element(doc, "div", { className: "mc-control" }, [element(doc, "label", { htmlFor: id, text: label }), output, input])); return input; }
    var pieces = element(doc, "select", { id: LAB_ID + "-pieces" }, [1, 2, 4, 8].map(function (value) { return element(doc, "option", { value: String(value), text: value + " 颗" }); })); pieces.value = "4"; pieces.addEventListener("change", render); controls.appendChild(element(doc, "div", { className: "mc-control" }, [element(doc, "label", { htmlFor: pieces.id, text: "Chiplet 数量" }), pieces]));
    var traffic = addRange("跨裸片流量", LAB_ID + "-traffic", 0, 20, 0.5, DEFAULTS.trafficGbit, " Gbit", 1); var link = addRange("互连能耗", LAB_ID + "-link", 0.5, 5, 0.5, DEFAULTS.linkEnergy, " pJ/bit", 1);
    var topology = element(doc, "select", { id: LAB_ID + "-topology" }, [element(doc, "option", { value: "2.5D", text: "2.5D 并排" }), element(doc, "option", { value: "3D", text: "3D 堆叠" })]); topology.value = DEFAULTS.topology; topology.addEventListener("change", render); controls.appendChild(element(doc, "div", { className: "mc-control" }, [element(doc, "label", { htmlFor: topology.id, text: "封装拓扑" }), topology]));
    var stage = element(doc, "div", { className: "mc-stage" }); var result = element(doc, "div"); rootNode.appendChild(title); rootNode.appendChild(note); rootNode.appendChild(predict); rootNode.appendChild(element(doc, "div", { className: "mc-layout" }, [controls, element(doc, "div", {}, [stage, result])]));
    function renderStage(data) { var chart = svgElement(doc, "svg", { viewBox: "0 0 720 315", role: "img", "aria-label": "不同 chiplet 数量的系统良率与跨裸片能耗散点图" }); chart.appendChild(svgElement(doc, "title", {}, "Chiplet 系统权衡")); chart.appendChild(svgElement(doc, "desc", {}, "横轴为跨裸片通信能耗，纵轴为系统良率；红点为当前选择，蓝点为其他切分。")); var left = 58, top = 22, width = 620, height = 230; function x(value) { return left + Math.min(value, 100) / 100 * width; } function y(value) { return top + height * (1 - value); } [0, .25, .5, .75, 1].forEach(function (tick) { var yy = y(tick); chart.appendChild(svgElement(doc, "line", { x1: left, y1: yy, x2: left + width, y2: yy, class: "mc-grid" })); chart.appendChild(svgElement(doc, "text", { x: left - 8, y: yy + 4, "text-anchor": "end", "font-size": 11 }, format(tick * 100, 0) + "%")); }); [0, 25, 50, 75, 100].forEach(function (tick) { chart.appendChild(svgElement(doc, "text", { x: x(tick), y: top + height + 21, "text-anchor": "middle", "font-size": 11 }, tick + " mJ")); }); [1, 2, 4, 8].forEach(function (piecesCount) { var point = simulate({ totalArea: data.config.totalArea, chiplets: piecesCount, trafficGbit: data.config.trafficGbit, linkEnergy: data.config.linkEnergy, packageYield: data.config.packageYield, topology: data.config.topology }); chart.appendChild(svgElement(doc, "circle", { cx: x(point.linkEnergyMJ), cy: y(point.systemYield), r: piecesCount === data.config.chiplets ? 7 : 5, class: piecesCount === data.config.chiplets ? "mc-selected" : "mc-point" })); chart.appendChild(svgElement(doc, "text", { x: x(point.linkEnergyMJ) + 8, y: y(point.systemYield) + 4, "font-size": 11 }, piecesCount + "x")); }); chart.appendChild(svgElement(doc, "text", { x: left, y: 287, "font-size": 11 }, "横轴：跨裸片通信能耗   纵轴：全部裸片与封装同时合格的概率")); stage.replaceChildren(chart); }
    function render() { var data = simulate({ totalArea: DEFAULTS.totalArea, chiplets: Number(pieces.value), trafficGbit: Number(traffic.value), linkEnergy: Number(link.value), packageYield: DEFAULTS.packageYield, topology: topology.value }); renderStage(data); result.replaceChildren(element(doc, "div", { className: "mc-metrics" }, [element(doc, "div", { className: "mc-metric" }, [element(doc, "span", { text: "单颗面积" }), element(doc, "strong", { text: format(data.dieArea, 0) + " mm²" })]), element(doc, "div", { className: "mc-metric" }, [element(doc, "span", { text: "单颗裸片 Y" }), element(doc, "strong", { text: format(data.localYield * 100, 1) + "%" })]), element(doc, "div", { className: "mc-metric" }, [element(doc, "span", { text: "系统 Y" }), element(doc, "strong", { text: format(data.systemYield * 100, 1) + "%" })]), element(doc, "div", { className: "mc-metric" }, [element(doc, "span", { text: "跨裸片能耗" }), element(doc, "strong", { text: format(data.linkEnergyMJ, 1) + " mJ" })]), element(doc, "div", { className: "mc-metric" }, [element(doc, "span", { text: "热负载" }), element(doc, "strong", { className: data.thermalPass ? "mc-ok" : "mc-no", text: format(data.thermalLoad, 1) + " W" })]) ])); }
    predict.querySelector("button").addEventListener("click", function () { var answer = predict.querySelector("select").value; var mono = simulate({ totalArea: 600, chiplets: 1, trafficGbit: 8, linkEnergy: 2, packageYield: 0.96, topology: "2.5D" }); var split = simulate(DEFAULTS); var ok = answer === "lower" && split.systemYield < mono.systemYield; var feedback = predict.querySelector(".mc-feedback"); feedback.className = "mc-feedback " + (ok ? "mc-ok" : "mc-no"); feedback.textContent = ok ? "正确：小片 Y 提高后仍要乘四颗与封装良率，默认 toy 参数下系统 Y 约 53.8%，低于单片约 59.2%。" : "再计算 Ysystem=Ysmall^4*Ypkg，而不是把单颗小片 Y 当整机 Y。"; announce(api, rootNode, feedback.textContent); });
    render();
  }
  function selfTest() { var checks = 0; function check(condition, message) { checks += 1; assert(condition, message); } check(near(dieYield(600), Math.pow(1 + 6 * 0.1 / 2, -2)), "monolithic yield"); var mono = simulate({ totalArea: 600, chiplets: 1, trafficGbit: 8, linkEnergy: 2, packageYield: 0.96, topology: "2.5D" }); var split = simulate(DEFAULTS); check(near(split.dieArea * split.config.chiplets, split.config.totalArea), "area conservation"); check(split.systemYield < split.localYield, "system yield multiplies"); check(near(mono.linkEnergyMJ, 0), "monolithic has no cross-die link energy"); check(near(split.linkEnergyMJ, 16), "link energy conversion"); check(near(split.systemYield, Math.pow(dieYield(150), 4) * 0.96), "system yield calculation"); check(split.systemYield < mono.systemYield, "default split is not automatically better"); check(simulate({ totalArea: 600, chiplets: 4, trafficGbit: 8, linkEnergy: 2, packageYield: 0.96, topology: "3D" }).thermalLoad > split.thermalLoad, "3D thermal penalty"); return { checks: checks }; }
  return { dieYield: dieYield, simulate: simulate, mount: mount, selfTest: selfTest };
});
