(function(hostWindow,factory){const api=factory(hostWindow);if(typeof module==='object'&&module.exports)module.exports=api;if(hostWindow&&hostWindow.CourseLearning)hostWindow.CourseLearning.register('qec-channel',api.mount);})(typeof window!=='undefined'?window:null,function(hostWindow){
'use strict';
// Complex matrices retain Pauli global phases until density matrices are formed.
const C=(r=0,i=0)=>[r,i],add=(a,b)=>C(a[0]+b[0],a[1]+b[1]),mul=(a,b)=>C(a[0]*b[0]-a[1]*b[1],a[0]*b[1]+a[1]*b[0]),conj=a=>C(a[0],-a[1]),scale=(a,t)=>C(a[0]*t,a[1]*t),abs2=a=>a[0]*a[0]+a[1]*a[1];
const zero=(n,m=n)=>Array.from({length:n},()=>Array.from({length:m},()=>C())),eye=n=>Array.from({length:n},(_,i)=>Array.from({length:n},(_,j)=>C(i===j?1:0)));
const dagger=A=>A[0].map((_,j)=>A.map(r=>conj(r[j]))),mm=(A,B)=>A.map(r=>B[0].map((_,j)=>r.reduce((z,a,k)=>add(z,mul(a,B[k][j])),C()))),ms=(A,t)=>A.map(r=>r.map(z=>scale(z,t))),ma=(A,B)=>A.map((r,i)=>r.map((z,j)=>add(z,B[i][j]))),tr=A=>A.reduce((z,r,i)=>add(z,r[i]),C());
const PAULI={I:eye(2),X:[[C(),C(1)],[C(1),C()]],Y:[[C(),C(0,-1)],[C(0,1),C()]],Z:[[C(1),C()],[C(),C(-1)]]};
const kron=(A,B)=>A.flatMap(r=>B.map(s=>r.flatMap(a=>s.map(b=>mul(a,b))))),tensor=word=>Array.from(word).reduce((a,k)=>kron(a,PAULI[k]),[[C(1)]]);
const MODELS=['pauli','independent','correlated','depolarizing','coherentSingle','coherentAll'];
const DEFAULT={model:'coherentAll',error:'IXI',p:.1,axis:'X',angle:.6,site:2,theta:Math.PI/2,phi:Math.PI/2};
function config(input={}){if(!input||typeof input!=='object'||Array.isArray(input))throw Error('config object');for(const k of Object.keys(input))if(!Object.hasOwn(DEFAULT,k))throw Error('unknown '+k);const q={...DEFAULT,...input};if(!MODELS.includes(q.model)||!['X','Z'].includes(q.axis)||typeof q.error!=='string'||!/^[IXYZ]{3}$/.test(q.error))throw Error('choice');for(const[k,lo,hi]of[['p',0,1],['angle',-Math.PI,Math.PI],['theta',0,Math.PI],['phi',-Math.PI,Math.PI],['site',1,3]])if(typeof q[k]!=='number'||!Number.isFinite(q[k])||q[k]<lo||q[k]>hi)throw Error(k);if(!Number.isInteger(q.site))throw Error('site integer');return q;}
function syndromeIndex(x){const a=(x>>2)&1,b=(x>>1)&1,c=x&1;return((a^b)<<1)|(b^c);}
const CORRECTIONS=[0,1,4,2],SIGNS=['++','+-','-+','--'];
function logicalK(E,s){const A=zero(2),corr=CORRECTIONS[s];for(let i=0;i<2;i++)for(let j=0;j<2;j++){const row=(i?7:0)^corr;if(syndromeIndex(row)===s)A[i][j]=E[row][j?7:0];}return A;}
function rotation(axis,angle){const c=Math.cos(angle/2),s=Math.sin(angle/2);return ma(ms(PAULI.I,c),PAULI[axis].map(r=>r.map(z=>mul(C(0,-s),z))));}
function noise(q){const rows=[];const put=(label,weight,matrix)=>rows.push({label,weight,matrix:ms(matrix,Math.sqrt(weight))});if(q.model==='pauli')put(q.error,1,tensor(q.error));
else if(q.model==='correlated'){put('III',1-q.p,eye(8));put('XXX',q.p,tensor('XXX'));}
else if(['independent','depolarizing'].includes(q.model)){const letters=q.model==='independent'?'IX':'IXYZ';for(const a of letters)for(const b of letters)for(const c of letters){const word=a+b+c;let weight=1;for(const p of word)weight*=p==='I'?1-q.p:q.p/(letters.length-1);put(word,weight,tensor(word));}}
else{let E=[[C(1)]];for(let j=1;j<=3;j++)E=kron(E,q.model==='coherentAll'||q.site===j?rotation(q.axis,q.angle):eye(2));put(q.model,1,E);}return rows;}
function rhoInput(q){const psi=[C(Math.cos(q.theta/2)),C(Math.sin(q.theta/2)*Math.cos(q.phi),Math.sin(q.theta/2)*Math.sin(q.phi))];return{psi,rho:psi.map(a=>psi.map(b=>mul(a,conj(b))))};}
function channel(ks,rho){return ks.reduce((a,K)=>ma(a,mm(mm(K,rho),dagger(K))),zero(2));}
function fidelity(rho,sigma){return tr(mm(rho,sigma))[0];}
function bloch(rho){return['X','Y','Z'].map(k=>tr(mm(rho,PAULI[k]))[0]);}
function pauliRows(){const rows=[];for(const a of 'IXYZ')for(const b of 'IXYZ')for(const c of 'IXYZ'){const word=a+b+c,E=tensor(word),mask=Array.from(word).reduce((m,k)=>2*m+('XY'.includes(k)?1:0),0),s=syndromeIndex(mask),K=logicalK(E,s);const coeff=Object.fromEntries(Object.entries(PAULI).map(([k,P])=>[k,scale(tr(mm(P,K)),.5)]));const logical=Object.keys(coeff).find(k=>abs2(coeff[k])>.5);rows.push({word,weight:Array.from(word).filter(k=>k!=='I').length,bitMask:mask,syndrome:SIGNS[s],correctionMask:CORRECTIONS[s],logical,phase:coeff[logical],matrix:K,universallyCorrected:logical==='I'});}return rows;}
function reference(q,rho,ledger){if(q.model==='coherentSingle'||q.model==='coherentAll'){if(q.axis==='Z'){const angle=q.angle*(q.model==='coherentAll'?3:1),U=rotation('Z',angle);return{kind:'logical Z rotation',q:null,kappa:null,rho:mm(mm(U,rho),dagger(U))};}if(q.model==='coherentSingle')return{kind:'single X rotation corrected',q:0,kappa:0,rho};const c=Math.cos(q.angle/2),s=Math.sin(q.angle/2),p=3*c*c*s**4+s**6,kappa=2*c**3*s**3;const comm=ma(mm(PAULI.X,rho),ms(mm(rho,PAULI.X),-1)),r=ma(ma(ms(rho,1-p),ms(mm(mm(PAULI.X,rho),PAULI.X),p)),comm.map(row=>row.map(z=>mul(C(0,-kappa),z))));return{kind:'coherent X polynomial',q:p,kappa,rho:r};}
const weights={I:0,X:0,Y:0,Z:0};for(const row of ledger){let p;if(q.model==='pauli')p=row.word===q.error?1:0;else if(q.model==='correlated')p=row.word==='III'?1-q.p:row.word==='XXX'?q.p:0;else{p=1;for(const k of row.word)p*=k==='I'?1-q.p:q.model==='independent'?(k==='X'?q.p:0):q.p/3;}weights[row.logical]+=p;}return{kind:'Pauli residual enumeration',weights,q:weights.X,kappa:0,rho:Object.entries(weights).reduce((a,[k,p])=>ma(a,ms(mm(mm(PAULI[k],rho),PAULI[k]),p)),zero(2))};}
function evaluate(input={}){const q=config(input),initial=rhoInput(q),errors=noise(q),branches=[],ks=[];for(const e of errors)for(let s=0;s<4;s++){const K=logicalK(e.matrix,s),unnormalized=mm(mm(K,initial.rho),dagger(K)),probability=tr(unnormalized)[0];ks.push(K);branches.push({error:e.label,weight:e.weight,syndrome:SIGNS[s],correctionMask:CORRECTIONS[s],K,probability,unnormalized,conditional:probability>0?ms(unnormalized,1/probability):null});}
const output=channel(ks,initial.rho),completeness=ks.reduce((a,K)=>ma(a,mm(dagger(K),K)),zero(2)),ptm=Object.keys(PAULI).map(i=>Object.keys(PAULI).map(j=>.5*tr(mm(PAULI[i],channel(ks,PAULI[j])))[0])),paulis=pauliRows(),ref=reference(q,initial.rho,paulis),syndromes=SIGNS.map(s=>{const chosen=branches.filter(b=>b.syndrome===s),probability=chosen.reduce((v,b)=>v+b.probability,0),density=chosen.reduce((v,b)=>ma(v,b.unnormalized),zero(2));return{syndrome:s,probability,unnormalized:density,conditional:probability>0?ms(density,1/probability):null};});
return{schema:'qec-channel-v1',parameters:q,initial,noise:errors,branches,syndromes,output,outputBloch:bloch(output),inputBloch:bloch(initial.rho),fidelity:fidelity(initial.rho,output),purity:tr(mm(output,output))[0],completeness,tracePreservationDefect:Math.max(...ma(completeness,ms(eye(2),-1)).flat().map(z=>Math.sqrt(abs2(z)))),normalizationDefect:tr(output)[0]-1,pauliTransferMatrix:ptm,paulis,reference:ref,referenceDefect:Math.max(...ma(output,ms(ref.rho,-1)).flat().map(z=>Math.sqrt(abs2(z)))),independentFailure:3*q.p*q.p*(1-q.p)+q.p**3,correlatedFailure:q.p};}

'use strict';
const parity=x=>{let p=0;for(;x;x&=x-1)p^=1;return p;};
function masks(word){let x=0,z=0,y=0;for(const k of word){x=(x<<1)|('XY'.includes(k)?1:0);z=(z<<1)|('ZY'.includes(k)?1:0);y+=k==='Y';}return{x,z,y};}
function sparsePauli(word,state){const{x,z,y}=masks(word),phase=[C(1),C(0,1),C(-1),C(0,-1)][y%4],out={};for(const[index,a]of Object.entries(state))out[(+index)^x]=scale(mul(phase,a),parity(z&(+index))?-1:1);return out;}
const dot=(a,b)=>Object.entries(a).reduce((v,[i,z])=>add(v,mul(conj(z),b[i]||C())),C());
const SHOR_GENERATORS=['ZZIIIIIII','IZZIIIIII','IIIZZIIII','IIIIZZIII','IIIIIIZZI','IIIIIIIZZ','XXXXXXIII','IIIXXXXXX'];
function shorData(){const basis=[{},{}];for(let b=0;b<8;b++){const index=((b&4)?448:0)|((b&2)?56:0)|((b&1)?7:0);basis[0][index]=C(1/Math.sqrt(8));basis[1][index]=C((parity(b)?-1:1)/Math.sqrt(8));}
const gens=SHOR_GENERATORS.map(word=>({word,...masks(word)}));
function syndrome(word){const e=masks(word);return gens.map(g=>parity(e.x&g.z)^parity(e.z&g.x));}
const group=[];for(let bits=0;bits<256;bits++){let x=0,z=0,state={...basis[0]};for(let j=0;j<8;j++)if(bits&(1<<j)){x^=gens[j].x;z^=gens[j].z;state=sparsePauli(gens[j].word,state);}group.push({bits,x,z,fixesCode0:dot(basis[0],state)});}
const members=new Set(group.map(g=>g.x+','+g.z));
const words=['I'.repeat(9)];for(let j=0;j<9;j++)for(const k of 'XYZ')words.push('I'.repeat(j)+k+'I'.repeat(8-j));
const transformed=words.map(word=>basis.map(v=>sparsePauli(word,v)));
const kl=[];for(let a=0;a<words.length;a++)for(let b=0;b<words.length;b++){const matrix=transformed[a].map(v=>transformed[b].map(w=>dot(v,w))),scalar=scale(add(matrix[0][0],matrix[1][1]),.5),defect=Math.max(...matrix.flatMap((r,i)=>r.map((z,j)=>Math.sqrt(abs2(add(z,scale(i===j?scalar:C(),-1)))))));kl.push({a:words[a],b:words[b],matrix,scalar,defect});}
const errors=words.map((word,i)=>({word,syndrome:syndrome(word),code0:transformed[i][0],code1:transformed[i][1]}));
const distances=[];function enumerate(start,weight,word){if(!weight){const text=word.join(''),e=masks(text),s=syndrome(text),commutes=s.every(v=>v===0),stabilizer=members.has(e.x+','+e.z);distances.push({word:text,weight:word.filter(k=>k!=='I').length,syndrome:s,commutes,stabilizer,nontrivialLogical:commutes&&!stabilizer});return;}for(let j=start;j<=9-weight;j++)for(const k of 'XYZ'){word[j]=k;enumerate(j+1,weight-1,word);word[j]='I';}}
for(let weight=1;weight<=3;weight++)enumerate(0,weight,Array(9).fill('I'));
const commutation=gens.map(g=>gens.map(h=>parity(g.x&h.z)^parity(g.z&h.x))),logicalX='ZIIZIIZII',logicalZ='XXXIIIIII';
return{basis,generators:gens,commutation,group,groupSize:members.size,dimension:512/members.size,errors,knillLaflamme:kl,maxKLDefect:Math.max(...kl.map(r=>r.defect)),distanceEnumeration:distances,distance:Math.min(...distances.filter(r=>r.nontrivialLogical).map(r=>r.weight)),logicalX,logicalZ,logicalXBlock:basis.map(v=>basis.map(w=>dot(v,sparsePauli(logicalX,w)))),logicalZBlock:basis.map(v=>basis.map(w=>dot(v,sparsePauli(logicalZ,w))))};}

const PRESETS=[{key:'coherent',label:'全三位相干X旋转',config:{}},{key:'single',label:'单X旋转可纠正',config:{model:'coherentSingle'}},{key:'phase',label:'单Z旋转不可纠正',config:{model:'coherentSingle',axis:'Z'}},{key:'pauliY',label:'Y的相位残留',config:{model:'pauli',error:'IYI'}},{key:'double',label:'双X伪装单X',config:{model:'pauli',error:'XXI'}},{key:'stabilizer',label:'双Z是稳定子',config:{model:'pauli',error:'ZZI'}},{key:'independent',label:'独立X噪声',config:{model:'independent'}},{key:'correlated',label:'相同边缘，全相关',config:{model:'correlated'}},{key:'depolarizing',label:'独立退极化',config:{model:'depolarizing'}},{key:'zero',label:'零旋转与零分支',config:{angle:0}},{key:'pi',label:'旋转π',config:{angle:Math.PI}},{key:'eigenstate',label:'特定态无损≠通用纠错',config:{model:'pauli',error:'XXX',theta:Math.PI/2,phi:0}}];
const QUESTIONS=[['三比特码测得综合++，能否保证逻辑态没有改变？',['不能，单Z和XXX都可能看不见','能，两个稳定子都已通过'],0],['一位的相干X旋转可否由理想三比特恢复完整纠正？',['不能，误差不是离散翻转','能，两个综合分支恢复同一逻辑态'],1],['全三位相干X旋转与p=sin²(angle/2)的独立随机X噪声是否总是同一通道？',['不是，同综合分支还可能相干叠加','是，逐位翻转概率已相同'],0],['Shor码中Z1与Z2产生同样综合，是否就意味着纠错失败？',['是，必须区分每个物理错误','否，它们在码空间上可有相同作用'],1]];
const EXPLANATIONS=['综合只描述相对稳定子的对易符号。III、逻辑Z以及逻辑X都可能得到++；是否保留任意逻辑态，要检查恢复后的码上算符。','exp(-i angle X/2)=cI-isX。I与单X属于不同综合，分别恢复后都只是原逻辑态乘一个标量；把综合忘掉仍得到原态。','全三位旋转的单错与互补双错会进入同一综合。恢复后留下两个逻辑分量的干涉；总通道含-iκ[X,ρ]，独立随机模型没有这一项。','Z1Z2属于Shor稳定子，所以Z1与Z2对每个码字的作用相同。退化意味着无需辨认这两个物理标签；这和三比特码把单Z误当无错不同。'];
function feedback(i,j){if(!Number.isInteger(i)||i<0||i>=4||![0,1].includes(j))throw Error('choice');const correct=j===QUESTIONS[i][2];return{correct,text:(correct?'预测正确。':'再检查条件。')+EXPLANATIONS[i]};}
function fmt(v){if(v===null)return'不适用';if(typeof v==='boolean')return v?'是':'否';if(Array.isArray(v))return'['+v.map(fmt).join(', ')+']';if(typeof v==='object')return'{'+Object.entries(v).map(([k,z])=>k+':'+fmt(z)).join(', ')+'}';if(typeof v==='number')return v!==0&&(Math.abs(v)<1e-5||Math.abs(v)>1e7)?v.toExponential(5):Number(v.toFixed(6)).toString();return String(v);}
let cachedShor;
function snapshot(input){const s=evaluate(input);if(!cachedShor)cachedShor=shorData();s.shor=cachedShor;s.probabilityScan=Array.from({length:51},(_,i)=>{const p=i/50;return{p,independent:3*p*p-2*p**3,correlated:p,improvement:p-(3*p*p-2*p**3)};});s.angleScan=Array.from({length:81},(_,i)=>{const angle=-Math.PI+2*Math.PI*i/80,q={...s.parameters,model:'coherentAll',axis:'X',angle},r=reference(q,s.initial.rho,s.paulis),p=Math.sin(angle/2)**2,random=reference({...q,model:'independent',p},s.initial.rho,s.paulis);return{angle,p,q:r.q,kappa:r.kappa,coherentState:r.rho,randomState:random.rho,coherentFidelity:fidelity(s.initial.rho,r.rho),randomFidelity:fidelity(s.initial.rho,random.rho),coherentZ:bloch(r.rho)[2],randomZ:bloch(random.rho)[2]};});return s;}
function makePlot(key,title,xLabel,yLabel,series,fixedX){const points=series.flatMap(s=>s.points.filter(Boolean)),xs=points.map(p=>p[0]),ys=points.map(p=>p[1]);let xMin=fixedX?fixedX[0]:Math.min(...xs),xMax=fixedX?fixedX[1]:Math.max(...xs),yMin=Math.min(...ys),yMax=Math.max(...ys);if(xMin===xMax){xMin--;xMax++;}const pad=.08*(yMax-yMin||Math.max(1,Math.abs(yMax)));return{key,title,xLabel,yLabel,xMin,xMax,yMin:yMin-pad,yMax:yMax+pad,series};}
function plots(s){const blue='#2874bd',green='#29825a',orange='#c17814',purple='#9364b7',line=(name,color,points,markersOnly=false)=>({name,color,points,markersOnly});return[
makePlot('syndromes','只读综合：各分支概率','综合编号：0 ++，1 +−，2 −+，3 −−','概率',[line('本次噪声与输入态',blue,s.syndromes.map((r,i)=>[i,r.probability]),true)],[-.3,3.3]),
makePlot('bloch','恢复前后的逻辑Bloch分量','分量编号：0 X，1 Y，2 Z','期望值',[line('输入',green,s.inputBloch.map((v,i)=>[i,v]),true),{...line('恢复后',orange,s.outputBloch.map((v,i)=>[i,v]),true),hollow:true,markerRadius:7}],[-.3,2.3]),
makePlot('probability','独立与全相关X：相同边缘p','每位翻转概率p','通用逻辑X错误概率',[line('独立：3p²−2p³',blue,s.probabilityScan.map(r=>[r.p,r.independent])),line('全相关：p',orange,s.probabilityScan.map(r=>[r.p,r.correlated]))],[0,1]),
makePlot('angle','独立参照：全三位X旋转与随机X噪声','每位旋转角angle（弧度）','恢复后逻辑Z期望',[line('相干旋转',purple,s.angleScan.map(r=>[r.angle,r.coherentZ])),line('独立随机 p=sin²(angle/2)',green,s.angleScan.map(r=>[r.angle,r.randomZ]))],[-Math.PI,Math.PI]),
makePlot('transfer','当前恢复通道的Pauli传递矩阵','行优先编号4i+j；顺序I,X,Y,Z','T_ij=Tr(P_i Φ(P_j))/2',[line('全部16系数',blue,s.pauliTransferMatrix.flat().map((v,i)=>[i,v]),true)],[-.5,15.5]),
makePlot('kl','Shor码：28种错误的784个KL块','错误对编号28a+b','块与标量I之差的最大模',[{...line('逐对矩阵残差',green,s.shor.knillLaflamme.map((r,i)=>[i,r.defect]),true),markerRadius:1,markerStrokeWidth:.3}],[0,783])];}
function tables(s){const matrixRows=(label,A)=>A.flatMap((r,i)=>r.map((z,j)=>[label,i,j,z[0],z[1]]));return[
{key:'parameters',title:'当前参数与界限',headers:['量','值'],rows:[...Object.entries(s.parameters),['分支数（包括零权重）',s.branches.length],['保真度（只针对当前输入）',s.fidelity],['纯度',s.purity],['TP残差',s.tracePreservationDefect],['迹减1',s.normalizationDefect],['解析参照差',s.referenceDefect]]},
{key:'states',title:'输入、输出与独立参照的复密度矩阵',headers:['矩阵','行','列','实部','虚部'],rows:[...matrixRows('输入',s.initial.rho),...matrixRows('输出',s.output),...matrixRows('参照',s.reference.rho),...matrixRows('ΣK†K',s.completeness)]},
{key:'noise',title:'全部物理Kraus矩阵（已含概率平方根）',headers:['噪声','权重','行','列','实部','虚部'],rows:s.noise.flatMap(e=>matrixRows(e.label,e.matrix).map(r=>[r[0],e.weight,...r.slice(1)]))},
{key:'branches',title:'全部恢复分支：复矩阵与条件态',headers:['噪声','综合','概率','恢复X掩码','逻辑K（[实,虚]）','未归一态','条件态'],rows:s.branches.map(r=>[r.error,r.syndrome,r.probability,r.correctionMask,r.K,r.unnormalized,r.conditional])},
{key:'syndromes',title:'只保留综合后，合并经典噪声标签',headers:['综合','概率','未归一态','条件态'],rows:s.syndromes.map(r=>[r.syndrome,r.probability,r.unnormalized,r.conditional])},
{key:'paulis',title:'三位64种Pauli：通用纠错与特定输入保真度不同',headers:['Pauli','权重','X掩码','综合','恢复掩码','逻辑Pauli','整体相位','逻辑矩阵','任意逻辑态均恢复'],rows:s.paulis.map(r=>[r.word,r.weight,r.bitMask,r.syndrome,r.correctionMask,r.logical,r.phase,r.matrix,r.universallyCorrected])},
{key:'scan',title:'X旋转独立参照：完整解析通道扫描',headers:['angle','随机p','逻辑X权重q','相干κ','相干保真度','随机保真度','相干Z','随机Z','相干输出态','随机输出态'],rows:s.angleScan.map(r=>[r.angle,r.p,r.q,r.kappa,r.coherentFidelity,r.randomFidelity,r.coherentZ,r.randomZ,r.coherentState,r.randomState])},
{key:'shor',title:'Shor生成元、码基与28种错误综合',headers:['种类','Pauli','综合或X掩码','Z掩码或空','码基0或其错后振幅','码基1或其错后振幅'],rows:[['码基','III…III',null,null,...s.shor.basis],...s.shor.generators.map(r=>['生成元',r.word,r.x,r.z,null,null]),...s.shor.errors.map(r=>['错误',r.word,r.syndrome,null,r.code0,r.code1])]},
{key:'kl',title:'784个Knill–Laflamme矩阵块',headers:['错误a','错误b','V†Ea†EbV','标量C_ab','最大残差'],rows:s.shor.knillLaflamme.map(r=>[r.a,r.b,r.matrix,r.scalar,r.defect])},
{key:'distance',title:'Shor码距：逐一枚举权重1至3',headers:['Pauli','权重','综合','与稳定子对易','属于稳定子（忽略整体相位）','非平凡逻辑算符'],rows:s.shor.distanceEnumeration.map(r=>[r.word,r.weight,r.syndrome,r.commutes,r.stabilizer,r.nontrivialLogical])},
{key:'probability',title:'独立与相关X噪声的完整概率扫描',headers:['p','独立逻辑X概率','全相关逻辑X概率','p减独立错误概率'],rows:s.probabilityScan.map(r=>[r.p,r.independent,r.correlated,r.improvement])},
{key:'transfer',title:'Pauli传递矩阵与Bloch读数',headers:['行Pauli','列Pauli','传递系数'],rows:s.pauliTransferMatrix.flatMap((r,i)=>r.map((v,j)=>['IXYZ'[i],'IXYZ'[j],v]))},
{key:'group',title:'Shor稳定子群：全部256个生成元组合',headers:['生成元选择位掩码','X掩码','Z掩码','对码基0的期望'],rows:s.shor.group.map(r=>[r.bits,r.x,r.z,r.fixesCode0])}
];}

function svg(p){const left=100,right=855,top=95,bottom=385,X=v=>left+(v-p.xMin)/(p.xMax-p.xMin)*(right-left),Y=v=>bottom-(v-p.yMin)/(p.yMax-p.yMin)*(bottom-top),esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let out='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 900 540" role="img" aria-label="'+esc(p.title)+'"><title>'+esc(p.title)+'</title><style>text{font:15px system-ui;fill:currentColor}</style><text x="30" y="30" font-weight="700">'+esc(p.title)+'</text><text x="25" y="70">'+esc(p.yLabel)+'</text>';
const axisFmt=v=>v===0?'0':Math.abs(v)<1e-3||Math.abs(v)>=1e4?v.toExponential(2):Number(v.toFixed(3)).toString();
for(let i=0;i<=4;i++){const y=p.yMin+(p.yMax-p.yMin)*i/4;out+='<line x1="100" x2="855" y1="'+Y(y)+'" y2="'+Y(y)+'" stroke="currentColor" opacity=".18"/><text x="85" y="'+(Y(y)+5)+'" text-anchor="end">'+axisFmt(y)+'</text>';}
const xTicks=p.key==='syndromes'?[0,1,2,3]:p.key==='bloch'?[0,1,2]:p.key==='transfer'?[0,4,8,12,15]:p.key==='kl'?[0,196,392,588,783]:Array.from({length:5},(_,i)=>p.xMin+(p.xMax-p.xMin)*i/4);
for(const x of xTicks)out+='<text x="'+X(x)+'" y="410" text-anchor="middle">'+axisFmt(x)+'</text>';
out+='<text x="477" y="442" text-anchor="middle">'+esc(p.xLabel)+'</text>';
p.series.forEach((s,i)=>{let pen=false;const path=s.points.map(q=>{if(!q){pen=false;return '';}const d=(pen&&!s.markersOnly?'L':'M')+X(q[0]).toFixed(6)+','+Y(q[1]).toFixed(6);pen=true;return d;}).join(' ');out+='<path data-series="'+i+'" d="'+path+'" stroke="'+s.color+'" stroke-width="2.8" fill="none"/>';const marks=s.markersOnly?s.points.filter(Boolean):s.boundaryMarkers?[s.points[0],s.points.at(-1)]:s.points.filter(Boolean).length===1?s.points.filter(Boolean):[];marks.forEach(q=>out+='<circle cx="'+X(q[0])+'" cy="'+Y(q[1])+'" r="'+(s.markerRadius??5)+'" stroke="'+s.color+'" fill="'+(s.hollow?'none':s.open?'var(--bg,#fff)':s.color)+'" stroke-width="'+(s.markerStrokeWidth??2.5)+'"/>');out+='<line x1="'+(40+430*(i%2))+'" x2="'+(60+430*(i%2))+'" y1="'+(473+32*Math.floor(i/2))+'" y2="'+(473+32*Math.floor(i/2))+'" stroke="'+s.color+'" stroke-width="3"/><text x="'+(68+430*(i%2))+'" y="'+(478+32*Math.floor(i/2))+'">'+esc(s.name)+'</text>';});return out+'</svg>';}

  var mounted=new WeakMap();
  function mount(root){const METRICS=QUESTIONS.map((q,i)=>({key:String(i),label:q[0]}));var doc=root.ownerDocument;var previous=mounted.get(root);if(previous)previous();var url=null,c=config(),choices={},revealed=false,view=0;root.replaceChildren();root.classList.add('qc177');
    function el(tag,attrs={},text){var e=doc.createElement(tag);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v));if(text!==undefined)e.textContent=text;return e;}
    if(!doc.querySelector('[data-qc177-style]')){let style=el('style',{'data-qc177-style':''});style.textContent='.qc177{min-width:0;color:var(--fg,#222);line-height:1.65}.qc177 *{box-sizing:border-box}.qc177 button,.qc177 select{font:inherit;min-height:44px;padding:8px;border:1px solid var(--border,#aaa);border-radius:5px;background:var(--block-bg,#eee);color:inherit;max-width:100%;white-space:normal}.qc177 button[aria-pressed="true"]{outline:2px solid var(--accent,#a33)}.qc177 button:focus-visible,.qc177 select:focus-visible,.qc177 [tabindex]:focus-visible{outline:3px solid #2474bc}.qc177 .qc-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.qc177 label{display:grid;gap:4px;min-width:0}.qc177 input{width:100%;min-height:44px}.qc177 .qc-row{display:flex;gap:8px;flex-wrap:wrap;margin:10px 0}.qc177 .qc-pred>strong{display:block;margin-bottom:6px}.qc177 .qc-pred{padding:10px 0;border-top:1px solid var(--border,#aaa)}.qc177 .qc-feedback{margin:7px 0}.qc177 .qc-scroll{max-width:100%;overflow:auto}.qc177 svg{display:block;min-width:680px;width:100%;height:auto}.qc177 table{display:table;overflow:visible;max-width:none;border-collapse:collapse;width:max-content;min-width:100%;font-variant-numeric:tabular-nums}.qc177 td,.qc177 th{white-space:nowrap;text-align:right;padding:7px;border:1px solid var(--border,#bbb)}.qc177 [hidden]{display:none!important}.qc177 details{margin:12px 0}.qc177 summary{min-height:44px;cursor:pointer}.qc177 .qc-status{border-left:3px solid var(--accent,#a33);padding:8px 12px}.qc177 .qc-correct{color:var(--cl-green,#277540)}.qc177 .qc-wrong{color:var(--cl-red,#a33)}@media(max-width:600px){.qc177 .qc-grid{grid-template-columns:1fr}}';doc.head.appendChild(style);}
    root.append(el('h3',{},'只测综合之后，逻辑态真的恢复了吗？'));
    root.append(el('p',{},'完整枚举噪声Kraus算符与四个综合，直接计算恢复后的复密度矩阵。本页没有随机抽样；理想恢复电路本身不加噪声。'));
    var presets=el('div',{class:'qc-row','aria-label':'教学预设'});PRESETS.forEach(p=>{let b=el('button',{type:'button','data-preset':p.key},p.label);b.onclick=()=>{c=config(p.config);sync();reset();};presets.append(b);});root.append(presets);
    var fields={},grid=el('div',{class:'qc-grid'});
    function select(key,title,options){let label=el('label',{},title),input=el('select',{'data-field':key,'aria-label':title});options.forEach(([v,t])=>input.append(el('option',{value:v},t)));label.append(input);grid.append(label);fields[key]=input;input.onchange=()=>{c[key]=key==='site'?Number(input.value):input.value;sync();reset();};}
    select('model','噪声模型',[['pauli','确定Pauli'],['independent','独立X'],['correlated','全相关XXX'],['depolarizing','独立退极化'],['coherentSingle','单比特相干旋转'],['coherentAll','全三位相干旋转']]);select('error','确定Pauli模型所用错误',pauliRows().map(r=>[r.word,r.word]));select('axis','相干旋转轴（随机模型不使用）',[['X','X'],['Z','Z']]);select('site','单比特旋转位置（其他模型不使用）',[[1,'第1位'],[2,'第2位'],[3,'第3位']]);
    var outs={};[['p','随机模型每位错误概率p',0,1,'any'],['angle','每位相干旋转角（弧度）',-Math.PI,Math.PI,'any'],['theta','逻辑输入Bloch极角θ（弧度）',0,Math.PI,'any'],['phi','逻辑输入相对相位φ（弧度）',-Math.PI,Math.PI,'any']].forEach(([key,title,min,max,step])=>{let label=el('label',{},title),out=el('output'),input=el('input',{type:'range',min,max,step,'data-field':key,'aria-label':title});label.append(out,input);grid.append(label);fields[key]=input;outs[key]=out;input.oninput=()=>{c[key]=+input.value;sync();reset();};});root.append(grid);
    var rateNote=el('p'),prediction=el('section',{'aria-label':'先预测'});root.append(rateNote,prediction);prediction.append(el('h4',{},'先预测：连续误差、逻辑残留与退化'),el('p',{},'四道题的数学条件写在题干里。旋钮用于对照和找反例，不会自动改写题目。'));
    var predButtons={},feedbacks={};METRICS.forEach(m=>{let row=el('div',{class:'qc-pred'});row.append(el('strong',{},m.label));predButtons[m.key]=[];[true,false].forEach(v=>{let b=el('button',{type:'button','data-prediction':m.key,'data-choice':String(v),'aria-pressed':'false'},QUESTIONS[+m.key][1][v?0:1]);b.onclick=()=>{choices[m.key]=v;predButtons[m.key].forEach(b=>b.setAttribute('aria-pressed',String(b.getAttribute('data-choice')===String(v))));if(revealed)showFeedback();};predButtons[m.key].push(b);row.append(b);});let f=el('p',{class:'qc-feedback','data-feedback':m.key});feedbacks[m.key]=f;row.append(f);prediction.append(row);});
    var check=el('button',{type:'button','data-check':''},'核对预测并显示结果'),status=el('p',{class:'qc-status','aria-live':'polite'});root.append(check,status);
    var stage=el('section',{'data-stage':'',hidden:'','aria-label':'实验结果'}),plotButtons=el('div',{class:'qc-row'}),plotWrap=el('div',{class:'qc-scroll',tabindex:'0',role:'region','aria-label':'图表，可横向滚动'}),plotNote=el('p',{},'概率与Bloch图只画离散节点。p扫描和X旋转扫描是明确标出的独立解析参照；当前噪声由参数表确定。数值残差保留浮点末位。'),summary=el('p'),tableHost=el('div'),download=el('a',{'data-download':'',download:'qec-channel-record.json'},'下载当前完整数值记录（JSON）');stage.append(summary,plotButtons,plotWrap,plotNote,tableHost,download);root.append(stage);var current;
    function showFeedback(){let total=0;METRICS.forEach(m=>{if(typeof choices[m.key]!=='boolean')return;let f=feedback(+m.key,choices[m.key]?0:1);total+=+f.correct;feedbacks[m.key].textContent=f.text;feedbacks[m.key].className='qc-feedback '+(f.correct?'qc-correct':'qc-wrong');});status.textContent='预测核对：'+total+'/4 正确。读数、曲线和下载均对应当前参数。';}
    function draw(){var ps=plots(current);plotWrap.innerHTML=svg(ps[view]);Array.from(plotButtons.children).forEach((b,i)=>b.setAttribute('aria-pressed',String(i===view)));}
    function render(){current=snapshot(c);root.__qecSnapshot=current;stage.hidden=false;summary.textContent='当前输入保真度='+fmt(current.fidelity)+'；通道保迹残差='+fmt(current.tracePreservationDefect)+'。保真度1可能只保护这一输入态；请结合64种Pauli表和传递矩阵判断通用纠错。';plotButtons.replaceChildren();plots(current).forEach((p,i)=>{let b=el('button',{type:'button','data-plot':p.key},p.title);b.onclick=()=>{view=i;draw();};plotButtons.append(b);});draw();tableHost.replaceChildren();tables(current).forEach(t=>{let details=el('details',{'data-table':t.key}),heading=el('summary',{},t.title);details.append(heading);details.addEventListener('toggle',()=>{if(!details.open||details.children.length>1)return;let wrap=el('div',{class:'qc-scroll',tabindex:'0',role:'region','aria-label':t.title+'，可横向滚动'}),table=el('table'),head=el('thead'),tr=el('tr'),body=el('tbody');t.headers.forEach(h=>tr.append(el('th',{scope:'col'},h)));head.append(tr);t.rows.forEach(r=>{let row=el('tr');r.forEach(v=>row.append(el('td',{},fmt(v))));body.append(row);});table.append(head,body);wrap.append(table);details.append(wrap);});tableHost.append(details);});if(url)hostWindow.URL.revokeObjectURL(url);url=hostWindow.URL.createObjectURL(new hostWindow.Blob([JSON.stringify(current,null,2)],{type:'application/json'}));download.href=url;showFeedback();}
    function sync(){Object.entries(fields).forEach(([k,e])=>e.value=c[k]);}
    function reset(){c=config(c);revealed=false;choices={};stage.hidden=true;delete root.__qecSnapshot;METRICS.forEach(m=>{feedbacks[m.key].textContent='';predButtons[m.key].forEach(b=>b.setAttribute('aria-pressed','false'));});Object.entries(outs).forEach(([k,o])=>o.textContent=fmt(c[k]));rateNote.textContent='退极化约定：I概率1−p，X/Y/Z各p/3。每个噪声标签是经典Kraus分支；同一个相干算符内部的项按振幅相加。';status.textContent='参数已就绪。完成四项预测后显示结果。';}
    check.onclick=()=>{if(!METRICS.every(m=>typeof choices[m.key]==='boolean')){status.textContent='请先为四个量各选一个预测。';return;}revealed=true;render();};sync();reset();mounted.set(root,()=>{if(url)hostWindow.URL.revokeObjectURL(url);});
  }

function selfTest(){let checks=0;const assert=(b,m)=>{checks++;if(!b)throw Error(m);},near=(x,y,m)=>assert(Math.abs(x-y)<1e-10,m);for(const error of ['III','XII','IXI','IIX'])near(evaluate({model:'pauli',error}).fidelity,1,'correctable '+error);for(const error of ['IZI','IYI','XXX'])near(evaluate({model:'pauli',error}).fidelity,0,'uncorrectable for +i '+error);near(evaluate({model:'pauli',error:'XXX',theta:Math.PI/2,phi:0}).fidelity,1,'eigenstate exception');near(evaluate({model:'independent',p:.1}).fidelity,.972,'independent');near(evaluate({model:'correlated',p:.1}).fidelity,.9,'correlated');near(evaluate({model:'coherentSingle',angle:Math.PI/3}).fidelity,1,'single rotation');const r=evaluate({angle:Math.PI/3});near(r.reference.q,5/32,'coherent q');near(r.reference.kappa,3*Math.sqrt(3)/32,'coherent term');near(r.outputBloch[1],11/16,'Bloch Y');near(r.outputBloch[2],3*Math.sqrt(3)/16,'Bloch Z');near(r.fidelity,27/32,'pure fidelity');near(r.purity,101/128,'coherent purity');assert(evaluate({angle:0}).branches.filter(r=>r.conditional===null).length===3,'zero branches');assert(pauliRows().length===64,'complete Paulis');assert(pauliRows().find(r=>r.word==='ZZI').universallyCorrected,'degenerate repetition stabilizer');const sh=shorData();assert(sh.groupSize===256&&sh.dimension===2,'Shor dimension');assert(sh.knillLaflamme.length===784&&sh.maxKLDefect<1e-12,'Shor KL');assert(sh.distance===3&&sh.distanceEnumeration.length===2619,'Shor distance');assert(feedback(0,0).correct&&!feedback(0,1).correct,'feedback branches');return{checks,presets:PRESETS.length};}

return{MODELS,DEFAULT,config,evaluate,snapshot,pauliRows,shorData,PRESETS,QUESTIONS,feedback,fmt,plots,tables,svg,mount,selfTest};
});
