"""流体线 6 图 + 天体线 6 图 + qft-03 跑动耦合。
运行：cd figs && ~/ai-course/.venv/bin/python physics_fl_ap.py"""
import numpy as np
from _common import plt, save, ACC, ACC2, INK, RED, GREEN

rng = np.random.default_rng(4)

# ══════════ 流体线 ══════════

def _preserve_reviewed_svg(name):
    """The reviewed SVG is source artwork; rebuilding sites copies it directly."""
    from pathlib import Path
    import xml.etree.ElementTree as ET
    source = Path(__file__).resolve().parents[1] / "images" / (name + ".svg")
    ET.parse(source)  # Fail explicitly if the authoritative source is missing/invalid.
    print(f"Preserved reviewed source SVG: {source.name}")


def fl01_re():
    """Legacy entry point: the lecture now uses a nozzle momentum diagram."""
    _preserve_reviewed_svg("fl-01-continuum-re")


def fl02_drag():
    """Legacy entry point: sphere traction + collocation Blasius profile."""
    _preserve_reviewed_svg("fl-02-viscous-drag")


def fl03_spectrum():
    """Legacy entry point: preserve reviewed spectrum and viscous balance."""
    _preserve_reviewed_svg("fl-03-turbulence-spectrum")


def fl04_bifurcation():
    """Preserve reviewed free-slip neutral and signed branch diagram."""
    _preserve_reviewed_svg("fl-04-instability-bifurcation")


def fl05_lorenz():
    """Preserve reviewed numerical orbit, finite scan and exact period-2 branches."""
    _preserve_reviewed_svg("fl-05-chaos-lorenz")


def fl06_regimes():
    """Preserve reviewed SI electron density/temperature boundaries."""
    _preserve_reviewed_svg("fl-06-plasma-regimes")

# ══════════ 天体线 ══════════

def ap01_transfer():
    # Preserve reviewed grey limb and explicit slab line model.
    _preserve_reviewed_svg("ap-01-radiative-transfer")


def ap02_hr():
    # Preserve reviewed scaling and constant-radius HR lines.
    _preserve_reviewed_svg("ap-02-stellar-hr")


def ap03_gamow():
    # Mechanism figure is generated by tools/build_gamow_figure.py.
    pass


def ap04_massradius():
    # Mechanism figure is generated by tools/build_compact_fermi_figure.py.
    pass


def ap05_disk():
    """Preserve the physical Planck-integral figure; rebuild with tools/build_accretion_figure.py."""
    _preserve_reviewed_svg("ap-05-accretion-disk")


def ap06_rotation():
    r = np.linspace(0.3, 30, 400)
    v_disk = 200*np.sqrt(3.0/r)*(1-np.exp(-r/1.5))
    v_flat = 220*(1-np.exp(-r/1.8))
    v_halo = np.sqrt(np.maximum(v_flat**2 - v_disk**2, 0))
    fig, ax = plt.subplots(figsize=(6.9, 4.3))
    ax.plot(r, v_flat, color=ACC, lw=3.0, label="observed (flat)")
    ax.plot(r, v_disk, "--", color=RED, lw=2.2, label="visible matter only")
    ax.plot(r, v_halo, ":", color=GREEN, lw=2.2, label="required dark halo")
    robs = np.linspace(1.5, 28, 16)
    ax.errorbar(robs, np.interp(robs, r, v_flat), yerr=9, fmt="o",
                color=INK, ms=4.5, lw=1.1, capsize=2.5, zorder=5)
    ax.annotate("Keplerian decline\nexpected", xy=(20, 60), xytext=(12, 20),
                fontsize=9.5, color=RED, arrowprops=dict(arrowstyle="->", color=RED))
    ax.set_xlabel("radius  (kpc)"); ax.set_ylabel("rotation velocity  (km/s)")
    ax.set_title("Galaxy rotation curve", color=INK, fontsize=12.5)
    ax.legend(frameon=False, fontsize=9.5, loc="lower right")
    ax.set_ylim(0, 265)
    save(fig, "ap-06-rotation-curve")

# ══════════ qft-03 ══════════

def qft03_running():
    mu = np.logspace(-1, 16, 500)          # GeV
    # 单圈 QED：1/α 随 log(μ) 线性下降；标定为 1/α(m_e)=137 → 1/α(M_Z)=128
    slope = (137 - 128)/np.log10(91.2/5.11e-4)      # ≈1.71 per decade
    inv_qed = 137 - slope*np.log10(mu/5.11e-4)
    alpha_qed = 1/np.maximum(inv_qed, 60)
    Lam = 0.2
    alpha_s = np.where(mu > Lam*1.3, 12*np.pi/(23*np.log(np.maximum(mu/Lam, 1.31)**2)), np.nan)
    fig, (a1, a2) = plt.subplots(1, 2, figsize=(9.8, 4.1))
    a1.semilogx(mu, 1/alpha_qed, color=ACC, lw=2.8)
    a1.set_xlabel(r"energy scale  $\mu$  (GeV)")
    a1.set_ylabel(r"$1/\alpha_{\rm em}$")
    a1.set_title(r"QED: $\beta>0$ (screening)", color=INK, fontsize=11.5)
    a1.plot([91.2], [128], "o", color=RED, ms=8, zorder=5)
    a1.text(3e2, 129, r"$M_Z$: $\alpha^{-1}\approx128$", fontsize=9.5, color=RED)
    a1.text(1e-1, 136, r"$\alpha^{-1}=137$ at low $E$", fontsize=9.5, color="#666")
    a1.invert_yaxis()
    a2.loglog(mu, alpha_s, color=ACC, lw=2.8)
    a2.axvline(0.2, color=RED, ls="--", lw=1.5)
    a2.text(0.24, 0.9, r"$\Lambda_{\rm QCD}$", fontsize=10.5, color=RED)
    a2.text(3e3, 0.30, "asymptotic\nfreedom", fontsize=10, color=GREEN)
    a2.set_xlabel(r"energy scale  $\mu$  (GeV)")
    a2.set_ylabel(r"$\alpha_s$")
    a2.set_title(r"QCD: $\beta<0$ (anti-screening)", color=INK, fontsize=11.5)
    a2.set_xlim(0.15, 1e6); a2.set_ylim(0.05, 2)
    fig.tight_layout()
    save(fig, "qft-03-running")


if __name__ == "__main__":
    fl01_re(); fl02_drag(); fl03_spectrum(); fl04_bifurcation()
    fl05_lorenz(); fl06_regimes()
    ap01_transfer(); ap02_hr(); ap03_gamow(); ap04_massradius()
    ap05_disk(); ap06_rotation()
    qft03_running()
