"""Render only frozen experiment records; never sample while publishing."""
from pathlib import Path
import sys,json,subprocess,hashlib,shutil,html
PREFIX=['rtk','proxy']if shutil.which('rtk')else[]
js,out,fixture,fallback=map(Path,sys.argv[1:5]);f=json.loads(fixture.read_text());assert f['schema']==1 and f['provenance']['jsSha256']==hashlib.sha256(js.read_bytes()).hexdigest()
code="""const fs=require('fs'),a=require(require('path').resolve(process.argv[1])),f=JSON.parse(fs.readFileSync(process.argv[2]));const panels=[['coarse',3],['brownian',2],['single',5],['sign',1]].map(([key,i])=>({key,svg:a.svg(a.plots(f[key])[i])}));const c=f.coarse.selectedEnsemble,b=f.brownian.selectedPath,e=f.brownian.selectedEnsemble,s=f.single.selectedEnsemble,g=f.sign.selectedPath;const refs=[['粗网格L',0],['粗网格平均左和平方',c.statistics.leftSquare.mean],['粗网格平均能量',c.statistics.energy.mean],['粗网格离散目标',c.theory.expectedEnergy],['连续目标',c.theory.continuousTarget],['布朗场景读取层L',4],['当前路径左端和',b.totals.left],['当前路径右端和',b.totals.right],['当前路径梯形和',b.totals.trapezoid],['当前路径Q',b.totals.quadraticVariation],['当前路径能量',b.totals.energy],['成对差样本均值',e.statistics.paired.mean],['成对差估计标准误',e.statistics.paired.estimatedStandardError],['当前离散共同目标',e.theory.expectedEnergy],['单路径场景N',1],['单路径估计标准误',s.statistics.paired.estimatedStandardError],['符号过程路径能量',g.totals.energy],['符号过程离散目标',f.sign.selectedEnsemble.theory.expectedEnergy],['符号过程左端和',g.totals.left],['布朗左和恒等式残差',b.brownianIdentity.leftResidual]];console.log(JSON.stringify({panels,refs:refs.map(([k,v])=>[k,v===null?'不适用':String(v)]),short:[e.theory.expectedEnergy,e.statistics.paired.mean].map(a.fmt)}));"""
d=json.loads(subprocess.check_output(PREFIX+['node','-e',code,str(js),str(fixture)],text=True))
svg='<svg xmlns="http://www.w3.org/2000/svg" width="1000" height="2300" viewBox="0 0 1000 2300" role="img"><title>Itô积分：取点、等距与两类误差</title><desc>四个固定场景：一步网格、布朗三种和、单路径标准误边界与符号简单过程。完整记录可下载复算。</desc><rect width="1000" height="2300" fill="#fff"/>'
titles=['一、只用一段：增加N不能消除时间网格偏差','二、同一条布朗路径：左端、右端与梯形和','三、N=1：不把未知的样本标准误显示为0','四、符号简单过程：每段按已知符号翻转噪声']
captions=['当前L=0时，左端和与能量都为0；连续二阶矩目标仍为1/2。','当前L=4的离散共同期望='+d['short'][0]+'；实际逐路径值见完整表。','只有一条样本，无法估计样本方差；理论均值0仍可单独列出。','H=sign₊(B)取±1，所以每条有限路径的能量恰为T；左和仍随机。']
for i,p in enumerate(d['panels']):
 y=[85,640,1195,1750][i];svg+='<text x="50" y="'+str(y-24)+'" font-family="system-ui,sans-serif" font-size="19" fill="#283b46">'+html.escape(titles[i])+'</text>'+p['svg'].replace('<svg ','<svg x="50" y="'+str(y)+'" ',1)+'<text x="50" y="'+str(y+490)+'" font-family="system-ui,sans-serif" font-size="14" fill="#283b46">'+html.escape(captions[i])+'</text>'
out.write_text(svg+'</svg>\n')
rows='\n'.join('<tr><td>'+html.escape(k)+'</td><td>'+html.escape(v)+'</td></tr>'for k,v in d['refs'])
fallback.write_text('<figure class="plot" markdown="1">\n[![Itô积分的四个固定实验场景](assets/img/sc-02-ito-ledgers.svg)](assets/img/sc-02-ito-ledgers.svg)\n<figcaption>图1.1：打开原图可比较取点、有限期望和样本标准误的适用边界。</figcaption>\n</figure>\n\n<div class="fallback-scroll" role="region" tabindex="0" aria-label="Itô积分固定数值记录">\n<table><thead><tr><th scope="col">项目</th><th scope="col">固定记录值</th></tr></thead><tbody>\n'+rows+'\n</tbody></table>\n</div>\n\n[下载四个场景的全部路径与账本(JSON)](assets/learning/projects/ito-integral-ledger/run-snapshot.json)。各场景T=1、M=4、根种子20260722；除单路径场景外N=16。图上刻度为阅读做舍入，表内保留固定记录的数值。\n')
print(json.dumps({'svgBytes':out.stat().st_size,'values':len(d['refs'])}))
