"""Rebuild scientific panels and fallback values from frozen records only."""
from pathlib import Path
import json,sys,hashlib,subprocess,shutil,html
PREFIX=['rtk','proxy']if shutil.which('rtk')else[]
js,out,fixture,fallback=map(Path,sys.argv[1:5]);f=json.loads(fixture.read_text());assert f['schema']==1 and f['provenance']['jsSha256']==hashlib.sha256(js.read_bytes()).hexdigest()
code="""const fs=require('fs'),a=require(require('path').resolve(process.argv[1])),f=JSON.parse(fs.readFileSync(process.argv[2]));const panels=[['default',0],['threshold',5],['deep',2],['black',3]].map(([key,i])=>({key,svg:a.svg(a.plots(f[key])[i])}));const d=f.default,t=f.threshold,h=f.deep,b=f.black;const refs=[['弱井：弹性截面',d.totals.elastic],['弱井：反应截面',d.totals.reaction],['弱井：总截面',d.totals.total],['弱井：光学定理',d.totals.optical],['弱井：散射长度',d.scatteringLength.value],['阈值附近：s波上限占比',t.partials[0].sin**2],['阈值附近：弹性截面',t.totals.elastic],['阈值附近：光学定理',t.totals.optical],['阈值附近：k',+t.parameters.k],['阈值附近：V₀',+t.parameters.depth],['深井：L=6弹性截面',h.totals.elastic],['深井：只取s波截面',h.totals.rows[0].elastic],['深井：前向Im f',h.totals.forward.imag],['深井：Born总截面',h.integratedBorn],['深井：散射长度',h.scatteringLength.value],['完全损失：η',+b.parameters.eta],['完全损失：L',+b.parameters.lmax],['完全损失：弹性截面',b.totals.elastic],['完全损失：反应截面',b.totals.reaction],['完全损失：总截面',b.totals.total]];console.log(JSON.stringify({panels,refs:refs.map(([k,v])=>[k,String(v)])}));"""
d=json.loads(subprocess.check_output(PREFIX+['node','-e',code,str(js),str(fixture)],text=True))
svg='<svg xmlns="http://www.w3.org/2000/svg" width="1000" height="2300" viewBox="0 0 1000 2300" role="img"><title>散射：边界匹配、窄共振、Born与通道损失</title><desc>四个固定场景使用完整冻结记录，保留实际分波、角积分和采样点。</desc><rect width="1000" height="2300" fill="#fff"/>'
titles=['一、弱井：函数与边界先匹配','二、低能窄峰：在计算得到的共振位置加密','三、深井：一阶Born可能偏离实际分波结果','四、完全损失：弹性与反应截面同样非零']
captions=['V₀=0.25，k=0.35，L=3，η=1；径向图始终是实方井s波。','V₀≈π²/4，k=0.02，L=3，η=1；本图扫描井深，包含实际峰点。','V₀=25，k=2.5，L=6，η=1；有限L并未给出无限分波尾项的严格界。','V₀=2，k=1.1，L=3，η=0；这是有限通道现象学模型。']
for i,p in enumerate(d['panels']):
 y=85+555*i;svg+='<text x="50" y="'+str(y-24)+'" font-family="system-ui,sans-serif" font-size="19" fill="#283b46">'+html.escape(titles[i])+'</text>'+p['svg'].replace('<svg ','<svg x="50" y="'+str(y)+'" ',1)+'<text x="50" y="'+str(y+490)+'" font-family="system-ui,sans-serif" font-size="14" fill="#283b46">'+html.escape(captions[i])+'</text>'
out.write_text(svg+'</svg>\n');rows='\n'.join('<tr><td>'+html.escape(k)+'</td><td>'+html.escape(v)+'</td></tr>'for k,v in d['refs'])
fallback.write_text('<figure class="plot" markdown="1">\n[![散射的四个固定场景](assets/img/aqm-02-scattering-ledgers.svg)](assets/img/aqm-02-scattering-ledgers.svg)\n<figcaption>图2.1：打开原图，比较边界匹配、窄共振和两种截面。</figcaption>\n</figure>\n\n<div class="fallback-scroll" role="region" tabindex="0" aria-label="散射固定数值记录">\n<table><thead><tr><th scope="col">项目</th><th scope="col">固定记录值</th></tr></thead><tbody>\n'+rows+'\n</tbody></table>\n</div>\n\n[下载四个场景的完整分波、匹配与求积记录(JSON)](assets/learning/projects/swave-scattering/run-snapshot.json)。固定R=1、2μ/ℏ²=1。弱井V₀=0.25、k=0.35、L=3、η=1；阈值附近V₀=2.4674011002723395、k=0.02、L=3、η=1；深井V₀=25、k=2.5、L=6、η=1；完全损失V₀=2、k=1.1、L=3、η=0。所选角度均60度。图上显示舍入，表内保留冻结值。\n')
print(json.dumps({'svgBytes':out.stat().st_size,'values':len(d['refs'])}))
