"""Rebuild static evidence from four fixed complete records."""
from pathlib import Path
import json,sys,hashlib,subprocess,shutil,html
PREFIX=['rtk','proxy']if shutil.which('rtk')else[]
js,out,fixture,fallback=map(Path,sys.argv[1:5]);f=json.loads(fixture.read_text());assert f['schema']==1 and f['provenance']['jsSha256']==hashlib.sha256(js.read_bytes()).hexdigest()
code="""const fs=require('fs'),a=require(require('path').resolve(process.argv[1])),f=JSON.parse(fs.readFileSync(process.argv[2]));const panels=[['return',5],['pulse',8],['front',0],['static',1]].map(([key,i])=>({key,svg:a.svg(a.plots(f[key])[i])}));const r=f.return,p=f.pulse,n=f.front,s=f.static;const refs=[['回流：推迟源时刻',r.point.retardedTime],['回流：完整Eθ',r.point.components.et],['回流：完整Bφ',r.point.components.b],['回流：完整球面瞬时功率',r.power.numerical],['回流：辐射项功率',r.power.radiation],['回流：周期平均功率',r.meanReference],['脉冲：当前推迟时刻',p.point.retardedTime],['脉冲：当前偶极矩',p.point.source.p],['脉冲：当前二阶导',p.point.source.second],['脉冲：闭式完整能量',p.pulseEnergy.closed],['脉冲：Simpson完整能量',p.pulseEnergy.numerical],['脉冲：积分差',p.pulseEnergy.error],['前沿：到达时刻',n.events[2].arrival],['前沿：当前推迟时刻',n.point.retardedTime],['前沿：完整Eθ',n.point.components.et],['前沿：完整球面功率',n.power.numerical],['静态：完整Er',s.point.components.er],['静态：完整Eθ',s.point.components.et],['静态：完整Bφ',s.point.components.b],['静态：球面功率',s.power.numerical]];console.log(JSON.stringify({panels,refs:refs.map(([k,v])=>[k,String(v)])}));"""
d=json.loads(subprocess.check_output(PREFIX+['node','-e',code,str(js),str(fixture)],text=True))
svg='<svg xmlns="http://www.w3.org/2000/svg" width="1000" height="2300" viewBox="0 0 1000 2300" role="img"><title>推迟辐射：近场回流、有限脉冲与静态极限</title><desc>四组固定记录分别显示瞬时功率、累计辐射能量、传播延迟与静电场。</desc><rect width="1000" height="2300" fill="#fff"/>'
titles=['一、近场回流：完整功率可以暂时为负','二、完整脉冲：累计辐射能量与精确积分','三、因果前沿：先有源变化，再有观察响应','四、静态极限：电场仍存在，磁场与能流为零']
captions=['r=0.2、t=0.2：完整球面功率−16，辐射项2/3，完整周期平均1/3。','D=2、A=c=1：完整脉冲能量131072/5005；图中积分对象仅为辐射项。','r=4、c=1：到达前沿t=4，端点场仍为0；橙色源脉冲比蓝色响应早4。','ω=0、r=1、θ=60°：Er=1、Eθ=√3/2；没有有限周期，也没有辐射。']
for i,p in enumerate(d['panels']):
 y=[85,640,1195,1750][i];svg+='<text x="50" y="'+str(y-24)+'" font-family="system-ui,sans-serif" font-size="19" fill="#283b46">'+html.escape(titles[i])+'</text>'+p['svg'].replace('<svg ','<svg x="50" y="'+str(y)+'" ',1)+'<text x="50" y="'+str(y+490)+'" font-family="system-ui,sans-serif" font-size="14" fill="#283b46">'+html.escape(captions[i])+'</text>'
out.write_text(svg+'</svg>\n');rows='\n'.join('<tr><td>'+html.escape(k)+'</td><td>'+html.escape(v)+'</td></tr>'for k,v in d['refs'])
fallback.write_text('<figure class="plot" markdown="1">\n[![推迟辐射的四个固定场景](assets/img/ced-02-radiation-ledgers.svg)](assets/img/ced-02-radiation-ledgers.svg)\n<figcaption>图2.1：打开原图，分别读瞬时功率、累计能量、时间延迟和静电场。</figcaption>\n</figure>\n\n<div class="fallback-scroll" role="region" tabindex="0" aria-label="推迟辐射固定数值记录">\n<table><thead><tr><th scope="col">项目</th><th scope="col">固定记录值</th></tr></thead><tbody>\n'+rows+'\n</tbody></table>\n</div>\n\n[下载四个场景的完整数值与账本(JSON)](assets/learning/projects/retarded-radiation/run-snapshot.json)。均k=c=A=1、t₀=0；回流为谐波ω=1、r=t=0.2、θ=90°；脉冲中点D=2、r=1、t=2、θ=60°；前沿D=2、r=t=4、θ=60°；静态ω=0、r=1、t=5、θ=60°。图上刻度做显示舍入，表内保留固定数值。\n')
print(json.dumps({'svgBytes':out.stat().st_size,'values':len(d['refs'])}))
