"""Rebuild static evidence from fixed records; never draw new randomness."""
from pathlib import Path
import json,sys,hashlib,subprocess,shutil,html
PREFIX=['rtk','proxy']if shutil.which('rtk')else[]
js,out,fixture,fallback=map(Path,sys.argv[1:5]);f=json.loads(fixture.read_text());assert f['schema']==1 and f['provenance']['jsSha256']==hashlib.sha256(js.read_bytes()).hexdigest()
code="""const fs=require('fs'),a=require(require('path').resolve(process.argv[1])),f=JSON.parse(fs.readFileSync(process.argv[2]));const panels=[['square',2],['quartic',3],['negative',4],['zero',0]].map(([key,i])=>({key,svg:a.svg(a.plots(f[key])[i])}));const s=f.square.selected.chain,q=f.quartic.selected.chain,g=f.negative.selected.gbm,z=f.zero.selected;const refs=[['平方场景读取层L',4],['平方场景Q',s.totals.q],['平方一次项',s.totals.first],['平方二次项',s.totals.second],['平方余项',s.totals.remainder],['平方恒等式残差',s.identityResidual],['平方dt修正后残差',s.timeResidual],['四次方一次项',q.totals.first],['四次方二次项',q.totals.second],['四次方余项',q.totals.remainder],['四次方加权平方增量误差',q.weightedNoise],['四次方dt修正后残差',q.timeResidual],['粗Euler精确终点',g.exactTerminal],['粗Euler终点',g.eulerTerminal],['首个非正Euler节点',g.firstNonPositive],['粗Euler解析均值',g.reference.eulerMean],['零时域Q',z.chain.totals.q],['零时域精确终点',z.gbm.exactTerminal],['零时域Euler终点',z.gbm.eulerTerminal],['零时域首个非正节点',z.gbm.firstNonPositive]];console.log(JSON.stringify({panels,refs:refs.map(([k,v])=>[k,v===null?'未出现':String(v)])}));"""
d=json.loads(subprocess.check_output(PREFIX+['node','-e',code,str(js),str(fixture)],text=True))
svg='<svg xmlns="http://www.w3.org/2000/svg" width="1000" height="2300" viewBox="0 0 1000 2300" role="img"><title>Itô公式：有限Taylor、二阶修正与Euler对照</title><desc>四个固定场景展示精确代数、概率极限与数值近似的不同角色。完整数据可下载。</desc><rect width="1000" height="2300" fill="#fff"/>'
titles=['一、平方函数：实际二次项使每层账本成立','二、四次方：dt修正还留下哪两种误差','三、粗Euler：精确正性不会自动传给算法','四、T=0：所有布朗观测都在同一点']
captions=['有限恒等式保留实际Q；用T替代Q后会有Q−T误差。','dt残差拆成加权平方增量误差与高阶余项，二者都要控制。','μ=−2、σ=2、L=0；非正Euler数值保留，不取绝对值。','T=0时布朗节点为0，GBM精确与Euler节点均为初值1。']
for i,p in enumerate(d['panels']):
 y=[85,640,1195,1750][i];svg+='<text x="50" y="'+str(y-24)+'" font-family="system-ui,sans-serif" font-size="19" fill="#283b46">'+html.escape(titles[i])+'</text>'+p['svg'].replace('<svg ','<svg x="50" y="'+str(y)+'" ',1)+'<text x="50" y="'+str(y+490)+'" font-family="system-ui,sans-serif" font-size="14" fill="#283b46">'+html.escape(captions[i])+'</text>'
out.write_text(svg+'</svg>\n');rows='\n'.join('<tr><td>'+html.escape(k)+'</td><td>'+html.escape(v)+'</td></tr>'for k,v in d['refs'])
fallback.write_text('<figure class="plot" markdown="1">\n[![Itô公式与Euler近似的四个固定场景](assets/img/sc-03-ito-sde-ledgers.svg)](assets/img/sc-03-ito-sde-ledgers.svg)\n<figcaption>图1.1：打开原图，依次比较有限恒等式、dt误差和Euler正性。</figcaption>\n</figure>\n\n<div class="fallback-scroll" role="region" tabindex="0" aria-label="Itô公式固定数值记录">\n<table><thead><tr><th scope="col">项目</th><th scope="col">固定记录值</th></tr></thead><tbody>\n'+rows+'\n</tbody></table>\n</div>\n\n[下载四个场景的完整路径与账本(JSON)](assets/learning/projects/ito-quadratic-variation/run-snapshot.json)。均用M=4、seed=20260722；平方/四次场景T=1、L=4、μ=0.3、σ=0.8；粗Euler场景T=1、L=0、μ=−2、σ=2；零时域场景T=0、L=4。表内保留固定数值，图上刻度做显示舍入。\n')
print(json.dumps({'svgBytes':out.stat().st_size,'values':len(d['refs'])}))
