"""Rebuild four scientific panels from fixed complete records."""
from pathlib import Path
import json,sys,hashlib,subprocess,shutil,html
PREFIX=['rtk','proxy']if shutil.which('rtk')else[]
js,out,fixture,fallback=map(Path,sys.argv[1:5]);f=json.loads(fixture.read_text());assert f['schema']==1 and f['provenance']['jsSha256']==hashlib.sha256(js.read_bytes()).hexdigest()
code="""const fs=require('fs'),a=require(require('path').resolve(process.argv[1])),f=JSON.parse(fs.readFileSync(process.argv[2]));const panels=[['default',0],['kramers',3],['integer',2],['tiny',2]].map(([key,i])=>({key,svg:a.svg(a.plots(f[key])[i])}));const s=f.default,k=f.kramers,n=f.integer,t=f.tiny;const refs=[['双自旋半：空间维数',s.product.dimension],['单态能量',s.dynamics.spectrum.values[0]],['三重态能量',s.dynamics.spectrum.values[1]],['单态↑↓系数',s.cg.matrix[1][3]],['单态↓↑系数',s.cg.matrix[2][3]],['Kramers：T²符号',k.dynamics.squareSign],['Kramers：最低能量',k.dynamics.spectrum.values[0]],['Kramers：第二能量',k.dynamics.spectrum.values[1]],['Kramers：第三能量',k.dynamics.spectrum.values[2]],['Kramers：第四能量',k.dynamics.spectrum.values[3]],['Kramers：第五能量',k.dynamics.spectrum.values[4]],['Kramers：第六能量',k.dynamics.spectrum.values[5]],['整数自旋：T²符号',n.dynamics.squareSign],['整数自旋：第一能量',n.dynamics.spectrum.values[0]],['整数自旋：第二能量',n.dynamics.spectrum.values[1]],['整数自旋：第三能量',n.dynamics.spectrum.values[2]],['微小磁场：低能',t.dynamics.spectrum.values[0]],['微小磁场：高能',t.dynamics.spectrum.values[1]],['微小磁场：数值分组容差',t.dynamics.groupingTolerance],['微小磁场：数值组数',t.dynamics.groups.length]];console.log(JSON.stringify({panels,refs:refs.map(([k,v])=>[k,String(v)])}));"""
d=json.loads(subprocess.check_output(PREFIX+['node','-e',code,str(js),str(fixture)],text=True))
svg='<svg xmlns="http://www.w3.org/2000/svg" width="1000" height="2600" viewBox="0 0 1000 2600" role="img"><title>量子对称性：CG换基、Kramers与微小劈裂</title><desc>四组冻结记录展示有符号CG系数、外场能级、整数自旋反例与容差内的真实劈裂。</desc><rect width="1000" height="2600" fill="#fff"/>'
titles=['一、两个自旋半：四个态如何分成三重态与单态','二、Kramers保护：无磁场时成对，外场可以劈裂','三、整数自旋反例：T对称并不单独保证简并','四、微小劈裂：一组数值聚类不等于严格简并']
captions=['j₁=j₂=1/2，λ=1，其余项0；单态能量−3/4，三重态能量1/4。','j₁=1、j₂=1/2，λ=0.7、Dz=1、Dx=0.4、hx=0；图中扫描hz。','j₁=1、j₂=0，Dz=1、Dx=0.4、hz=hx=0；三个能量0.4、1、1.4。','j₁=1/2、j₂=0，hz=10⁻¹¹；两能量±5×10⁻¹²，分组容差10⁻⁹。']
for i,p in enumerate(d['panels']):
 y=[85,940,1495,2050][i];height=760 if i==0 else 460;svg+='<text x="50" y="'+str(y-24)+'" font-family="system-ui,sans-serif" font-size="19" fill="#283b46">'+html.escape(titles[i])+'</text>'+p['svg'].replace('<svg ','<svg x="50" y="'+str(y)+'" ',1)+'<text x="50" y="'+str(y+height+30)+'" font-family="system-ui,sans-serif" font-size="14" fill="#283b46">'+html.escape(captions[i])+'</text>'
out.write_text(svg+'</svg>\n');rows='\n'.join('<tr><td>'+html.escape(k)+'</td><td>'+html.escape(v)+'</td></tr>'for k,v in d['refs'])
fallback.write_text('<figure class="plot" markdown="1">\n[![量子对称性的四个固定场景](assets/img/aqm-01-symmetry-ledgers.svg)](assets/img/aqm-01-symmetry-ledgers.svg)\n<figcaption>图1.1：打开原图，比较CG符号、Kramers条件与数值容差。</figcaption>\n</figure>\n\n<div class="fallback-scroll" role="region" tabindex="0" aria-label="量子对称性固定数值记录">\n<table><thead><tr><th scope="col">项目</th><th scope="col">固定记录值</th></tr></thead><tbody>\n'+rows+'\n</tbody></table>\n</div>\n\n[下载四个场景的完整矩阵、CG与求解记录(JSON)](assets/learning/projects/quantum-symmetry/run-snapshot.json)。取ℏ=1。默认双自旋半仅λ=1；Kramers场景j₁=1、j₂=1/2、λ=0.7、Dz=1、Dx=0.4；整数场景j₁=1、j₂=0、λ=1、Dz=1、Dx=0.4；微场场景j₁=1/2、j₂=0、λ=1、hz=10⁻¹¹。未写出的系数均0。图上做显示舍入，表内保留冻结值。\n')
print(json.dumps({'svgBytes':out.stat().st_size,'values':len(d['refs'])}))
