"""Rebuild static evidence from fixed records; never draw new randomness."""
from pathlib import Path
import json,sys,hashlib,subprocess,shutil,html
PREFIX=['rtk','proxy']if shutil.which('rtk')else[]
js,out,fixture,fallback=map(Path,sys.argv[1:5]);f=json.loads(fixture.read_text());assert f['schema']==1 and f['provenance']['jsSha256']==hashlib.sha256(js.read_bytes()).hexdigest()
code="const fs=require('fs'),a=require(require('path').resolve(process.argv[1])),f=JSON.parse(fs.readFileSync(process.argv[2]));const panels=[['plane',3],['grounded',2],['isolated',4],['zero',0]].map(([key,i])=>({key,svg:a.svg(a.plots(f[key])[i])}));const s=f.plane,g=f.grounded,n=f.isolated,z=f.zero;const refs=[['平面边界势',s.model.surfacePotential],['平面完整电荷',s.model.surfaceCharge],['平面有限积分',s.quadratureStatus.total],['平面未覆盖电荷',s.quadratureStatus.remainingCharge],['平面受力',s.force.force],['平面相互作用能',s.force.energy],['接地球离心像',g.model.qp],['接地球像位置',g.model.b],['接地球电位',g.model.surfacePotential],['接地球总电荷',g.model.surfaceCharge],['接地球受力',g.force.force],['接地球相互作用能',g.force.energy],['孤立中性球中心像',n.model.q0],['孤立中性球电位',n.model.surfacePotential],['孤立中性球总电荷',n.model.surfaceCharge],['孤立中性球受力',n.force.force],['孤立中性球相互作用能',n.force.energy],['零电荷边界场',z.boundary[0].normalField],['零电荷受力',z.force.force],['零电荷多极尾界',z.probe.orders[4].tailBound]];console.log(JSON.stringify({panels,refs:refs.map(([k,v])=>[k,String(v)])}));"
d=json.loads(subprocess.check_output(PREFIX+['node','-e',code,str(js),str(fixture)],text=True))
svg='<svg xmlns="http://www.w3.org/2000/svg" width="1000" height="2300" viewBox="0 0 1000 2300" role="img"><title>导体边值：有限区域、表面电荷与力能量</title><desc>四个固定场景展示平面、接地球、孤立中性球与零电荷。完整数据可下载。</desc><rect width="1000" height="2300" fill="#fff"/>'
titles=['一、平面：有限圆盘不等于无限平面','二、接地球：面电荷从法向场得到','三、孤立中性球：固定Q核对力与能量','四、零电荷：只有位置标记，没有场箭头']
captions=['积分到8d仍缺少约12.4%的感应电荷；加密求积不能消除区域截断。','q=1、a=1、d=2，球总感应电荷为−1/2，边界电位为0。','Q=0，球面电位为1/2；差分时保持Q固定，与直接像场的力比较。','零电荷时电位、场、受力与多极尾界都为0；位置标记不代表非零电荷。']
for i,p in enumerate(d['panels']):
 y=[85,640,1195,1750][i];svg+='<text x="50" y="'+str(y-24)+'" font-family="system-ui,sans-serif" font-size="19" fill="#283b46">'+html.escape(titles[i])+'</text>'+p['svg'].replace('<svg ','<svg x="50" y="'+str(y)+'" ',1)+'<text x="50" y="'+str(y+490)+'" font-family="system-ui,sans-serif" font-size="14" fill="#283b46">'+html.escape(captions[i])+'</text>'
out.write_text(svg+'</svg>\n');rows='\n'.join('<tr><td>'+html.escape(k)+'</td><td>'+html.escape(v)+'</td></tr>'for k,v in d['refs'])
fallback.write_text('<figure class="plot" markdown="1">\n[![导体边值与多极的四个固定场景](assets/img/ced-01-boundary-ledgers.svg)](assets/img/ced-01-boundary-ledgers.svg)\n<figcaption>图1.1：打开原图，比较积分区域、导体条件和零电荷。</figcaption>\n</figure>\n\n<div class="fallback-scroll" role="region" tabindex="0" aria-label="边值问题固定数值记录">\n<table><thead><tr><th scope="col">项目</th><th scope="col">固定记录值</th></tr></thead><tbody>\n'+rows+'\n</tbody></table>\n</div>\n\n[下载四个场景的完整数值与账本(JSON)](assets/learning/projects/image-charge-boundary/run-snapshot.json)。四场景均a=1、间隙=1、Q=0、r/d=2、L=4、探针45°；平面/接地球/孤立球q=1，零电荷平面q=0。平面d=1，球模型d=2。表内保留固定数值，图上刻度做显示舍入。\n')
print(json.dumps({'svgBytes':out.stat().st_size,'values':len(d['refs'])}))
