"use strict";
const assert=require("assert"),lab=require("../course-shared/labs/determinant-volume.js"),reference=require("./fixtures/determinant-svd-reference.json");
let checks=0;
function check(ok,message){checks++;assert(ok,message);}
function close(a,b,message,tolerance=3e-11){check(Math.abs(a-b)<=tolerance*Math.max(Math.abs(a),Math.abs(b),1e-320),`${message}: ${a} vs ${b}`);}
// Independent six-permutation determinant and direct matrix application.
function det(a){let sum=0;for(const[p,sign]of [[[0,1,2],1],[[1,2,0],1],[[2,0,1],1],[[0,2,1],-1],[[2,1,0],-1],[[1,0,2],-1]])sum+=sign*a[0][p[0]]*a[1][p[1]]*a[2][p[2]];return sum;}
function apply(a,x){return a.map(row=>row.reduce((v,c,i)=>v+c*x[i],0));}
for(const fixture of reference.family){const result=lab.evaluate(fixture.params);result.singularValues.forEach((v,i)=>close(v,fixture.values[i],"independent SVD",2e-10));close(result.conditionA,fixture.values[0]/fixture.values[2],"independent condition",3e-10);}
for(const fixture of reference.generic){lab.singularValues3(fixture.matrix).forEach((v,i)=>close(v,fixture.values[i],"generic LAPACK SVD",1e-9));}
for(let si=0;si<=28;si++)for(let ki=-4;ki<=4;ki++)for(let hi=-4;hi<=4;hi++)for(const swapped of [false,true]){
 const p={scale:si/20,anisotropy:ki/5,shear:hi/5,basisScale:si%2?.5:1.5,swapped},r=lab.evaluate(p);
 close(r.detA,det(r.A),"oriented determinant");close(r.detAB,det(r.AB),"composition determinant");
 check(r.rankA===(si?3:hi?2:0),"exact structural rank");
 check(r.volumeLabel===(si?(swapped?"反转方向":"保持方向"):"体积塌缩"),"orientation independent of threshold");
 if(si){check(r.conditionA>=1-1e-12&&Number.isFinite(r.conditionA),"positive scale finite condition");close(r.singularValues.reduce((a,b)=>a*b,1),Math.abs(r.detA),"product singular values");check(r.uniformCondition===1,"same volume uniform baseline");if(hi===0)close(r.conditionA,Math.exp(2*Math.abs(p.anisotropy)),"diagonal analytic condition");}
 else{check(r.conditionA===Infinity&&r.uniformCondition===Infinity,"singular convention");const kernel=swapped?[0,1,0]:[1,0,0];check(apply(r.A,kernel).every(x=>x===0),"explicit kernel certificate");}
 for(const v of [[1,0,0],[0,1,0],[0,0,1],[1,-2,3]]){const a=apply(r.AB,v),b=apply(r.A,apply(r.B,v));a.forEach((x,i)=>check(Math.abs(x-b[i])<1e-13,"composition acts on vectors"));}
}
for(const scale of [1e-12,1e-100,1e-200,Number.MIN_VALUE])for(const k of [-.8,0,.8])for(const swapped of [false,true]){
 const r=lab.evaluate({...lab.DEFAULTS,scale,anisotropy:k,swapped});check(r.rankA===3,"tiny positive scale full rank");close(r.conditionA,Math.exp(2*Math.abs(k)),"uniform tiny scale condition independent of units");check(r.uniformCondition===1,"uniform reference avoids determinant underflow");check(r.volumeLabel!="体积塌缩","underflow not zero structure");check(lab.format(scale)!=="0","nonzero display");
}
for(const swapped of [false,true]){const r=lab.evaluate({...lab.DEFAULTS,scale:1e-200,shear:.8,swapped});check(r.rankA===3&&!r.conditionResolved&&r.conditionA===null,"unrepresentable condition distinct from singularity");check(!r.determinantResolved,"determinant underflow marked");}
close(lab.evaluate(lab.PRESETS[0]).detA,lab.evaluate(lab.PRESETS[1]).detA,"same-volume presets actually same");
for(const fixture of lab.PRESETS)check(Math.abs(fixture.scale/.05-Math.round(fixture.scale/.05))<1e-12,"preset on slider lattice");
for(const key of ["scale","anisotropy","shear","basisScale"])for(const value of [NaN,Infinity,-Infinity,"1",null,undefined]){checks++;assert.throws(()=>lab.evaluate({...lab.DEFAULTS,[key]:value}),RangeError);}
for(const[key,value]of [["scale",-1],["scale",1.41],["anisotropy",-.81],["shear",.81],["basisScale",.49],["basisScale",1.51]]){checks++;assert.throws(()=>lab.evaluate({...lab.DEFAULTS,[key]:value}),RangeError);}
for(const bad of [[],[[1]],Array(3),[[1,0,0],[0,1,0],[0,0,null]],[[1,0,0],[0,1,0],[0,0,Infinity]]])for(const name of ["determinant3","singularValues3","symmetricEigenvalues3"]){checks++;assert.throws(()=>lab[name](bad));}
check(lab.format(12000,0)==="12000","integer trailing zeros");
// Homogeneous/inhomogeneous exercise certificates, not generated by the lab.
const a=[[0,.6,-.3],[0,0,.3],[0,0,0]];for(const t of [-10,0,1,7])check(JSON.stringify(apply(a,[t,1,1]))===JSON.stringify([.3,.3,0]),"affine solution family");
for(const x of [[1,0,0],[0,1,0],[0,0,1]])check(apply(a,x)[2]===0,"nonzero third RHS impossible");
const svg = require("fs").readFileSync(require("path").join(__dirname,"../math-course/images/algebra-02-volume-condition.svg"),"utf8");
const boxes = [...svg.matchAll(/<rect x="([\d.]+)" y="([\d.]+)" width="([\d.]+)" height="([\d.]+)" fill="#dbeafe"/g)];
check(boxes.length===2,"two static matrix images");
boxes.forEach((m,i)=>{const width=Number(m[3]),height=Number(m[4]);close(width*height/180**2,.25,"static same area");close(width/height,i?4:1,"static anisotropy");close(Number(m[1]),75+i*400,"static x origin");close(Number(m[2])+height,300,"static y origin");});
const lecture = require("fs").readFileSync(require("path").join(__dirname,"../math-course/lectures/algebra-02-determinant.md"),"utf8");
check(!/[\x00-\x08\x0b\x0c\x0e-\x1f]/.test(lecture),"no control-character damage");
for (const inline of lecture.replace(/\$\$[\s\S]*?\$\$/g,"").matchAll(/(?<![\\$])\$(?!\$)([\s\S]*?)(?<!\\)\$(?!\$)/g)) check(!inline[1].includes("\n"),"inline mathematics intact");
console.log(`determinant volume: PASS (${checks} independent checks; ${lab.selfTest().checks} self-tests)`);
