"use strict";
const assert=require('assert'),fs=require('fs'),path=require('path'),lab=require('../course-shared/labs/viscous-boundary-layer.js'),ref=require('./fixtures/blasius-reference.json');let checks=0;
function check(v,m){checks++;assert(v,m)}function close(a,b,m,t=1e-10){check(Math.abs(a-b)<=t*Math.max(1,Math.abs(b)),m+': '+a+' vs '+b)}
function simpson(f,a,b,n=512){let s=f(a)+f(b);for(let i=1;i<n;i++)s+=(i%2?4:2)*f(a+(b-a)*i/n);return s*(b-a)/n/3}
const d=lab.blasius(),truth=ref.truncations.find(r=>r.end===16);close(d.slope,truth.slope,'independent adaptive BVP wall slope',2e-10);close(d.eta99,truth.eta99,'independent BVP crossing',1e-7);ref.samples.forEach(p=>close(lab.profile(p.eta),p.u,'independent BVP including off-grid interpolation',1.5e-6));close(lab.profile(d.eta99),.99,'same-solution 99 percent point');
for(const step of [.02,.005]){const rows=lab.integrateBlasius(d.slope,step,12);for(let j=0;j<rows.length;j+=10){const row=rows[j],other=d.rows[Math.round(row.eta/.01)];close(row.u,other.u,'RK step comparison',2e-8)}}
check(Object.isFrozen(d)&&Object.isFrozen(d.rows)&&Object.isFrozen(d.rows[0]),'cached reference cannot be mutated');check(d.rows.every((r,i)=>r.du>0&&(i===0||r.u>=d.rows[i-1].u)),'monotone profile');close(d.rows.at(-1).u,1,'far boundary residual',1e-10);
const pressureFactor=simpson(t=>Math.cos(t)**2*Math.sin(t),0,Math.PI),shearFactor=simpson(t=>Math.sin(t)**3,0,Math.PI);
for(const a of [.001,.01,1])for(const U of [.001,.1,5])for(const rho of [1,1.2,1000])for(const mu of [.001,1,10]){const r=lab.stokesSphere(a,U,rho,mu);close(r.reynolds,2*rho*U*a/mu,'diameter Re');close(r.pressureDrag,3*mu*U/(2*a)*2*Math.PI*a*a*pressureFactor,'independent pressure traction integral',1e-8);close(r.shearDrag,3*mu*U/(2*a)*2*Math.PI*a*a*shearFactor,'independent shear traction integral',1e-8);close(r.drag,r.pressureDrag+r.shearDrag,'force sum');close(r.normalizedDrag,1,'normalized force missing-U regression');close(r.dragCoefficient,r.drag/(.5*rho*U*U*Math.PI*a*a),'Cd dynamic pressure definition');}
for(let log=-3;log<=1.0001;log+=.05){const re=10**log,r=lab.stokesSphere(1,re/2,1,1),svg=lab.scene('stokes',r),point=svg.match(/data-point="stokes" cx="([^"]+)" cy="([^"]+)"/);close((+point[1]-80)/555*4-3,Math.log10(r.reynolds),'actual log Re coordinate');close((350-+point[2])/57,Math.log10(r.dragCoefficient),'actual log Cd coordinate');const paths=[...svg.matchAll(/data-curve="([^"]+)"[^>]+d="([^"]+)"/g)];check(paths.length===2,'physical-reference/extrapolation split');paths.forEach(p=>{const pts=[...p[2].matchAll(/[ML]([\d.]+),([\d.]+)/g)];check(pts.length===81,'curve sampling');pts.forEach(m=>{const e=(+m[1]-80)/555*4-3,cd=(350-+m[2])/57;close(cd,Math.log10(24)-e,'actual log curve',2e-7);check(+m[2]>=65&&+m[2]<=350,'large Cd not clipped')})})}
for(let i=0;i<=80;i++){const re=10**(3+i*.05);for(const x of [.1,1,3]){const p=lab.flatPlate(re,x,10,1.2);close(p.kinematicViscosity,10*x/re,'physical closure');close(p.delta99,truth.eta99*x/Math.sqrt(re),'BVP thickness',1e-7);close(p.cfLocal,2*truth.slope/Math.sqrt(re),'BVP friction');close(p.shear,1.2*100*truth.slope/Math.sqrt(re),'wall shear');const svg=lab.scene('plate',p),curve=svg.match(/data-curve="blasius"[^>]+d="([^"]+)"/)[1],pts=[...curve.matchAll(/[ML]([\d.]+),([\d.]+)/g)];check(pts.length===161,'profile sample count');pts.forEach((m,j)=>{close((+m[1]-80)/430,lab.profile(j/20),'actual profile x',2e-8);close((350-+m[2])/35,j/20,'actual eta y',2e-7)});const point=svg.match(/data-point="plate" cx="([^"]+)" cy="([^"]+)"/);close((+point[1]-80)/430,.99,'99 percent marker');close((350-+point[2])/35,p.eta99,'99 percent height')}}
for(const x of [.1,1,3]){const a=lab.flatPlate(1e4,x,10,1.2),b=lab.flatPlate(4e4,4*x,10,1.2);close(b.kinematicViscosity,a.kinematicViscosity,'same-fluid downstream');close(b.delta99,2*a.delta99,'downstream thickness');close(b.cfLocal,a.cfLocal/2,'downstream friction')}
for(const bad of [0,-1,null,'1',NaN,Infinity])for(let i=0;i<4;i++){const args=[1,1,1,1];args[i]=bad;for(const fn of [lab.stokesSphere,lab.flatPlate]){checks++;assert.throws(()=>fn(...args))}}for(const v of [-1,13,NaN,'1',null]){checks++;assert.throws(()=>lab.profile(v))}for(const args of [[.33,0,12],[NaN,.01,12],[.33,.001,12],[.33,.01,100]]){checks++;assert.throws(()=>lab.integrateBlasius(...args))}checks++;assert.throws(()=>lab.stokesSphere(1e308,1e308,1,1));checks++;assert.throws(()=>lab.flatPlate(Number.MIN_VALUE,1,1,1));
const lecture=fs.readFileSync(path.join(__dirname,'../physics-course/lectures/fl-02-viscous.md'),'utf8');check(!/[\x00-\x09\x0b\x0c\x0e-\x1f]/.test(lecture),'TeX controls');for(const m of lecture.replace(/\$\$[\s\S]*?\$\$/g,'').matchAll(/(?<![\\$])\$(?!\$)([\s\S]*?)(?<!\\)\$(?!\$)/g))check(!m[1].includes('\n'),'inline TeX integrity');check(/<\/div>\s*### 3/.test(lecture),'model boundary not swallowed');
const svg=fs.readFileSync(path.join(__dirname,'../physics-course/images/fl-02-viscous-drag.svg'),'utf8'),curve=svg.match(/data-blasius="true" d="([^"]+)"/)[1],pts=[...curve.matchAll(/([\d.]+),([\d.]+)/g)],samples=ref.samples.filter(p=>p.eta<=8);check(pts.length===samples.length,'static collocation samples');pts.forEach((m,i)=>{close((+m[1]-530)/300,samples[i].u,'static independent curve x',2e-8);close((340-+m[2])/30,samples[i].eta,'static independent curve y',2e-7)});for(const [name,v]of [['压力',2],['剪切',4],['总阻力',6]]){const rect=svg.match(new RegExp('data-force="'+name+'"[^>]+height="([^"]+)"'))[1];close(+rect/35,v,'static force decomposition')}
console.log(`viscous boundary layer: PASS (${checks} independent checks; ${lab.selfTest().checks} self checks)`);
