'use strict';const assert=require('assert'),fs=require('fs'),path=require('path'),m=require('../course-shared/labs/pde-separation.js'),ref=require('./fixtures/pde-separation-reference.json');let checks=0;function check(x,msg){assert(x,msg);checks++}function near(a,b,t=2e-12){check(Number.isFinite(a)&&Math.abs(a-b)<=t*Math.max(1,Math.abs(b)),`${a} vs ${b}`)}
for(const[n,b]of ref.coefficients)near(m.coefficient(n),b,1e-13);
for(const c of ref.laplace){let a=m.laplaceFactor(c.n,c.y);check(Number.isFinite(a)&&a>=0&&a<=1,'stable Laplace ratio');check(Math.abs(a-c.factor)<=Math.max(1e-300,2e-12*Math.abs(c.factor)),'85 digit Laplace');}
for(const c of ref.tails){const a=m.evaluate({mode:c.mode,N:c.N,time:c.time}),rounding=c.mode==='heat'?Math.max(1e-300,c.norm*8e-12):1e-13;check(a.currentL2TailLower<=c.norm+rounding,'tail lower incl floating evaluation allowance');check(a.currentL2Tail>=c.norm-rounding,'tail upper incl floating evaluation allowance');if(c.mode==='heat'&&c.time===2&&c.N===16)check(a.currentL2Tail>0&&m.format(a.currentL2Tail)!=='0','tiny heat norm preserved');}
for(const mode of ['heat','wave','laplace'])for(const N of [1,2,7,16])for(const time of [0,.45,1,2]){
 const r=m.evaluate({mode,N,time});near(r.fullWaveEnergy,ref.waveEnergy);let partial=0,wave=0;for(let n=1;n<=N;n++){const b=m.coefficient(n);partial+=Math.PI/2*b*b;wave+=Math.PI/4*n*n*b*b;}if(mode!=='laplace')near(r.initialL2Tail**2,ref.initialL2Squared-partial);if(mode==='wave'){near(r.waveEnergy,wave);near(r.waveEnergyTail**2,2*(ref.waveEnergy-wave));}check(r.points.every(p=>Math.abs(p.reference-(mode==='laplace'?Math.sin(p.x):p.x*(Math.PI-p.x)))<1e-13),'exact initial profile');
}
for(const bad of [null,[],{N:0},{N:1.2},{N:17},{time:'0'},{time:-1},{time:3},{y:4},{mode:'typo'},{other:1}]){assert.throws(()=>m.evaluate(bad));checks++;}for(const n of [0,-1,1.5,Infinity]){assert.throws(()=>m.coefficient(n));checks++;}
// Independent midpoint quadrature of the actual finite solution and its two wave energy components.
for(const mode of ['heat','wave'])for(const N of [1,7,16])for(const t of [0,.45,2]){const r=m.evaluate({mode,N,time:t});let l2=0,e=0;const M=4096,dx=Math.PI/M;for(let j=0;j<M;j++){const x=(j+.5)*dx;let u=0,ut=0,ux=0;for(let n=1;n<=N;n++){const b=n%2?8/(Math.PI*n**3):0,f=mode==='heat'?Math.exp(-n*n*t):Math.cos(n*t);u+=b*f*Math.sin(n*x);ux+=n*b*f*Math.cos(n*x);ut+=mode==='heat'?-n*n*b*f*Math.sin(n*x):-n*b*Math.sin(n*t)*Math.sin(n*x);}l2+=u*u*dx;e+=(ut*ut+ux*ux)*dx/2;}near(l2,r.currentL2,2e-12);if(mode==='wave')near(e,r.waveEnergy,2e-12);}
class Node{constructor(tag){this.tag=tag;this.attrs={};this.children=[];this.nodeType=1;this.ownerDocument=doc;}setAttribute(k,v){this.attrs[k]=String(v)}appendChild(n){this.children.push(n);return n;}}
const doc={createElementNS:(ns,t)=>new Node(t),createTextNode:t=>({nodeType:3,text:t})};function parse(d){const v=d.match(/[-+]?\d*\.?\d+(?:e[-+]?\d+)?/gi).map(Number);return Array.from({length:v.length/2},(_,i)=>[v[2*i],v[2*i+1]]);}
for(const mode of ['heat','wave','laplace'])for(const N of [1,2,7,16])for(const t of [0,.45,2])for(const y of [0,Math.PI/2,Math.PI]){const r=m.evaluate({mode,N,time:t,y}),svg=m.drawChart(doc,r),p=svg.children.find(n=>n.attrs.class==='pse-profile'),q=svg.children.find(n=>n.attrs.class==='pse-reference'),ps=parse(p.attrs.d),qs=parse(q.attrs.d),extent=1.1*Math.max(1,...r.points.flatMap(p=>[Math.abs(p.value),Math.abs(p.reference)]));check(ps.length===321&&qs.length===321,'321 actual profile points');for(let i=0;i<ps.length;i++){near(ps[i][0],42+350*i/320,1.3e-4);near(ps[i][1],155-r.points[i].value/extent*111,1.3e-4);near(qs[i][1],155-r.points[i].reference/extent*111,1.3e-4);}const bars=svg.children.filter(n=>n.attrs.class==='pse-bar');check(bars.length===N,'bar count');for(let i=0;i<N;i++){near(+bars[i].attrs.height,Math.abs(r.rows[i].factor)*101);near(+bars[i].attrs.y,Math.min(155,155-r.rows[i].factor*101));}check(r.params.mode!=='heat'||r.params.time!==0||Math.max(...r.points.map(p=>p.value))>1.15,'unclipped true peak');}
const svg=fs.readFileSync(path.join(__dirname,'../math-course/images/pde-01-heat-decay.svg'),'utf8');function pts(id){let q=svg.match(new RegExp('<path id="'+id+'" d="([^"]+)"'));check(q,id);return parse(q[1]);}const initial=pts('initial');for(let j=0;j<=320;j++){let x=Math.PI*j/320;near(initial[j][0],65+355*j/320,1e-9);near(initial[j][1],350-220*x*(Math.PI-x)/2.7,1e-9);}
for(const [i,t]of [0,.05,.4,1].entries()){let a=pts('heat-'+i);for(let j=0;j<=320;j++){let u=0;for(let n=1;n<=31;n+=2)u+=8/(Math.PI*n**3)*Math.exp(-n*n*t)*Math.sin(n*Math.PI*j/320);near(a[j][1],350-220*u/2.7,1e-9);}}
for(const n of [1,3,7]){const a=pts('factor-'+n);for(let j=0;j<=200;j++){near(a[j][0],550+350*j/200,1e-9);near(a[j][1],130-220*Math.log10(Math.exp(-n*n*j/200))/22,1e-9);}}
console.log(`pde-separation independent: PASS (${checks} checks)`);
