'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path'),root=path.resolve(__dirname,'..'),m=require(path.join(root,'course-shared/labs/estimator-risk.js')),ref=require('./fixtures/estimator-risk-reference.json');let checks=0,maxMomentError=0;
const ids=['mle','laplace','shrink'];function ok(v,msg){checks++;assert(v,msg);}function near(x,y,t=3e-12){ok(Number.isFinite(x)&&Math.abs(x-y)<=Math.max(5e-324,t*Math.abs(y)),`${x} != ${y}`);}
for(const row of ref.rows){const weights=m.probabilities(row.n,row.p);near(weights.reduce((a,b)=>a+b,0),1);for(let k=0;k<weights.length;k++)near(weights[k],row.weights[k]);ids.forEach((id,a)=>{const r=m.riskLedger(row.n,row.p,id),v=row.stats[a];for(const key of ['mean','variance','mse']){near(r[key],v[key]);maxMomentError=Math.max(maxMomentError,Math.abs(r[key]-v[key]));near(r.enumerated[key],v[key],1e-11);}ok(r.crlbRegular===(row.p>0&&row.p<1),'exact interior');if(r.crlbRegular)near(r.biasedCRB,r.variance);else ok(r.biasedCRB===null,'no endpoint certificate');});}
for(let n=1;n<=100;n++)for(let i=0;i<=100;i++)for(const id of ids){const p=i/100,a=m.ESTIMATORS[id].a,r=m.riskLedger(n,p,id),mirror=m.riskLedger(n,1-p,id);near(r.mse,mirror.mse);near(r.mse,r.variance+r.bias*r.bias);near(r.enumerated.mse,r.mse);if(a){const threshold=n*a/(4*(n*(a+1)+a));if(Math.abs(p*(1-p)-threshold)>1e-12)ok((r.mse<m.closedRisk(n,p,'mle').mse)===(p*(1-p)>threshold),'exact beneficial region');}}
for(const bad of [[0,.2,'mle'],[101,.2,'mle'],[5.5,.2,'mle'],['5',.2,'mle'],[5,'0.2','mle'],[5,NaN,'mle'],[5,Infinity,'mle'],[5,-.1,'mle'],[5,1.1,'mle'],[5,.2,'toString'],[5,.2,'unknown']]){checks++;assert.throws(()=>m.riskLedger(...bad));}
for(const steps of [0,-1,2.2,'100',1001]){checks++;assert.throws(()=>m.riskCurve(5,'mle',steps));}
function points(d){return [...d.matchAll(/[ML]([-\d.e]+),([-\d.e]+)/g)].map(x=>[+x[1],+x[2]]);}
for(const n of [1,5,10,20,100])for(const p of [0,.13,.5,.91,1]){
 let original=null;for(const id of ids){const svg=m.riskPlot(n,p,id),maximum=Math.max(...ids.flatMap(key=>Array.from({length:201},(_,i)=>m.closedRisk(n,i/200,key).mse)))*1.12,paths=[];
  ids.forEach(key=>{const tag=svg.match(new RegExp('<path data-risk="'+key+'"[^>]*/>'))[0],d=tag.match(/ d="([^"]+)"/)[1];paths.push(d);const ps=points(d);ok(ps.length===201,'resolution');ps.forEach(([x,y],i)=>{near(x,70+630*i/200);ok(Math.abs(y-(330-250*m.closedRisk(n,i/200,key).mse/maximum))<5.1e-8,'actual risk ordinate');ok(y>=80&&y<=330,'risk not clipped');});});if(original)ok(JSON.stringify(paths)===JSON.stringify(original),'selection preserves common axes and curves');original=paths;
  const point=svg.match(/<circle[^>]*cx="([^"]+)" cy="([^"]+)"/);ok(Math.abs(+point[1]-(70+630*p))<5.1e-8,'selected p');ok(Math.abs(+point[2]-(330-250*m.closedRisk(n,p,id).mse/maximum))<5.1e-8,'selected risk');
 }
}
const svg=fs.readFileSync(path.join(root,'math-course/images/stat-02-estimator-risk.svg'),'utf8');for(const row of ref.figures){const panel=[5,20,100].indexOf(row.n),tag=svg.match(new RegExp('<path data-curve="n'+row.n+'-a'+row.a+'"[^>]*/>'))[0],ps=points(tag.match(/ d="([^"]+)"/)[1]),ymax=Math.max(...ref.figures.filter(f=>f.n===row.n).flatMap(f=>f.risk))*1.12;ok(ps.length===601,'static resolution');ps.forEach(([x,y],i)=>{ok(Math.abs(x-(65+350*panel+285*i/600))<5.1e-8,'static x');ok(Math.abs(y-(410-290*row.risk[i]/ymax))<5.1e-8,'static y');});}
near(ref.crossing,(1-Math.sqrt(11/21))/2);console.log('estimator risk independent: PASS',{checks,maxMomentError});
