'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path'),q=require('../course-shared/labs/quadratic-forms.js'),ref=require('./fixtures/quadratic-spectrum-reference.json');let checks=0;
function check(v,m){checks++;assert(v,m)}function relative(a,b,m){check(a===b||Math.abs(a-b)<=5e-13*Math.max(Math.abs(a),Math.abs(b)),m+': '+a+' vs '+b)}function close(a,b,m,t=2e-10){check(Math.abs(a-b)<=t*Math.max(1,Math.abs(b)),m+': '+a+' vs '+b)}
const mul=(a,b)=>a.map(r=>b[0].map((_,j)=>r.reduce((v,x,k)=>v+x*b[k][j],0))),T=a=>a[0].map((_,i)=>a.map(r=>r[i])),quad=(a,v)=>v[0]*(a[0][0]*v[0]+a[0][1]*v[1])+v[1]*(a[1][0]*v[0]+a[1][1]*v[1]);
for(const row of ref.family){const d=q.analyze(row);d.eigenvalues.forEach((v,i)=>relative(v,row.eigen[i],'mpmath original spectrum'));d.congruentEigenvalues.forEach((v,i)=>relative(v,row.congruentEigen[i],'mpmath constructed congruent spectrum'));}
for(const row of ref.generic){if(row.eigen==='unrepresentable'){checks++;assert.throws(()=>q.eigenvaluesSymmetric(row.matrix),RangeError);}else q.eigenvaluesSymmetric(row.matrix).forEach((v,i)=>relative(v,row.eigen[i],'800 digit generic eigen'));}
for(const familyId of ['positive','indefinite','semidefinite'])for(let bi=-18;bi<=18;bi++)for(let si=-15;si<=15;si++){
 const b=bi/10,shear=si/10,d=q.analyze({familyId,b,shear}),C=[[1,shear],[0,1]],Ci=[[1,-shear],[0,1]],expected=mul(T(C),mul(d.matrix,C)),similar=mul(Ci,mul(d.matrix,C));d.congruent.flat().forEach((v,i)=>close(v,expected.flat()[i],'independent congruence'));d.similar.flat().forEach((v,i)=>close(v,similar.flat()[i],'independent similarity'));
 const tuple=familyId==='positive'?'2,0,0':familyId==='indefinite'?'1,1,0':'1,0,1';check(d.inertia.tuple.join(',')===tuple&&d.congruentInertia.tuple.join(',')===tuple,'structural inertia');d.similarEigenvalues.forEach((v,i)=>close(v,d.eigenvalues[i],'similar model spectrum'));close(quad(d.matrix,d.point),1,'old marked point');close(quad(d.congruent,d.newPoint),1,'new marked point');close(d.point[0],d.newPoint[0]+shear*d.newPoint[1],'corresponding point x');close(d.point[1],d.newPoint[1],'corresponding point y');close(d.originalValue,1,'factorized old q');close(d.newValue,1,'factorized new q');
 for(const x of [-2,0,2])for(const y of [-2,0,2]){const mapped=[x+shear*y,y];close(quad(d.matrix,mapped),quad(d.congruent,[x,y]),'same quadratic value for arbitrary vector');}
 if(si===-15||si===0||si===15)for(const branch of q.contourPoints(d))for(const v of branch){close(quad(d.matrix,v),1,'analytic contour');const w=[v[0]-shear*v[1],v[1]];close(quad(d.congruent,w),1,'mapped contour');}
}
for(const field of ['b','shear'])for(const value of [null,'1',NaN,Infinity,-Infinity,-2,2]){checks++;assert.throws(()=>q.analyze({[field]:value}),RangeError);}for(const bad of [null,1,[],true]){checks++;assert.throws(()=>q.analyze(bad),TypeError);}for(const bad of [[],[[1,2],[3,4]],[[1,null],[null,1]],[[1],[1]]]){checks++;assert.throws(()=>q.eigenvaluesSymmetric(bad));}check(q.inertia([1e-100,-1e-100]).tuple.join(',')==='1,1,0','no epsilon sign collapse');check(q.formatNumber(12000,0)==='12000'&&q.formatNumber(1e-100)!=='0','scientific and integer formatting');
// Inspect the actual SVG renderer through a minimal DOM, independent of its coordinate helpers.
const doc={createElementNS(ns,tag){return{tag,attrs:{},children:[],setAttribute(k,v){this.attrs[k]=v},appendChild(n){this.children.push(n)}}}};
function walk(n,tag){return(n.tag===tag?[n]:[]).concat(...n.children.map(c=>walk(c,tag)));}
for(const familyId of ['positive','indefinite','semidefinite'])for(const b of [-1.8,.5,1.8])for(const shear of [-1.5,0,1.5]){const d=q.analyze({familyId,b,shear}),svg=q.contourSvg(doc,d,'audit');for(const path of walk(svg,'path')){const side=path.attrs['data-contour']==='new'?1:0,a=side?d.congruent:d.matrix,points=[...path.attrs.d.matchAll(/[ML]([-\d.]+),([-\d.]+)/g)];check(points.length===257,'rendered sample count');points.forEach(p=>{const v=[(+p[1]-185-370*side)/40,(235-+p[2])/40],delta=.5e-4/40,bound=2*delta*(Math.abs(a[0][0]*v[0]+a[0][1]*v[1])+Math.abs(a[1][0]*v[0]+a[1][1]*v[1]))+delta*delta*a.flat().reduce((s,x)=>s+Math.abs(x),0)+1e-10;check(Math.abs(quad(a,v)-1)<=bound,'rendered contour within derived pixel-rounding bound');});}for(const point of walk(svg,'circle')){const side=point.attrs['data-point']==='new'?1:0;check(+point.attrs.cx>=45+370*side&&+point.attrs.cx<=325+370*side&&+point.attrs.cy>=95&&+point.attrs.cy<=375,'marked point remains visible');}}
// Explicit projection, SVD error, Hessian and orthogonal-basis examples.
const U=[[1/Math.sqrt(3),1/Math.sqrt(2),1/Math.sqrt(6)],[1/Math.sqrt(3),-1/Math.sqrt(2),1/Math.sqrt(6)],[1/Math.sqrt(3),0,-2/Math.sqrt(6)]],A=[[2,1,1],[1,2,1],[1,1,2]];mul(T(U),U).flat().forEach((v,i)=>close(v,i%4===0?1:0,'explicit orthonormal basis'));mul(T(U),mul(A,U)).flat().forEach((v,i)=>close(v,[4,0,0,0,1,0,0,0,1][i],'orthogonal diagonalization'));
for(const t of [-1,-.8,-.5,0,.2]){const a=[[1,t,-1],[t,1,2],[-1,2,5]],det=a[0][0]*(a[1][1]*a[2][2]-a[1][2]*a[2][1])-a[0][1]*(a[1][0]*a[2][2]-a[1][2]*a[2][0])+a[0][2]*(a[1][0]*a[2][1]-a[1][1]*a[2][0]);close(det,-5*t*t-4*t,'parameter principal determinant');}
for(const theta of [0,.1,1,2,3]){const u=[Math.cos(theta),Math.sin(theta)],E=[[1-u[0]*u[0],-u[0]*u[1]],[-u[0]*u[1],1-u[1]*u[1]]];close(E.flat().reduce((s,v)=>s+v*v,0),1,'nonunique rank one Frobenius error');}
const lecture=fs.readFileSync(path.join(__dirname,'../math-course/lectures/algebra-06-quadratic.md'),'utf8');check(!/[\x00-\x09\x0b\x0c\x0e-\x1f]/.test(lecture),'no damaged TeX including tabs');check(!/^\+(?:$|\*\*)/m.test(lecture),'no patch residue');for(const m of lecture.replace(/\$\$[\s\S]*?\$\$/g,'').matchAll(/(?<![\\$])\$(?!\$)([\s\S]*?)(?<!\\)\$(?!\$)/g))check(!m[1].includes('\n'),'no newline in inline formula');
const svg=fs.readFileSync(path.join(__dirname,'../math-course/images/algebra-06-quadratic-forms.svg'),'utf8');let curveCount=0;for(const m of svg.matchAll(/<path d="([^"]+)"[^>]*data-family="([^"]+)" data-side="([01])"/g)){curveCount++;const name=m[2],side=+m[3],index=['positive','indefinite','semidefinite'].indexOf(name),A=name==='positive'?[[2,.5],[.5,2]]:name==='indefinite'?[[1,.5],[.5,-1]]:[[1,.5],[.5,.25]],B=side?mul([[1,0],[1,1]],mul(A,[[1,1],[0,1]])):A;const points=[...m[1].matchAll(/[ML]([-\d.]+),([-\d.]+)/g)];check(points.length===257,'static sample count');points.forEach(p=>close(quad(B,[(+p[1]-125-250*index)/30,(238-+p[2])/30]),1,'static level contour',1e-5));}check(curveCount===10,'three types and both coordinate records');
console.log(`quadratic forms: PASS (${checks} independent checks; ${q.selfTest().checks} self-tests)`);
