'use strict';const assert=require('assert'),fs=require('fs'),path=require('path'),m=require('../course-shared/labs/lebesgue.js');let checks=0;function check(x,msg){assert(x,msg);checks++;}function near(a,b,t=2e-12){check(Number.isFinite(a)&&Math.abs(a-b)<=t*Math.max(1,Math.abs(b)),`${a} vs ${b}`);}
class Node{constructor(tag){this.tag=tag;this.attrs={};this.children=[];this.nodeType=1;}setAttribute(k,v){this.attrs[k]=String(v)}appendChild(n){this.children.push(n);return n;}}
const doc={createElementNS:(ns,t)=>new Node(t),createTextNode:t=>({nodeType:3,text:t})};function points(d){const v=d.match(/[-+]?\d*\.?\d+(?:e[-+]?\d+)?/gi).map(Number);return Array.from({length:v.length/2},(_,i)=>[v[2*i],v[2*i+1]]);}
for(const key of ['indicator','spike','power'])for(let n=1;n<=40;n++){
 const d=m.evaluate(key,n),expected=key==='indicator'?(n-1)/n:key==='spike'?1:1/(n+1);near(d.integral,expected);near(d.limitIntegral,key==='indicator'?1:0);
 // Integrate the model independently after splitting at its actual jump, never missing a narrow spike.
 let sum=0;const cuts=key==='power'?[0,1]:[0,1/n,1];for(let c=1;c<cuts.length;c++){const a=cuts[c-1],b=cuts[c],N=2048,dx=(b-a)/N;for(let j=0;j<N;j++)sum+=m.value(key,n,a+(j+.5)*dx)*dx;}near(sum,expected,key==='power'?4e-7:2e-12);
 const svg=m.drawChart(doc,d),circles=svg.children.filter(n=>n.tag==='circle'&&n.attrs['data-n']);check(circles.length===40,'all exact integral sequence values');for(let j=1;j<=40;j++){let v=key==='indicator'?(j-1)/j:key==='spike'?1:1/(j+1);near(+circles[j-1].attrs.cx,58+(j-1)/39*677);near(+circles[j-1].attrs.cy,504-v*120/1.1);check(circles[j-1].attrs.class===(j===n?'lb-current':'lb-area-point'),'current term marker');}
 if(key==='power'){const p=svg.children.find(n=>n.tag==='path'&&n.attrs.class==='lb-profile'),ps=points(p.attrs.d);check(ps.length===321,'full power curve');for(let j=0;j<=320;j++){near(ps[j][0],58+677*j/320,1e-9);near(ps[j][1],265-223*(j/320)**n/1.12,1e-9);}}
 else{const rect=svg.children.find(n=>n.tag==='rect'&&n.attrs.class==='lb-area');near(+rect.attrs.width,key==='spike'?677/n:677*(1-1/n));near(+rect.attrs.height,223/1.12);const line=svg.children.filter(n=>n.tag==='line'&&n.attrs.class==='lb-profile');check(line.every(n=>n.attrs.y1===n.attrs.y2),'jump has no false vertical graph segment');const closed=svg.children.filter(n=>n.tag==='circle'&&n.attrs.class==='lb-closed'),open=svg.children.filter(n=>n.tag==='circle'&&n.attrs.class==='lb-open');check(open.length===(key==='spike'?2:1),'open jump endpoints');for(const node of closed){const x=(+node.attrs.cx-58)/677,y=(265-(+node.attrs.cy))*d.yMax/223; // compare endpoint formula without reconstructing x across a rounding boundary
 if(key==='spike')near(y,0);else near(y,1);}}
 if(key==='spike'){near(m.value(key,n,0),0,0);near(m.value(key,n,1/n),0,0);near(m.value(key,n,.5/n),n,0);}else if(key==='indicator')near(m.value(key,n,1/n),1,0);
}
for(const key of ['indicator','spike','power'])for(const n of [0,41,2.2,'3',null,NaN,Infinity]){assert.throws(()=>m.evaluate(key,n));checks++;}for(const key of ['__proto__','constructor','typo',null]){assert.throws(()=>m.evaluate(key,1));checks++;}for(const x of [-.1,1.1,'0',NaN,Infinity]){assert.throws(()=>m.value('power',2,x));checks++;}
// Verify the explicit lower bound ruling out an L1 dominator for the spike.
for(let j=2;j<=10000;j++){let x=1/(j+.1),n=Math.ceil(1/(2*x));check(n>=1/(2*x)&&n<1/x,'dominator lower bound index');}
const svg=fs.readFileSync(path.join(__dirname,'../math-course/images/real-02-riemann-vs-lebesgue.svg'),'utf8');function attrs(id){const q=svg.match(new RegExp('<rect id="'+id+'"([^>]+)>'));check(q,id);return Object.fromEntries([...q[1].matchAll(/([\w-]+)="([^"]+)"/g)].map(x=>[x[1],x[2]]));}let area=0;for(let j=1;j<=4;j++){const p=attrs('layer-'+j),half=Math.sqrt(1-j/4);near(+p.x,75+365*(1-half)/2,1e-9);near(+p.width,365*half,1e-9);near(+p.y,355-235*(j/4)/1.1,1e-9);near(+p.height,235/1.1/4,1e-9);area+=half/2;}near(area,(Math.sqrt(3)+Math.sqrt(2)+1)/4);check(Math.abs(area-1.036566)<5e-7,'printed lower sum rounds correctly');check(4/3-area<.5,'integral error budget');const ps=points(svg.match(/<path id="function" d="([^"]+)"/)[1]);for(let j=0;j<=400;j++){const x=j/200;near(ps[j][0],75+365*x/2,1e-9);near(ps[j][1],355-235*x*(2-x)/1.1,1e-9);}
console.log(`lebesgue-convergence independent: PASS (${checks} checks)`);
