'use strict';const assert=require('assert'),fs=require('fs'),path=require('path'),m=require('../course-shared/labs/cantor-measure.js');let checks=0;function check(x,msg){assert(x,msg);checks++;}function near(a,b,t=2e-12){check(Number.isFinite(a)&&Math.abs(a-b)<=t*Math.max(1,Math.abs(b)),`${a} vs ${b}`);}function fraction(a,n,d){check(BigInt(a.n)*BigInt(d)===BigInt(n)*BigInt(a.d),'exact rational ledger');}
// Independent standard endpoints by ternary digits, fat endpoints by path offsets.
function endpoints(mode,n){return Array.from({length:2**n},(_,j)=>{let a=0;for(let k=1;k<=n;k++){let bit=(j>>(n-k))&1;if(mode==='standard')a+=bit*2/3**k;else a+=bit*(2**k+3)/2**(2*k+1);}let len=mode==='standard'?1/3**n:(2**n+1)/2**(2*n+1);return[a,a+len];});}
class Node{constructor(tag){this.tag=tag;this.attrs={};this.children=[];this.nodeType=1;this.ownerDocument=doc;}setAttribute(k,v){this.attrs[k]=String(v)}appendChild(n){this.children.push(n);return n;}}
const doc={createElementNS:(ns,t)=>new Node(t),createTextNode:t=>({nodeType:3,text:t})};
for(const mode of ['standard','fat'])for(let n=0;n<=6;n++){const d=m.evaluate(mode,n),expected=endpoints(mode,n);check(d.intervalCount===2**n,'branch count');let total=0;expected.forEach(([a,b],j)=>{near(d.intervals[j][0],a);near(d.intervals[j][1],b);check(b>a,'positive length');if(j)check(a>expected[j-1][1],'disjoint gaps');total+=b-a;});fraction(d.remaining,mode==='standard'?2**n:2**n+1,mode==='standard'?3**n:2**(n+1));near(total,d.remaining.n/d.remaining.d);near(d.deleted.n/d.deleted.d+total,1);if(n){const prev=m.evaluate(mode,n-1);near(prev.remaining.n/prev.remaining.d-total,d.deletedThisStage.n/d.deletedThisStage.d);if(mode==='fat')near((prev.segmentLength.n/prev.segmentLength.d)/(4**-n),2**n+2);}
const svg=m.drawChart(doc,d),rects=svg.children.filter(n=>n.tag==='rect');check(rects.length===2**n,'actual rectangles');rects.forEach((p,i)=>{near(+p.attrs.x,58+632*expected[i][0]);near(+p.attrs.width,632*(expected[i][1]-expected[i][0]));});const tick0=svg.children.filter(n=>n.tag==='text'&&n.children.some(c=>c.text==='0'));check(tick0.length===1,'no doubled endpoint tick');}
for(let k=0;k<=5;k++)for(let den=2;den<=64;den++){const d=m.denseModel(k,den),N=2**k+1,two=2n**BigInt(N);check(d.pointCount===N,'dense count');const sorted=d.points.map(p=>p.value).sort((a,b)=>a-b);sorted.forEach((v,j)=>near(v,j/2**k,0));fraction(d.outerCoverBudget,two-1n,BigInt(den)*two);fraction(d.tailBudget,1n,BigInt(den)*two);for(let i=0;i<N;i++)fraction(d.covers[i].length,1n,BigInt(den)*2n**BigInt(i+1));check(m.valueText(d.tailBudget.n/d.tailBudget.d)!=='0','positive tail never formatted zero');const svg=m.drawChart(doc,d),circles=svg.children.filter(n=>n.tag==='circle');check(circles.length===N,'actual point count');circles.forEach((p,j)=>near(+p.attrs.cx,58+632*d.points[j].value));}
for(const mode of ['standard','fat','dense'])for(const n of [-1,1.2,7,'3',NaN,Infinity,null]){assert.throws(()=>m.evaluate(mode,n));checks++;}for(const mode of ['','typo',null]){assert.throws(()=>m.evaluate(mode,1));checks++;}for(const e of [0,1,65,3.5,'16',null,NaN]){assert.throws(()=>m.denseModel(1,e));checks++;}
// Simple approximation: independent dyadic level counts, monotonicity and finite-value error.
for(const f of [0,.1,1/3,1,Math.PI,10,100,Infinity]){let prev=0;for(let n=1;n<=15;n++){const s=Number.isFinite(f)?Math.min(n,Math.floor(2**n*f)/2**n):n;check(s>=prev&&s<=f,'nonnegative simple approximation monotonic');if(n>f)check(f-s<2**-n,'eventual dyadic error');prev=s;}}
const svg=fs.readFileSync(path.join(__dirname,'../math-course/images/real-01-cantor-lengths.svg'),'utf8');function attrs(id){const match=svg.match(new RegExp('<(?:rect|circle) id="'+id+'"([^>]+)>'));check(match,id);return Object.fromEntries([...match[1].matchAll(/([\w-]+)="([^"]+)"/g)].map(x=>[x[1],x[2]]));}for(const[mode,i]of[['standard',0],['fat',1]]){for(let n=0;n<=4;n++)endpoints(mode,n).forEach(([a,b],j)=>{const p=attrs(`${mode}-${n}-${j}`);near(+p.x,70+470*i+350*a,1e-9);near(+p.width,350*(b-a),1e-9);});for(let n=0;n<=12;n++){const p=attrs(`length-${mode}-${n}`),v=mode==='standard'?(2/3)**n:.5+2**-(n+1);near(+p.cx,85+795*n/12,1e-9);near(+p.cy,579-v*177,1e-9);}}
console.log(`cantor-measure independent: PASS (${checks} checks)`);
