"use strict";
const assert=require('assert'),fs=require('fs'),path=require('path'),root=path.resolve(__dirname,'..'),m=require('../course-shared/labs/radiative-transfer.js'),ref=require('./fixtures/radiative-reference.json');let checks=0;
function check(v,msg){assert(v,msg);checks++;}function near(a,b,t=3e-13,abs=1e-300){check(Math.abs(a-b)<=abs+t*Math.max(Math.abs(a),Math.abs(b)),`${a} != ${b}`);}
for(const f of ref.slabs){const z=m.analyzeSlab({Iin:f.Iin,S:f.S,tau:f.tau,bins:f.bins});for(const k of ['transmitted','emitted','Iout'])near(z.solution[k],f[k]);near(z.ledger.sourceTotal,f.emitted,8e-13);for(let i=0;i<f.bins;i++){near(z.rows[i].contribution,f.layers[i],8e-13);check(z.rows[i].escapeToExit>=0&&z.rows[i].escapeToExit<=1+2e-14,'escape bounds');if(f.tau===0)check(z.rows[i].escapeToExit===1,'zero-width limiting weight');}check(z.equality.finiteExactCondition===(f.Iin===f.S),'structural equality');const curve=m.pathForSolution(z.solution,720,360,60),coords=curve.path.match(/-?\d+(?:\.\d+)?/g).map(Number);check(coords.length===(f.tau===0?2:322),'point count');for(let i=0;i<coords.length/2;i++){const t=f.tau*i/160,expected=f.S+(f.Iin-f.S)*Math.exp(-t);near(coords[2*i],60+(f.tau===0?0:600*i/160),0,.00051);near(coords[2*i+1],260-200*expected/curve.high,0,.00051);}}
for(const f of ref.ode)near(m.formalSolution(f.Iin,f.S,f.tau).Iout,f.Iout,3e-11);
for(const f of ref.barbier)near(f.I,f.a+f.b*f.mu+2*f.c*f.mu*f.mu,2e-12);
for(const e of [0,.15,.5,1])for(const B of [0,.3,1,1e6])for(const J of [0,.25,1,1e6])near(m.resolveSource({sourceModel:'scattering',B,J,epsilon:e}).S,J+e*(B-J),5e-15,1e-10);
for(const bad of [null,[],false,{Iin:1,S:1,tau:1,typo:2},{Iin:'1',S:1,tau:1},{Iin:1,S:NaN,tau:1},{Iin:1,S:1,tau:-1},{Iin:1,S:1,tau:1001},{Iin:1,S:1,tau:1,bins:0},{Iin:1,S:1,tau:1,bins:1.5},{Iin:1,S:1,tau:1,bins:257},{Iin:1,S:1,tau:1,sourceModel:'typo'},{Iin:1,tau:1,sourceModel:'LTE',B:1,epsilon:.5},{Iin:1,tau:1,sourceModel:'scattering',B:1,J:1,epsilon:null}]){assert.throws(()=>m.analyzeSlab(bad));checks++;}
check(m.questionSpecs(m.analyzeSlab(m.PRESETS[0]))[0].expected==='comparable','default prediction');check(m.questionSpecs(m.analyzeSlab({Iin:0,S:0,tau:0}))[0].expected==='comparable','zero prediction');check(!m.equalityBoundary(m.formalSolution(0,1,1000),1).finiteExactCondition,'underflow cannot certify equality');
const svg=fs.readFileSync(path.join(root,'physics-course/images/ap-01-radiative-transfer.svg'),'utf8');
function points(id){const match=svg.match(new RegExp('<path id="'+id+'" d="([^"]+)"'));check(!!match,id);return [...match[1].matchAll(/[ML]([\d.]+),([\d.]+)/g)].map(x=>[+x[1],+x[2]]);}
const limb=points('limb-curve');check(limb.length===201,'limb count');for(let i=0;i<limb.length;i++){near(limb[i][0],65+350*i/200,0,6e-8);near(limb[i][1],350-245*(3*i/200+2)/5/1.1,0,6e-8);}
for(const [id,S]of [['absorption',.3],['matched',1],['emission',1.7]]){const p=points(id);check(p.length===401,'line count');for(let i=0;i<p.length;i++){let x=-2+i*.01,tau=.1+3*Math.exp(-x*x/.5),ic=S+(1-S)*Math.exp(-.1),iv=m.formalSolution(1,S,tau).Iout;near(p[i][0],540+(x+2)/4*350,0,6e-8);near(p[i][1],350-245*iv/ic/1.8,0,6e-8);}}
console.log(`radiative-transfer independent: PASS (${checks} checks; ${ref.slabs.length} high-precision cases, ${ref.ode.length} Radau orbits, ${ref.barbier.length} QUADPACK integrals)`);
