"use strict";
const fs=require('fs'),assert=require('assert'),m=require('../course-shared/labs/stellar-structure.js'),ref=require('./fixtures/stellar-reference.json');let checks=0;
function check(v,msg){assert(v,msg);checks++;}function near(a,b,t=1e-8){check(Math.abs(a-b)<=t*Math.max(1,Math.abs(b)),`${a} != ${b}`);}
for(const f of ref.cases){const z=m.solveLaneEmden(f.n),fine=m.solveLaneEmden(f.n,{step:.0025});near(z.surface.xi,f.xi,1e-8);near(z.surface.massDimensionless,f.mu,1e-8);near(z.dimensionlessRows.at(-1).pressureIntegralDimensionless,f.pressureIntegral,1e-8);near(z.gravityIntegralDimensionless,f.gravityIntegral,1e-8);near(z.gravitationalEnergy,z.gravitationalAnalytic,1e-8);check(z.virialRelativeResidual<1e-8,'virial');near(fine.surface.xi,f.xi,2e-9);near(fine.surface.massDimensionless,f.mu,2e-9);
 for(let i=0;i<z.rows.length;i++){const a=z.rows[i],b=z.rows[Math.max(0,i-1)];check(Object.values(a).every(Number.isFinite),'finite rows');check(a.pressure<=b.pressure+1e-12,'pressure monotone');check(a.enclosedMass>=b.enclosedMass-1e-8,'mass monotone');if(f.n===1&&a.xi>0){near(a.theta,Math.sin(a.xi)/a.xi,1e-8);near(z.dimensionlessRows[i].massDimensionless,Math.sin(a.xi)-a.xi*Math.cos(a.xi),1e-8);}}
 for(const [x,t,v]of f.samples){let j=z.rows.findIndex(p=>p.xi>=x),a=z.dimensionlessRows[j-1],b=z.dimensionlessRows[j],w=(x-a.xi)/(b.xi-a.xi);near(a.theta+w*(b.theta-a.theta),t,2e-6);near(a.phi+w*(b.phi-a.phi),v,2e-6);}
 for(const rho of [.5,1,2,4])for(const K of [.1,1,10])for(const G of [.1,1,10]){const a=m.solveLaneEmden(f.n,{rhoC:rho,K,G});near(a.radius/z.radius,Math.sqrt(K/G)*rho**((1-f.n)/(2*f.n)),1e-12);near(a.mass/z.mass,(K/G)**1.5*rho**((3-f.n)/(2*f.n)),1e-12);near(a.gravitationalEnergy/a.gravitationalAnalytic,1,1e-8);}}
for(const [n,o]of [[null,{}],['3',{}],[.5,{}],[5,{}],[3,null],[3,[]],[3,{step:0}],[3,{step:1e-20}],[3,{maxXi:1e10}],[3,{rhoC:'1'}],[3,{K:Infinity}],[3,{G:1e-20}],[3,{typo:1}],[3,{maxXi:1}]]){assert.throws(()=>m.solveLaneEmden(n,o));checks++;}
const svg=fs.readFileSync(require('path').join(__dirname,'../physics-course/images/ap-02-stellar-hr.svg'),'utf8');function points(id){let x=svg.match(new RegExp('<path id="'+id+'" d="([^"]+)"'));check(!!x,id);return [...x[1].matchAll(/[ML]([\d.]+),([\d.]+)/g)].map(x=>[+x[1],+x[2]]);}
for(const [id,pow]of [['mass15',.5],['radius15',-1/6],['mass3',0],['radius3',-1/3]]){const a=points(id);check(a.length===201,'scaling count');for(let i=0;i<a.length;i++){let rho=.5+3.5*i/200;near(a[i][0],65+350*i/200,1e-9);near(a[i][1],350-rho**pow/2.2*245,1e-9);}}
for(const [id,r]of [['radius001',.01],['radius1',1],['radius100',100]])for(const [x,y]of points(id)){let t=4.5-(x-540)*1.1/350,l=(350-y)*9/245-4;near(l,2*Math.log10(r)+4*(t-Math.log10(5772)),1e-8);}
// Inspect actual rendered coordinates without relying on a browser.
class Node{constructor(tag){this.tag=tag;this.attrs={};this.children=[];this.nodeType=1;}setAttribute(k,v){this.attrs[k]=String(v);}appendChild(n){this.children.push(n);return n;}}
const doc={createElementNS:(ns,t)=>new Node(t),createTextNode:t=>({nodeType:3,text:t})};
for(const preset of m.PRESETS){const z=m.analyze(preset.id),svg=m.profileSvg(doc,z,1),paths=svg.children.filter(x=>x.tag==='path');check(paths.length===3,'profile curves');for(let k=0;k<3;k++){const xy=[...paths[k].attrs.d.matchAll(/[ML]([-\d.e+]+) ([-\d.e+]+)/g)];check(xy.length===z.rows.length,'all profile points');for(let i=0;i<xy.length;i++){let a=z.rows[i];near(+xy[i][1],(k===2?405:45)+270*a.xi/z.surface.xi,1e-12);near(+xy[i][2],238-185*(k===0?a.pressureRatio:k===1?a.densityRatio:a.massFraction),1e-12);}}}
console.log(`stellar-structure independent: PASS (${checks} checks; ${ref.cases.length} DOP853 references)`);
