'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path'),lab=require('../course-shared/labs/resistive-mhd.js'),ref=require('./fixtures/mhd-reference.json');let checks=0;
function check(v,m){checks++;assert(v,m)}function close(a,b,m,t=1e-9){check(Math.abs(a-b)<=t*Math.max(1,Math.abs(b)),m+': '+a+' vs '+b)}
for(const row of ref.modes){const r=lab.evaluate(row.params);for(const x of [0,.17,.51,.99]){const a=2*Math.PI*row.params.mode*x/row.params.L;close(r.fieldAt(x),row.a[0]*Math.cos(a)-row.a[1]*Math.sin(a),'independent implicit IVP',2e-10);}close(r.ledger.at(-1).cumulativeDissipation,row.joule,'independent QUADPACK Joule integral',2e-10);}
for(const L of [.5,1,2])for(const U of [-1.5,0,1.5])for(const eta of [0,1e-15,.025,.25])for(const n of [1,2,8,64]){const p={L,U,eta,mode:n,time:1.2,phase:.4},r=lab.evaluate(p),q=2*Math.PI*n/L;close(r.decayRate,eta*q*q,'rate');close(r.energyRatio,Math.exp(-2*eta*q*q*1.2),'energy exponent');for(const row of r.ledger){check(row.energy>=0&&row.dissipated>=0,'nonnegative energy and loss');close(row.balanceResidual,0,'independent FD space/time quadrature normalized residual',3e-9);close(row.energy+row.dissipated,r.initialEnergy,'energy plus stable analytic loss');}if(eta===0){check(r.Rm===(U===0?null:Infinity),'zero/zero and ideal limit separated');}else{close(r.scales.tauDiff/r.scales.tauAdv,r.Rm,'timescale Rm');}const x=.31,hh=1e-5*L/n,t=eta*q*q>.1?.05/(eta*q*q):.01,ht=1e-5/Math.max(1,eta*q*q,Math.abs(U*q));const f=(xx,tt)=>lab.fieldValue(p,xx,tt),v=f(x,t),dx=(f(x-2*hh,t)-8*f(x-hh,t)+8*f(x+hh,t)-f(x+2*hh,t))/(12*hh),dxx=(-f(x+2*hh,t)+16*f(x+hh,t)-30*v+16*f(x-hh,t)-f(x-2*hh,t))/(12*hh*hh),dt=(f(x,t-2*ht)-8*f(x,t-ht)+8*f(x,t+ht)-f(x,t+2*ht))/(12*ht);close((dt+U*dx-eta*dxx)/Math.max(1,eta*q*q,Math.abs(U*q)),0,'independent finite-difference PDE residual',3e-5);}
const tiny=lab.energyLedger({eta:1e-18,time:1e-4}).at(-1);check(tiny.dissipated>0,'tiny energy loss survives exp cancellation');close(tiny.dissipated/(.25*2e-18*(2*Math.PI)**2*1e-4),1,'tiny loss leading asymptotic',1e-12);for(const z of [0,1e-20,1e-10,.1,1,10,40,1e6])close(lab.expIntegral(z),-Math.expm1(-z),'independent adaptive integral vs closed form',2e-12);
for(const key of ['L','U','eta','B0','mode','phase','time','mu0'])for(const v of [null,true,'1',NaN,Infinity,-Infinity,1e10]){checks++;assert.throws(()=>lab.evaluate({[key]:v}));}for(const v of [null,[],true,{unknown:1},{mode:1.2},{n:1.2},{mode:2,n:3},{time:2,t:3}]){checks++;assert.throws(()=>lab.evaluate(v));}for(const v of [0,2,Infinity,2.1,'40']){checks++;assert.throws(()=>lab.sampleField({mode:8},v));}for(const v of [null,[],[NaN],[-1],['1'],Array(102).fill(0)]){checks++;assert.throws(()=>lab.energyLedger({},v));}
class N{constructor(tag,doc){this.tag=tag;this.ownerDocument=doc;this.attrs={};this.children=[];this.nodeType=1;this.textContent=''}setAttribute(k,v){this.attrs[k]=String(v)}appendChild(n){this.children.push(n);return n}removeChild(n){this.children.splice(this.children.indexOf(n),1)}get firstChild(){return this.children[0]}all(){return this.children.flatMap(n=>[n,...n.all()])}}
const doc={createElementNS:(_,t)=>new N(t,doc),createElement:t=>new N(t,doc),createTextNode:t=>{const n=new N('#text',doc);n.textContent=String(t);return n}};
for(const mode of [1,8,64])for(const U of [-1.5,0,1.5])for(const eta of [0,1e-15,.025,.25]){const r=lab.evaluate({mode,U,eta,time:6}),a=new N('svg',doc),b=new N('svg',doc);lab.drawFieldChart(doc,a,r);lab.drawEnergyChart(doc,b,r);for(const svg of [a,b])svg.all().forEach(n=>Object.values(n.attrs).forEach(v=>check(!/NaN|Infinity/.test(v),'finite SVG attributes')));const field=a.all().find(n=>n.attrs.class==='rmhd-current-field'),pts=[...field.attrs.d.matchAll(/[ML] ([\d.]+) ([\d.]+)/g)];check(pts.length===Math.max(256,32*mode)+1,'sampling grows with mode');pts.forEach((m,i)=>{const x=i/(pts.length-1);close(+m[1],54+x*650,'field x scale',.0051);close(+m[2],30+(1.12-r.fieldAt(x)/r.params.B0)/2.24*237,'actual signed phase and amplitude',.0051)});const energy=b.all().find(n=>n.attrs.class==='rmhd-energy-line'),tMax=+energy.attrs['data-tmax'],gamma=+energy.attrs['data-gamma'];[...energy.attrs.d.matchAll(/[ML] ([\d.]+) ([\d.]+)/g)].forEach((m,i)=>{const t=gamma===0?tMax*i/120:Math.expm1(Math.log1p(gamma*tMax)*i/120)/gamma;close(+m[1],54+i/120*650,'logarithmic time screen coordinate',.0051);close(+m[2],30+(1.05-Math.exp(-gamma*t))/1.05*207,'energy ordinate',.0051)});}
const C=ref.constants,svg=fs.readFileSync(path.join(__dirname,'../physics-course/images/fl-06-plasma-regimes.svg'),'utf8');function tf(n){const p=C.hbar*Math.cbrt(3*Math.PI**2*n),w=p/(C.me*C.c);return C.me*C.c*C.c/C.k*w*w/(Math.sqrt(1+w*w)+1)}function tg(n){return C.e*C.e/(4*Math.PI*C.eps0*C.k)*Math.cbrt(4*Math.PI*n/3)}for(const row of ref.boundaries){close(tf(row.n),row.tf,'100-digit Fermi reference',1e-13);close(tg(row.n),row.tg,'100-digit Coulomb reference',1e-13)}for(const [name,fn] of [['fermi',tf],['coupling',tg]]){const d=svg.match(new RegExp('id="'+name+'" d="([^"]+)"'))[1];for(const m of d.matchAll(/[ML]([\d.]+),([\d.]+)/g)){const logn=6+(+m[1]-75)/735*32,logt=(420-+m[2])/340*12;close(logt,Math.log10(fn(10**logn)),'physical boundary actual logarithmic coordinates',1e-8)}}for(const m of svg.matchAll(/data-ne="([^"]+)" data-eV="([^"]+)" cx="([^"]+)" cy="([^"]+)"/g)){close(+m[3],75+(Math.log10(+m[1])-6)/32*735,'NRL density cm to SI and x axis',1e-8);close(+m[4],420-Math.log10(+m[2]*C.e/C.k)/12*340,'NRL eV to Kelvin and y axis',1e-8)}
const body=fs.readFileSync(path.join(__dirname,'../physics-course/lectures/fl-06-plasma-mhd.md'),'utf8');check(!/[\x00-\x09\x0b\x0c\x0e-\x1f]/.test(body),'TeX controls');check(!/^\+(?!\+)/m.test(body.replace(/\$\$[\s\S]*?\$\$/g,'')),'patch residue');for(const m of body.replace(/\$\$[\s\S]*?\$\$/g,'').matchAll(/(?<![\\$])\$(?!\$)([\s\S]*?)(?<!\\)\$(?!\$)/g))check(!m[1].includes('\n'),'inline TeX');
console.log(`Resistive MHD: PASS (${checks} independent checks; ${lab.selfTest().checks} self checks)`);
