'use strict';
const assert=require('assert'),m=require('../course-shared/labs/manifold-atlas'),f=require('../course-shared/labs/forms-stokes');let checks=0;
function ok(x,t){checks++;assert(x,t)}function close(x,y,t=1e-9){ok(Math.abs(x-y)<=t*Math.max(1,Math.abs(x),Math.abs(y)),`${x} vs ${y}`)}
for(let i=-40;i<=40;i++){let u=i/10;if(!u)continue;let p=m.circleFromNorth(u);close(p[0]**2+p[1]**2,1);close(m.circleNorthCoordinate(p),u);close(m.circleSouthCoordinate(p),1/u);close(m.circleTransitionJacobian(u)[0][0],-1/u**2);let h=1e-5;close((m.circleTransition(u+h)-m.circleTransition(u-h))/(2*h),-1/u**2,2e-8);}
for(let i=-20;i<=20;i++)for(let j=-10;j<=10;j++){if(!i&&!j)continue;let u=[i/10,j/10],p=m.sphereFromNorth(u),v=m.sphereTransition(u),J=m.sphereTransitionJacobian(u);close(Math.hypot(...p),1);m.sphereSouthCoordinate(p).forEach((x,k)=>close(x,v[k]));ok(m.matrixRank(J)===2,'chart invertible');close(J[0][0]*J[1][1]-J[0][1]*J[1][0],-1/(u[0]**2+u[1]**2)**2);for(let k=0;k<2;k++){let plus=u.slice(),minus=u.slice();plus[k]+=1e-6;minus[k]-=1e-6;let vp=m.sphereTransition(plus),vm=m.sphereTransition(minus);for(let row=0;row<2;row++)close((vp[row]-vm[row])/2e-6,J[row][k],5e-8)}}
for(const scale of [1e-100,1e-12,1,1e12,1e100]){ok(m.matrixRank([[scale,2*scale],[2*scale,4*scale]])===1,'scaled rank one');ok(m.matrixRank([[scale,0],[0,scale]])===2,'scaled invertible')}
for(const bad of [[[NaN]],[[1],[1,2]],[null]]){assert.throws(()=>m.matrixRank(bad));checks++}for(const bad of [[NaN,0],[0,0],[2,0]]){assert.throws(()=>m.circleNorthCoordinate(bad));checks++}
for(const kind of ['circle','sphere'])for(let i=-20;i<=20;i++){let r=m.analyze(kind,i/10);for(const v of r.tangent.basis)close(r.embeddingPoint.reduce((sum,x,k)=>sum+x*v[k],0),0);}
for(const id of ['square','deformed','reverse','punctured-loop'])for(const power of [1,3])for(const c of [-2,-.75,0,.5,2])for(const n of [2,4,8,16,32,64])for(const radius of [.25,1,2.5]){let r=f.compute(id,{scale:c,power,grid:n,radius});const expected=id==='punctured-loop'?2*Math.PI*c:id==='deformed'?c*(power+2)/(2*(power+1)):id==='reverse'?-c:c;close(r.exactLine,expected);if(id==='punctured-loop'){close(r.line,expected);ok(r.area===null&&r.closed,'loop not filled');}else{let line=expected,area=expected;if(power===3){if(id==='deformed')line=area=expected-c/(16*n*n);else area=expected*(1-1/(4*n*n));}close(r.line,line,2e-11);close(r.area,area,2e-11);close(r.difference,line-area,2e-11);}ok(r.exactForm===(c===0),'only zero form exact');ok(r.closed===(id==='punctured-loop'||c===0),'closed condition');}
let trap=f.compute('deformed',{power:3,grid:2});close(trap.line,trap.area);ok(Math.abs(trap.line-trap.exactLine)>.01,'equal approximations can both be wrong');
// Direct determinant change-of-variables: the reflection reverses a 2-form,
// while its probability-density Jacobian remains positive.
for(let i=0;i<=20;i++)for(let j=0;j<=20;j++){let p=f.mapPoint('reverse',i/20,j/20);close(p.xu*p.yv-p.xv*p.yu,-1);close(Math.abs(p.jacobian),1)}
console.log(`Manifold/forms independent checks: ${checks} PASS`);
