'use strict';const assert=require('assert'),fs=require('fs'),path=require('path'),root=path.resolve(__dirname,'..'),m=require(path.join(root,'course-shared/labs/quadric-sections.js')),ref=require('./fixtures/quadric-reference.json');let checks=0,maxResidual=0;
function ok(v,msg){checks++;assert(v,msg)}function near(x,y,t=3e-12){ok(Number.isFinite(x)&&Math.abs(x-y)<=t*Math.max(1,Math.abs(y)),`${x} != ${y}`)}
for(const r of ref.conics){const a=m.sectionKind(...r.input);ok(a.kind===r.expected.kind,'exact conic type');ok(a.shiftedSign===r.expected.sign,'exact shifted sign');}
const kinds=new Set();for(const r of ref.cuts){const d=m.analyze({modelId:r.modelId,axis:r.axis,slice:r.slice});ok(d.section.kind===r.expected.kind,'exact slice type');ok(d.section.shiftedSign===r.expected.sign,'exact slice sign');kinds.add(d.section.kind);const points=m.sectionCurve(d);for(const p of points){if(!p)continue;ok(p.every(Number.isFinite),'finite plotted point');const s=d.section,terms=[s.a*p[0]*p[0],s.b*p[1]*p[1],s.l1*p[0],s.l2*p[1]],res=Math.abs(terms.reduce((a,b)=>a+b,0)-s.rhs)/Math.max(1,Math.abs(s.rhs),...terms.map(Math.abs));ok(res<1e-11,'point satisfies conic');maxResidual=Math.max(maxResidual,res);}ok(JSON.parse(JSON.stringify(d)).section.kind===d.section.kind,'serializable');}
ok(kinds.size===10,'all ten conic kinds covered');
for(const model of m.MODELS)for(const axis of [0,1,2])for(const angle of [-60,-25,0,25,60]){const d=m.analyze({modelId:model.id,axis,angle,slice:.5}),p=[.7,-.4],world=m.sectionPoint(d,p),coords=m.projectSectionPoint(d,p);near(coords[0],p[0]);near(coords[1],p[1]);near(world.reduce((s,x,i)=>s+x*d.worldPlaneNormal[i],0),d.worldPlaneConstant);for(let i=0;i<3;i++)for(let j=0;j<3;j++)near(d.principalAxes[i].reduce((s,x,k)=>s+x*d.principalAxes[j][k],0),i===j?1:0);ok(d.hasCenter===!['paraboloid','saddle','parabolic-cylinder'].includes(model.id),'center condition');const base=m.analyze({modelId:model.id,axis,angle:0,slice:.5});ok(JSON.stringify(m.sectionCurve(base))===JSON.stringify(m.sectionCurve(d)),'co-rotating intrinsic contour invariant');}
const symbolic=m.analyze({modelId:'ellipsoid',axis:2,slicePreset:'positive-tangent'});ok(symbolic.section.kind==='point'&&symbolic.rhs===0,'symbolic exact tangent');ok(m.analyze({modelId:'ellipsoid',axis:2,slice:1/Math.sqrt(3)}).section.kind==='empty','numeric input separate from symbolic tangent');
for(const bad of [null,[],{modelId:''},{axis:'1'},{axis:null},{slice:'1'},{slice:NaN},{slice:4.1},{angle:Infinity},{angle:361},{slicePreset:'bad'},{modelId:'cone',slicePreset:'positive-tangent'},{axis:0,slicePreset:'positive-tangent'}]){checks++;assert.throws(()=>m.analyze(bad));}
for(const bad of [[1,2,0,0,NaN],[1,2,0,0,Infinity],['1',2,0,0,1]]){checks++;assert.throws(()=>m.sectionKind(...bad));}
for(const n of [0,1,10,100])ok(m.formatNumber(n,0)===String(n),'integer display');ok(m.formatNumber(1e-12)!=='0','small display');
// The old parabola sampler omitted the linear term along the quadratic axis.
for(const s of [m.sectionKind(2,0,3,-1,4),m.sectionKind(0,2,-1,3,4)])for(const p of m.sectionCurve({section:s})){if(p)near(s.a*p[0]**2+s.b*p[1]**2+s.l1*p[0]+s.l2*p[1],s.rhs);}
class Node{constructor(t){this.tag=t;this.attrs={};this.children=[];}setAttribute(k,v){this.attrs[k]=String(v)}appendChild(n){this.children.push(n);return n}}
const doc={createElementNS(ns,t){return new Node(t)}};for(const model of m.MODELS)for(const axis of [0,1,2]){const d=m.analyze({modelId:model.id,axis,slice:0}),s=m.contourSvg(doc,d,'test'),g=s.children.find(x=>x.tag==='g'),clip=s.children.find(x=>x.tag==='defs').children[0].children[0];ok(g.attrs['clip-path']==='url(#test-clip)','clipping used');ok(+clip.attrs.width===480&&+clip.attrs.height===480,'same scale');ok(s.children.filter(x=>x.tag==='text').some(x=>String(x.textContent).includes('X=')),'coordinate names');}
const figure=require('./fixtures/quadric-figure-points.json'),svg=fs.readFileSync(path.join(root,'math-course/images/geo-02-quadrics.svg'),'utf8');ok(figure.length===198,'six surfaces recorded');for(const row of figure){const tag=svg.match(new RegExp('<path data-quadric="'+row.id+'"[^>]+>'))[0],d=tag.match(/ d="([^"]+)"/)[1],screen=[...d.matchAll(/[ML]([-\d.]+),([-\d.]+)/g)];ok(screen.length===row.points.length,'static sample count');row.points.forEach(([u,v,w],i)=>{const eq=[u*u+2*v*v+3*w*w-1,u*u+v*v-w*w-1,u*u-v*v-w*w-1,u*u+v*v-w,u*u-v*v-w,u*u+v*v-w*w][row.panel];ok(Math.abs(eq)<5e-14,'static point on surface');const x=200+400*(row.panel%3)+60*Math.sqrt(3)/2*(u-v),y=260+440*Math.floor(row.panel/3)+60*((u+v)/2-w);ok(Math.abs(+screen[i][1]-x)<5.1e-8&&Math.abs(+screen[i][2]-y)<5.1e-8,'static projection');if(row.role==='slice'){const actual=row.panel===2?u:w,allowed=[[0],[-1,0,1],[-1.3,1.3],[1],[0],[-1,1]][row.panel];ok(allowed.some(s=>Math.abs(actual-s)<1e-14),'static highlighted slice');}});}
console.log('quadric sections independent: PASS',{checks,maxResidual,kinds:[...kinds]});
