'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path'),lab=require('../course-shared/labs/logistic-chaos.js'),ref=require('./fixtures/logistic-reference.json');let checks=0;
function check(v,m){checks++;assert(v,m)}function close(a,b,m,t=1e-10){check(Math.abs(a-b)<=t*Math.max(1,Math.abs(b)),m+': '+a+' vs '+b)}
// A priori Lipschitz recurrence for accumulated floating-point roundoff.
for(const r of ref.orbits){const xs=lab.iterate(r.r,r.x0,20);let bound=0;for(let n=0;n<xs.length;n++){close(xs[n],r.values[n],'100-digit real recurrence, forward error bound',bound+Number.EPSILON);bound=r.r*bound+4*Number.EPSILON;}}
for(let i=0;i<=64;i++)for(let j=0;j<=128;j++){const r=i/16,x=j/128,next=lab.logisticMap(r,x);check(next>=0&&next<=1,'interval invariant');close(next,lab.logisticMap(r,1-x),'reflection gives exact real coalescence');const e=(1-x)*.001;close(lab.logisticMap(r,x+e)-next,r*(1-2*x)*e-r*e*e,'finite error has quadratic correction',2e-15);}
for(let j=1;j<=150;j++){const r=3+j/400,disc=Math.sqrt((r-3)*(r+1)),a=(r+1-disc)/(2*r),b=(r+1+disc)/(2*r),m=4+2*r-r*r;close(lab.logisticMap(r,a),b,'analytic cycle lower');close(lab.logisticMap(r,b),a,'analytic cycle upper');close(r*(1-2*a)*r*(1-2*b),m,'cycle multiplier');close(lab.finiteLyapunov(r,a,2,0).lambda,.5*Math.log(Math.abs(m)),'exact cycle exponent',1e-9);}
for(const n of [1,20,160,800]){close(lab.finiteLyapunov(4,.75,n,0).lambda,Math.LN2,'positive exponent on fixed orbit');check(lab.finiteLyapunov(4,.5,n,0).lambda===-Infinity,'initial critical tangent');close(lab.finiteLyapunov(4,.5,n,2).lambda,Math.log(4),'reset tangent after burn');}
for(const r of [0,.1,1,2.8,3.2,3.5,3.83,3.9,4])for(const x of [0,.2,.5,.75,.999,1])for(const burn of [0,40,300])for(const n of [20,160,800]){const c=lab.evaluate({r,x0:x,burnIn:burn,steps:n}),pair=c.separation;check(c.state.x0===x,'never silently change initial x0');check(c.orbit.values.length===n+1,'same finite window for diagnostics');check(c.lyapunov.terms.length===n,'N derivative terms');close(pair.initialDistance,1e-8,'original actual distance',1e-16);check(pair.neighbor0>=0&&pair.neighbor0<=1,'neighbor stays inside');check(pair.direction===(x+1e-8<=1?1:-1),'inward neighbor');for(let k=0;k<=n;k++){close(c.orbit.values[k],pair.series[k].first,'identical burn indexing',0);check(pair.series[k].distance<=1,'finite distance bounded');}const burnValues=lab.iterate(r,x,burn);check(c.orbit.values[0]===burnValues.at(-1),'burn reset position');}
for(const period of [1,2,3,4,8,12]){const v=Array.from({length:80},(_,i)=>(i%period+.5)/period);check(lab.detectPeriod(v,12,1e-8)===period,'all supported periods labeled');check(lab.detectPeriod(v.slice(-period*3),12,1e-8)!==period,'at least four full blocks');const fake=v.slice();fake[0]=.123456;check(lab.detectPeriod(fake,12,1e-8)===0,'entire supplied tail checked');}
check(lab.analyzeOrbit(3.5,.2,160,300).period===4,'period four orbit');check(lab.analyzeOrbit(3.5,.2,160,300).label.includes('周期4'),'period four visible');
for(const key of ['r','x0','burnIn','steps','logDelta'])for(const v of [null,true,'1',NaN,Infinity,-Infinity,1e10]){checks++;assert.throws(()=>lab.evaluate({[key]:v}));}for(const v of [null,[],true,{unknown:1}]){checks++;assert.throws(()=>lab.evaluate(v));}for(const fn of [lab.finiteLyapunov,lab.analyzeOrbit])for(const n of [-1,0,1.5,Infinity,10001]){checks++;assert.throws(()=>fn(3,.2,n,0));}for(const v of [-1,Infinity,'2']){checks++;assert.throws(()=>lab.iterate(3,.2,v));}for(const v of [-1,Infinity,NaN,'0.1']){checks++;assert.throws(()=>lab.simulatePair(3,.2,v,20,0));}check(lab.formatNumber(100,0)==='100','integer zero suffix preserved');check(lab.formatNumber(0,0)==='0','zero printed');
class N{constructor(tag,doc){this.tag=tag;this.ownerDocument=doc;this.attrs={};this.children=[];this.nodeType=1;this.textContent=''}setAttribute(k,v){this.attrs[k]=String(v)}appendChild(n){this.children.push(n);return n}removeChild(n){this.children.splice(this.children.indexOf(n),1)}get firstChild(){return this.children[0]}all(){return this.children.flatMap(n=>[n,...n.all()])}querySelector(t){return this.all().find(n=>n.tag===t)}}
const doc={createElementNS:(_,t)=>new N(t,doc),createElement:t=>new N(t,doc),createTextNode:t=>{const n=new N('#text',doc);n.textContent=String(t);return n}};
for(const r of [0,2.8,3.2,3.5,3.9,4])for(const x of [.2,.5,.75,1]){const c=lab.evaluate({r,x0:x,steps:800,burnIn:0});const a=lab.drawTimeSeries(null,doc,c,'a'),b=lab.drawSeparation(null,doc,c,'b');for(const svg of [a,b])svg.all().forEach(n=>Object.values(n.attrs).forEach(v=>check(!/NaN|Infinity/.test(v),'finite SVG attributes')));const paths=['lc-series-a','lc-series-b'].map(cls=>a.all().find(n=>n.attrs.class===cls));for(let k=0;k<2;k++){const pts=[...paths[k].attrs.d.matchAll(/[ML] ([\d.]+) ([\d.]+)/g)];check(pts.length===801,'no aliasing by decimation');pts.forEach((m,i)=>{close(+m[1],43+i/800*505,'actual every-step x coordinate',.0051);close(+m[2],232-c.separation.series[i][k?'second':'first']*210,'actual orbit y coordinate',.0051);});}const curve=b.all().find(n=>n.attrs.class==='lc-distance'),floor=+curve.attrs['data-log-min'],positive=c.separation.series.filter(p=>p.distance>0),pts=[...curve.attrs.d.matchAll(/[ML] ([\d.]+) ([\d.]+)/g)];check(pts.length===positive.length,'only positive log samples');pts.forEach((m,i)=>{close(+m[1],47+positive[i].n/800*501,'positive x',.0051);close(+m[2],210-(Math.log10(positive[i].distance)-floor)/(0-floor)*180,'unclipped log geometry',.0051)});const zeros=b.all().filter(n=>n.attrs.class==='lc-zero');check(zeros.length===801-positive.length,'zero distance separate rail');zeros.forEach(n=>check(+n.attrs.cy===258,'zero outside finite axis'));}
const svg=fs.readFileSync(path.join(__dirname,'../physics-course/images/fl-05-chaos-lorenz.svg'),'utf8');for(const sign of [-1,1]){const d=svg.match(new RegExp('id="period-two-'+sign+'"[^>]* d="([^"]+)"'))[1];for(const m of d.matchAll(/[ML]([\d.]+),([\d.]+)/g)){const r=2.8+(+m[1]-455)/310*1.2,x=(350-+m[2])/280;close(lab.logisticMap(r,lab.logisticMap(r,x)),x,'static analytic period two',2e-8);}}
const first=svg.match(/id="lorenz-orbit"[^>]* d="M([\d.]+),([\d.]+)/);close((+first[1]-55)/305*44-22,ref.lorenz_t10[0],'independent RK45 versus static DOP853 x',2e-7);close((350-+first[2])/280*50,ref.lorenz_t10[2],'independent Lorenz z',2e-7);
const body=fs.readFileSync(path.join(__dirname,'../physics-course/lectures/fl-05-chaos.md'),'utf8');check(!/[\x00-\x09\x0b\x0c\x0e-\x1f]/.test(body),'no TeX controls');check(!/^\+(?!\+)/m.test(body.replace(/\$\$[\s\S]*?\$\$/g,'')),'no patch residue');for(const line of body.split('\n').filter(l=>l.startsWith('|')&&l.includes('\\log')))check(!line.includes('\\log|'),'table math bars escaped');
console.log(`Logistic chaos: PASS (${checks} independent checks; ${lab.runSelfTest()} self checks)`);
