'use strict';const assert=require('assert'),fs=require('fs'),path=require('path'),m=require('../course-shared/labs/pde-propagation.js'),ref=require('./fixtures/pde-propagation-reference.json');let checks=0,maxRel=0;function check(x,msg){assert(x,msg);checks++}function near(a,b,t=2e-12){check(Number.isFinite(a)&&Math.abs(a-b)<=t*Math.max(1,Math.abs(b)),`${a} vs ${b}`)}
for(const c of ref.heat){const q=m.heatEvaluation(c.x,c.time,c.diffusivity);check(q.converged&&q.evaluations<=5000,'integration converges within work bound');near(q.logValue,c.logValue,3e-13);if(c.value){const rel=Math.abs(q.value/c.value-1);maxRel=Math.max(maxRel,rel);check(rel<2e-11,'90 digit positive heat reference');}else check(q.value===0&&Number.isFinite(q.logValue),'underflow preserves finite logarithm');near(m.heatConvolution(c.x,c.time,c.diffusivity),q.value,0);}
const tent=x=>Math.abs(x)<1?1-Math.abs(x):0;
for(const t of [0,.1,3,8])for(const c of [-2,-.1,0,1,2])for(const a of [.25,1,2.5])for(let j=0;j<=100;j++){const x=-25+j/2;near(m.transportSolution(x,t,c),tent(x-c*t),0);near(m.waveSolution(x,t,a),(tent(x-a*t)+tent(x+a*t))/2,0);}
for(const bad of [null,[],{extra:1},{time:0},{time:.05},{time:9},{time:'3'},{transportSpeed:3},{waveSpeed:0},{diffusivity:0},{xTarget:11},{xTarget:NaN}]){assert.throws(()=>m.evaluate(bad));checks++;}for(const args of [[26,1,1],[0,.01,1],[0,1,0],[0,NaN,1]]){assert.throws(()=>m.heatEvaluation(...args));checks++;}
check(m.waveSolution(0,3,1)===0,'inside outer cone can lie in zero gap');check(m.transportSolution(4,3,1)===0,'support endpoint zero');check(m.heatConvolution(5,.1,.1)>0,'tiny heat is not rounded to zero');
// Independent midpoint integrals: tent mass/variance and Fourier transform.
for(const k of [0,.1,1,2,4,8,20]){const M=20000,dy=2/M;let f=0;for(let j=0;j<M;j++){let y=-1+(j+.5)*dy;f+=tent(y)*Math.cos(k*y)*dy;}near(f,k===0?1:(Math.sin(k/2)/(k/2))**2,3e-9);}
for(const t of [.1,1,8])for(const kap of [.1,1,3]){let mass=0,moment=0;const R=25,M=10000,dx=2*R/M;for(let j=0;j<M;j++){const x=-R+(j+.5)*dx,v=m.heatConvolution(x,t,kap);mass+=v*dx;moment+=v*x*x*dx;} // finite window tail at broadest variance is bounded separately
 if(t*kap<=3){near(mass,1,1e-11);near(moment,1/6+2*t*kap,1e-10);}else{check(mass<=1+1e-12&&mass>.9995,'finite-window mass');check(moment<=1/6+2*t*kap+1e-10,'finite-window second moment');}}
class Node{constructor(tag,attrs={},children=[]){this.tag=tag;this.attrs=attrs;this.children=(children||[]).map(x=>x&&x.nodeType?x:{nodeType:3,text:x});this.nodeType=1;}appendChild(n){this.children.push(n);return n}}
const api={svg:(...a)=>new Node(...a),el:(...a)=>new Node(...a)};function parse(d){const v=d.match(/[-+]?\d*\.?\d+(?:e[-+]?\d+)?/gi).map(Number);return Array.from({length:v.length/2},(_,i)=>[v[2*i],v[2*i+1]]);}
for(const time of [.1,3,8])for(const transportSpeed of [-2,0,2])for(const waveSpeed of [.25,1,2.5])for(const diffusivity of [.1,3]){
 const r=m.evaluate({time,transportSpeed,waveSpeed,diffusivity});for(const model of m.MODELS){const svg=m.drawPropagationChart(api,model,r,'audit'),p=svg.children.find(n=>String(n.attrs.className).startsWith('pde-solution')),ps=parse(p.attrs.d);check(ps.length>=301,'all base samples and exact knots');for(const [px,py]of ps){const x=-7+(px-47)/561*17;let u=model.key==='transport'?tent(x-transportSpeed*time):model.key==='wave'?.5*(tent(x-waveSpeed*time)+tent(x+waveSpeed*time)):m.heatConvolution(x,time,diffusivity);check(Math.abs(py-(222-u/1.05*202))<.04,"actual curve with 0.005px rounding propagated through slope");}if(model.key!=='heat'){const peaks=model.key==='transport'?[transportSpeed*time]:[-waveSpeed*time,waveSpeed*time];for(const x of peaks.filter(x=>x>=-7&&x<=10)){check(ps.some(p=>Math.abs(p[0]-(47+(x+7)/17*561))<=.0051),'exact corner included');}}
 const dot=svg.children.find(n=>n.attrs.className==='pde-target-dot');near(dot.attrs.cy,222-r.point[model.key]/1.05*202);}
 const mode=m.drawModeChart(api,r,'mode'),bars=mode.children.filter(n=>n.tag==='rect'),dots=mode.children.filter(n=>n.tag==='circle'),extent=Math.max(1,Math.ceil(diffusivity*64*time/Math.LN10));check(bars.length===9&&dots.length===9,'both scales show nine frequencies');for(let k=0;k<=8;k++){near(bars[k].attrs.height,174*Math.exp(-diffusivity*k*k*time));near(dots[k].attrs.cy,305+diffusivity*k*k*time/Math.LN10/extent*170);check(Number.isFinite(dots[k].attrs.cy),'finite logarithmic geometry despite linear underflow');}}
const svg=fs.readFileSync(path.join(__dirname,'../math-course/images/pde-02-propagation-footprints.svg'),'utf8'),q=svg.match(/<path id="heat-integrand" d="([^"]+)"/);check(q,'static integrand');const ps=parse(q[1]);check(ps.length===501,'static samples');for(let j=0;j<=500;j++){const y=-1+j/250,v=(1-Math.abs(y))*Math.exp(-((5-y)**2)/12)/Math.sqrt(12*Math.PI);near(ps[j][0],95+770*j/500,1e-9);near(ps[j][1],585-v/.025*150,1e-9);}const cone=parse(svg.match(/<path id="wave-cone" d="([^"]+)"/)[1]);for(const[i,x]of[2,5,8].entries()){near(cone[i][0],530+(x+2)/11*365,1e-9);near(cone[i][1],i===1?95:295,1e-9);}check(svg.includes('0.02116395'),'static observed heat rounds reference');console.log(`pde-propagation independent: PASS (${checks} checks; max heat relative error ${maxRel})`);
