"use strict";
const assert=require('assert'),fs=require('fs'),path=require('path'),m=require('../course-shared/labs/complex-analytic.js');let checks=0;function check(v,msg){assert(v,msg);checks++;}function near(a,b,t=2e-12){check(Math.abs(a-b)<=t*Math.max(1,Math.abs(b)),`${a} != ${b}`);}
function f(id,x,y,l){if(id==='z2')return[x*x-y*y,2*x*y];if(id==='conjugate')return[x,-y];if(id==='modulus2')return[x*x+y*y,0];return[x*x-y*y+l*(x*x+y*y),2*x*y];}
for(let ix=-4;ix<=4;ix++)for(let iy=-4;iy<=4;iy++)for(let il=-10;il<=10;il++)for(const item of m.FUNCTIONS){let x=ix/2,y=iy/2,l=il/10,z=m.evaluate({functionId:item.id,x,y,lambda:l}).selected;let base=f(item.id,x,y,l);near(z.u,base[0]);near(z.v,base[1]);for(const w of [[1,0],[0,1],[1,1],[.3,-.7]]){let h=.001,a=f(item.id,x+h*w[0],y+h*w[1],l),b=f(item.id,x-h*w[0],y-h*w[1],l),v=[(a[0]-b[0])/(2*h),(a[1]-b[1])/(2*h)],den=w[0]**2+w[1]**2,q=[(v[0]*w[0]+v[1]*w[1])/den,(v[1]*w[0]-v[0]*w[1])/den],actual=m.directionalQuotient(z,w);near(actual[0],q[0],2e-11);near(actual[1],q[1],2e-11);}const origin=ix===0&&iy===0,analytic=item.id==='z2'||item.id==='parameterized'&&il===0;check(z.analyticNeighborhood===analytic,'neighborhood');check(z.complexDifferentiable===(analytic||(item.id==='modulus2'||item.id==='parameterized')&&origin),'point classification');near(z.alpha[0]+z.beta[0],z.ux);near(z.alpha[1]+z.beta[1],z.vx);near(-z.alpha[1]+z.beta[1],z.uy);near(z.alpha[0]-z.beta[0],z.vy);}
for(const l of [1e-12,1e-17,1e-100,1e-300,Number.MIN_VALUE]){let z=m.evaluate({functionId:'parameterized',lambda:l}).selected;check(!z.complexDifferentiable&&!z.analyticNeighborhood,'tiny nonzero still not differentiable');check(z.beta[0]===l&&z.beta[1]===l,'preserve tiny beta');check(z.residual[0]===2*l&&z.residual[1]===2*l,'no subtractive residual');check(m.formatComplex(z.beta)!=='0','tiny display');}
check(m.evaluate({functionId:'parameterized',x:.1,y:0,lambda:Number.MIN_VALUE}).selected.betaUnderflow,'underflow disclosed');
const z=m.evaluate().selected;for(const a of [1e-300,1e300]){const q=m.directionalQuotient(z,[a,a]);near(q[0],2);near(q[1],2);}
for(const bad of [null,[],false,{lambda:9},{lambda:'0'},{x:Infinity},{x:3},{functionId:'typo'},{pointId:'typo'},{typo:1}]){assert.throws(()=>m.evaluate(bad));checks++;}
assert.throws(()=>m.directionalQuotient(z,[0,0]));checks++;
// All fixed line slopes vs a curved path for F(z)/z=H(x,y).
for(let a=-7;a<=7;a++)for(let b=-7;b<=7;b++){if(a===0&&b===0)continue;let t=1e-7,x=a*t,y=b*t,H=x*x*y/(x**4+y*y);near(H,b===0?0:a*a*b*t/(a**4*t*t+b*b));check(Math.abs(H)<1e-4,'fixed line tends to zero');}
for(const x of [.1,.01,.001])near(x*x*x*x/(x**4+x**4),.5);
let period=0;const N=10000;for(let i=0;i<N;i++){let t=(i+.5)*2*Math.PI/N,x=Math.cos(t),y=Math.sin(t);period+=((-y)*(-Math.sin(t))+x*Math.cos(t))*2*Math.PI/N;}near(period,2*Math.PI,2e-12);
class Node{constructor(tag){this.tag=tag;this.attrs={};this.children=[];this.nodeType=1;}setAttribute(k,v){this.attrs[k]=String(v);}appendChild(n){this.children.push(n);return n;}get firstChild(){return this.children[0];}removeChild(n){this.children.splice(this.children.indexOf(n),1);}}
const doc={createElementNS:(ns,t)=>new Node(t),createTextNode:t=>({nodeType:3,text:t})};for(const id of m.FUNCTIONS.map(x=>x.id))for(const pt of ['origin','generic','axis'])for(const l of [-1,0,.5,1,1e-12]){let row=m.evaluate({functionId:id,pointId:pt,lambda:l}).selected,svg=new Node('svg');m.drawProbeSvg(doc,svg,row);for(const e of svg.children){for(const k of ['x','y','x1','y1','x2','y2','cx','cy'])if(k in e.attrs)check(Number.isFinite(+e.attrs[k]),'finite svg');}const dots=svg.children.filter(e=>e.tag==='circle'&&e.attrs.class==='ca-probe');check(dots.length>=2&&dots.length<=6,'grouping');let extent=1.25*Math.max(1,...row.probes.flatMap(p=>p.quotient).map(Math.abs));for(const q of row.probes.map(p=>p.quotient)){let x=200+q[0]/extent*125,y=200-q[1]/extent*125;check(dots.some(d=>Math.hypot(+d.attrs.cx-x,+d.attrs.cy-y)<.015),'actual left quotient');}let r=Math.hypot(...row.beta),e=r===0?1:1.25*r;for(const [re,im]of [[1,0],[-1,0],[0,-1]]){let x=565+(row.beta[0]*re-row.beta[1]*im)/e*125,y=200-(row.beta[0]*im+row.beta[1]*re)/e*125;check(dots.some(d=>Math.hypot(+d.attrs.cx-x,+d.attrs.cy-y)<.015),'actual separated beta');}}
const svg=fs.readFileSync(path.join(__dirname,'../math-course/images/complex-01-conformal.svg'),'utf8');function pts(id){let a=svg.match(new RegExp('<path id="'+id+'" d="([^"]+)"'));check(!!a,id);return [...a[1].matchAll(/[ML]([\d.]+),([\d.]+)/g)].map(p=>[+p[1],+p[2]]);}
for(let k=0;k<5;k++)for(const dir of ['x','y']){let input=pts('input-'+dir+k),image=pts('image-'+dir+k);check(input.length===101&&image.length===101,'grid counts');for(let i=0;i<101;i++){let x=dir==='x'?.5+k*.25:.5+i/100,y=dir==='x'?-.5+i/100:-.5+k*.25;near(input[i][0],75+140*x,1e-9);near(input[i][1],365-140*(y+1),1e-9);near(image[i][0],535+80*(x*x-y*y+.5),1e-9);near(image[i][1],365-80*(2*x*y+1.75),1e-9);}}
const tangents=[pts('tangent-image0'),pts('tangent-image1')].map(a=>[a[1][0]-a[0][0],a[1][1]-a[0][1]]);near(tangents[0][0]*tangents[1][0]+tangents[0][1]*tangents[1][1],0,1e-8);
console.log(`complex-analytic independent: PASS (${checks} checks)`);
