'use strict';const assert=require('assert'),fs=require('fs'),path=require('path'),root=path.resolve(__dirname,'..'),m=require(path.join(root,'course-shared/labs/confidence-intervals.js')),ref=require('./fixtures/confidence-reference.json');let checks=0,maxQuantile=0,maxCoverage=0;
function ok(v,msg){checks++;assert(v,msg);}function near(x,y,t=2e-10){ok(Number.isFinite(x)&&Math.abs(x-y)<=t*Math.max(1,Math.abs(y)),`${x} != ${y}`);}
for(const r of ref.critical){const z=m.zCritical(r.c),t=m.tCritical(r.c,r.df);near(z,r.z,2e-15);near(t,r.t,3e-10);maxQuantile=Math.max(maxQuantile,Math.abs(t-r.t));near(m.studentTCdf(t,r.df),(1+r.c)/2,2e-13);near(m.studentTCdf(-t,r.df),(1-r.c)/2,2e-13);}
for(const r of ref.selection){const e=m.selectionTheory(r.c,r.n);near(e.coverage,r.coverage,2e-10);near(e.selectT,r.selectT,3e-10);maxCoverage=Math.max(maxCoverage,Math.abs(e.coverage-r.coverage));ok(e.coverage<r.c&&e.coverage>2*r.c-1,'intersection coverage bounds');}
for(const r of ref.samples){for(const variance of ['known','unknown']){const i=m.intervalFromSample(r.values,{confidence:.95,sigma:8},variance);near(i.center,r.center);near(i.standardDeviation,r.sd);near(i.margin,r[variance==='known'?'z':'t']);}const i=m.chooseInterval(r.values,{confidence:.95,sigma:8,rule:'selected',variance:'known'});near(i.margin,r.selected);ok(i!==i.candidates.z&&i!==i.candidates.t,'non-cyclic candidates');ok(JSON.parse(JSON.stringify(i)).candidates.z.lower===i.candidates.z.lower,'serializable');}
for(const n of [2,4,10,16,30,60])for(const confidence of [.9,.95,.99])for(const variance of ['known','unknown'])for(const rule of ['preplanned','selected']){if(variance==='unknown'&&rule==='selected')continue;for(const seed of [0,20260822,4294967295]){const config={n,confidence,variance,rule,seed},large=m.simulate({...config,repetitions:180}),small=m.simulate({...config,repetitions:40});ok(JSON.stringify(large.intervals.slice(0,40))===JSON.stringify(small.intervals),'repetitions preserve sample prefix');ok(JSON.stringify(large.observed)===JSON.stringify(small.observed),'fixed observed sample');let covered=0,zCount=0;for(const i of large.intervals){const hit=i.lower<=500&&500<=i.upper;ok(i.covered===hit,'exact coverage membership');covered+=hit;near(i.lower,i.center-i.margin);near(i.upper,i.center+i.margin);if(rule==='selected'){ok(i.margin<=i.candidates.z.margin&&i.margin<=i.candidates.t.margin,'intersection');zCount+=i.candidates.z.margin<=i.candidates.t.margin;}}ok(covered===large.coverageCount,'complete ledger');near(large.coverage,covered/180);if(rule==='selected')ok(zCount===large.selectedZ&&180-zCount===large.selectedT,'selection counts');else ok(large.selectedZ===null&&large.selectedT===null,'no fake selection counts');}}
for(const bad of [null,[],{n:1},{n:61},{n:3.5},{n:'16'},{sigma:0},{sigma:NaN},{confidence:'0.95'},{confidence:.8},{variance:'typo'},{rule:'typo'},{seed:-1},{seed:1.2},{repetitions:39},{variance:'unknown',rule:'selected'}]){checks++;assert.throws(()=>m.simulate(bad));}
for(const bad of [[],[1],[1,NaN],[1,Infinity],['1',2]]){checks++;assert.throws(()=>m.sampleStd(bad));}
near(m.sampleStd([1e308,1e308]),0);near(m.studentTCdf(Infinity,3),1);near(m.studentTCdf(-Infinity,3),0);for(const v of [1,-.1,NaN]){checks++;assert.throws(()=>m.gaussian(()=>v));}near(m.gaussian(()=>0),0);
for(const n of [0,1,10,16,40,100,180,500,1000])ok(m.format(n,0)===String(n),'integers keep trailing zero');ok(m.format(10.50,2)==='10.5','decimal trim only');
class Node{constructor(tag,doc){this.tag=tag;this.nodeType=1;this.ownerDocument=doc;this.attrs={};this.children=[];}setAttribute(k,v){this.attrs[k]=String(v)}appendChild(n){this.children.push(n);return n;}}
const doc={createElementNS(ns,t){return new Node(t,this)},createTextNode(t){return{nodeType:3,text:t}}};
for(const n of [2,16,60])for(const c of [.9,.95,.99])for(const rule of ['preplanned','selected']){const r=m.simulate({n,confidence:c,variance:'known',rule}),svg=m.chart(null,doc,r,'check'),shown=r.intervals.slice(0,22),all=[500,...shown.flatMap(i=>[i.lower,i.upper])];let min=Math.min(...all),max=Math.max(...all),pad=Math.max(1,(max-min)*.1);min-=pad;max+=pad;const lines=svg.children.filter(x=>(x.attrs.class||'').startsWith('ci-interval '));ok(lines.length===22,'only first22 clearly indicated');lines.forEach((line,i)=>{near(+line.attrs.x1,58+(shown[i].lower-min)/(max-min)*650);near(+line.attrs.x2,58+(shown[i].upper-min)/(max-min)*650);near(+line.attrs.y1,62+(i+1)/23*440);ok(line.attrs.class.includes(shown[i].covered?'ci-covered':'ci-missed'),'actual line encodes coverage');});}
const svg=fs.readFileSync(path.join(root,'math-course/images/stat-03-confidence.svg'),'utf8'),sample=ref.samples,xmin=Math.min(...sample.map(r=>r.center-Math.max(r.z,r.t)))-1,xmax=Math.max(...sample.map(r=>r.center+Math.max(r.z,r.t)))+1;
for(const [panel,key]of ['z','t','selected'].entries())sample.forEach((r,i)=>{const tag=svg.match(new RegExp('<path data-interval="'+key+'-'+i+'"[^>]*/>'))[0],d=tag.match(/d="M([-\d.]+),([-\d.]+)H([-\d.]+)"/),left=65+350*panel;ok(Math.abs(+d[1]-(left+285*(r.center-r[key]-xmin)/(xmax-xmin)))<5.1e-8,'static interval left');ok(Math.abs(+d[3]-(left+285*(r.center+r[key]-xmin)/(xmax-xmin)))<5.1e-8,'static interval right');near(+d[2],120+16*i);const covered=r.center-r[key]<=500&&500<=r.center+r[key];ok(tag.includes(covered?'#39734d':'#b64335'),'static coverage truthful');});
const curve=svg.match(/<path data-coverage="selected" d="([^"]+)"/)[1],ps=[...curve.matchAll(/[ML]([-\d.e]+),([-\d.e]+)/g)].map(r=>[+r[1],+r[2]]),rs=ref.selection.filter(r=>r.c===.95);ok(ps.length===59,'static theoretical coverage all n');ps.forEach(([x,y],i)=>{ok(Math.abs(x-(80+900*(rs[i].n-2)/58))<5.1e-8,'static coverage x');ok(Math.abs(y-(820-170*(rs[i].coverage-.9)/.06))<5.1e-8,'static coverage y');});console.log('confidence intervals independent: PASS',{checks,maxQuantile,maxCoverage});

for(const scale of [1e-300,1e-200,1,1e200,1e308]){const expected=Math.SQRT2*scale,actual=m.sampleStd([scale,-scale]);ok(Number.isFinite(actual)&&Math.abs(actual/expected-1)<5e-15,'scaled standard deviation');}
const huge=m.intervalFromSample(Array.from({length:60},(_,i)=>i%2?1e308:-1e308),{},'unknown');ok(Number.isFinite(huge.margin)&&huge.margin>0,'representable margin avoids intermediate overflow');
console.log('scale regression: PASS');

const maxSample=Array.from({length:60},(_,i)=>i%2?Number.MAX_VALUE:-Number.MAX_VALUE),maxInterval=m.intervalFromSample(maxSample,{},'unknown');ok(maxInterval.standardDeviation===Infinity&&Number.isFinite(maxInterval.margin),'finite interval even when standard deviation exceeds range');
ok(m.sampleStd([Number.MIN_VALUE,-Number.MIN_VALUE])===Number.MIN_VALUE,'subnormal std rounds without premature zero');
console.log('standard error range regression: PASS');
