'use strict';const assert=require('assert'),fs=require('fs'),path=require('path'),root=path.resolve(__dirname,'..'),m=require(path.join(root,'course-shared/labs/vectors-planes.js')),ref=require('./fixtures/vectors-reference.json');let checks=0,maxRelative=0;
function ok(v,msg){checks++;assert(v,msg)}
function near(a,b){const tol=Math.max(Number.MIN_VALUE*2,Math.abs(b)*8e-15);ok(Number.isFinite(a)&&Math.abs(a-b)<=tol,`${a} != ${b}`);if(b!==0&&Math.abs(b)>1e-300)maxRelative=Math.max(maxRelative,Math.abs((a-b)/b));}
function vector(a,b){ok(Array.isArray(a)&&a.length===3,'vector');a.forEach((x,i)=>near(x,b[i]));}
for(const {input,expected:e} of ref.lines){const a=m.linePlane(input);ok(a.relation===e.relation,'line relation');for(const key of ['denominatorNonzero','offsetNonzero'])if(key in e)ok(a[key]===e[key],key);if(e.relation==='intersect'){if(e.parameter===null)ok(a.parameterUnrepresentable===true,'parameter range');else near(a.parameter,e.parameter);if(e.intersection.includes(null))ok(a.intersectionUnrepresentable===true,'intersection range');else vector(a.intersection,e.intersection);}}
for(const {input,expected:e} of ref.planes){const a=m.planePlane(input);ok(a.relation===e.relation,'plane relation');if(e.relation==='intersect'){if(e.intersectionPoint.includes(null))ok(a.intersectionUnrepresentable===true,'point range');else vector(a.intersectionPoint,e.intersectionPoint);vector(a.intersectionDirection,e.intersectionDirection);near(Math.hypot(...a.intersectionDirection),1);}}
for(const fn of [m.linePlane,m.planePlane,m.analyze])for(const value of [null,[],3,'x']){checks++;assert.throws(()=>fn(value));}
for(const key of ['normal','point','planePoint','direction'])for(const value of [null,[],[1,2],['1',0,0],[null,0,1],[1,Infinity,0]]){checks++;assert.throws(()=>m.linePlane({[key]:value}));}
for(const bad of [{mode:''},{scenario:''},{offset:null},{tilt:'1'},{offset:2.1},{tilt:-2.1}]){checks++;assert.throws(()=>m.analyze(bad));}
for(const n of [0,1,10,100])ok(m.formatNumber(n,0)===String(n),'integer display');ok(m.formatNumber(1e-12)!=='0','tiny nonzero');
class Node{constructor(tag,doc){this.tag=tag;this.nodeType=1;this.ownerDocument=doc;this.attrs={};this.children=[];this.textContent='';}setAttribute(k,v){this.attrs[k]=String(v)}appendChild(n){this.children.push(n);return n;}}
const doc={createElementNS(ns,t){return new Node(t,this)}};
for(const mode of ['line-plane','plane-plane'])for(const scenario of mode==='line-plane'?['cross','parallel','contained','zero-direction','zero-normal']:['cross','coincident','parallel','zero-normal'])for(let i=-8;i<=8;i++)for(let j=-8;j<=8;j++){
 const a=m.analyze({mode,scenario,offset:i/4,tilt:j/4}),svg=(mode==='line-plane'?m.linePlaneSvg:m.planePlaneSvg)(doc,a,'check');ok(a.offsetParameter===i/4,'actual offset');
 const lines=svg.children.filter(x=>x.attrs['data-geometry']);for(const l of lines){const q=[(+l.attrs.x1-70)/70-3,3-(+l.attrs.y1-60)/70],p=[(+l.attrs.x2-70)/70-3,3-(+l.attrs.y2-60)/70];for(const v of [q,p]){ok(v[0]>=-3-1e-13&&v[0]<=5+1e-13&&v[1]>=-3-1e-13&&v[1]<=3+1e-13,'clipped');let residual;if(l.attrs['data-geometry']==='plane1')residual=v[1];else if(mode==='line-plane')residual=(v[0]-a.point[0])*a.direction[2]-(v[1]-a.point[2])*a.direction[0];else residual=a.normal2[0]*v[0]+a.normal2[2]*v[1]-a.constant2;ok(Math.abs(residual)<1e-12,'line equation');}}
 if(scenario==='zero-normal')ok(!lines.some(l=>l.attrs['data-geometry']===(mode==='line-plane'?'plane1':'plane2')),'no fake degenerate plane');
 if(scenario==='zero-direction')ok(!lines.some(l=>l.attrs['data-geometry']==='line'),'no fake direction');
 const point=mode==='line-plane'?a.intersection:a.intersectionPoint,visible=!!(point&&point[0]>=-3&&point[0]<=5&&point[2]>=-3&&point[2]<=3);ok(svg.children.some(n=>n.attrs['data-intersection'])===visible,'intersection visibility');
}
const far=m.analyze({mode:'line-plane',scenario:'cross',offset:1,tilt:1e-12}),farSvg=m.linePlaneSvg(doc,far,'far');ok(far.relation==='intersect'&&far.conditionWarning,'near parallel remains intersecting');ok(farSvg.children.some(n=>n.textContent.includes('视窗外')),'offscreen explanation');
const svg=fs.readFileSync(path.join(root,'math-course/images/geo-01-projection.svg'),'utf8'),curve=svg.match(/data-curve="intersection" d="([^"]+)"/)[1],points=[...curve.matchAll(/[ML]([-\d.]+),([-\d.]+)/g)];ok(points.length===601,'analytic samples');points.forEach((p,i)=>{const k=.1+1.9*i/600;ok(Math.abs(+p[1]-(605+400*(k-.1)/1.9))<5.1e-8,'static k');ok(Math.abs(+p[2]-(470-340*(1-1/k+10)/11))<5.1e-8,'static intersection');});
for(const [key,r] of [['M',2*Math.sqrt(3)],['H',Math.sqrt(3)]]){const p=svg.match(new RegExp('data-point="'+key+'" cx="([^"]+)" cy="([^"]+)"'));ok(Math.abs(+p[1]-(80+85/Math.sqrt(2)))<5.1e-8,'projection x');ok(Math.abs(+p[2]-(470-85*r))<5.1e-8,'projection height');}
console.log('vectors planes independent: PASS',{checks,maxRelative});
