"use strict";
const assert=require('assert'),fs=require('fs'),path=require('path'),lab=require('../course-shared/labs/continuum-conservation.js');let checks=0;
function check(v,m){checks++;assert(v,m)}function close(a,b,m,t=1e-10){check(Math.abs(a-b)<=t*Math.max(1,Math.abs(b)),m+': '+a+' vs '+b)}
function node(tag,doc){return{nodeType:1,tag,ownerDocument:doc,attrs:{},children:[],setAttribute(k,v){this.attrs[k]=v},appendChild(c){this.children.push(c)}}}const doc={createElementNS(ns,tag){return node(tag,this)},createTextNode(t){return{nodeType:3,text:t}}};function all(n,key){return(n.attrs&&Object.hasOwn(n.attrs,key)?[n]:[]).concat(...(n.children||[]).map(c=>all(c,key)));}
const A=x=>1-.45*Math.exp(-(((x-.5)/.22)**2)),rho=(m,x)=>m==='constant'?1:1+.2*x,U=(m,x)=>1/(rho(m,x)*A(x));
function derivative(f,x,h=1e-4){return(f(x-2*h)-8*f(x-h)+8*f(x+h)-f(x+2*h))/(12*h)}
function simpson(f,a,b,n=256){let s=f(a)+f(b);for(let i=1;i<n;i++)s+=(i%2?4:2)*f(a+(b-a)*i/n);return s*(b-a)/n/3}
for(const mode of ['constant','variable']){
 for(let i=1;i<1000;i++){const x=i/1000;close(lab.areaDerivative(x),derivative(A,x),'independent area derivative',1e-8);close(lab.velocityDerivative(mode,x,1),derivative(y=>U(mode,y),x),'independent velocity derivative',1e-8);const div=derivative(y=>A(y)*U(mode,y),x)/A(x);close(lab.quasiOneDDivergence(mode,x,1),div,'flux derivative divergence',1e-8);close(lab.materialDerivativeDensity(mode,x,1),U(mode,x)*(mode==='constant'?0:.2),'density material rate');close(lab.continuityResidual(mode,x,1),0,'continuity');}
 for(let samples=9;samples<=41;samples++){const d=lab.compute({densityMode:mode,samples}),svg=lab.drawSvg(doc,d,'test');close(d.throat.x,.5,'throat exact even with even grid');close(d.throat.velocity,U(mode,.5),'throat value');check(d.field.length===samples,'sample number');const curves=all(svg,'data-field');check(curves.length===3,'three independent axes');curves.forEach((c,j)=>{const key=c.attrs['data-field'],max=j===1?2:1.25,bottom=175+185*j,pts=[...c.attrs.d.matchAll(/[ML]([\d.e+-]+) ([\d.e+-]+)/g)];check(pts.length===samples,'actual plotted sampling');pts.forEach((p,i)=>{const x=i/(samples-1),v=key==='area'?A(x):key==='rho'?rho(mode,x):U(mode,x);close((+p[1]-50)/290,x,'graph x');close((bottom-+p[2])/110*max,v,'graph real y');});});}
 for(let i=1;i<=16;i++)for(let j=4;j<=19;j++)if(j>i){const x0=i/20,x1=j/20,d=lab.compute({densityMode:mode,x0,x1}),l=d.ledger,pressure=(1.4-.3*x0)*A(x0)-(1.4-.3*x1)*A(x1),change=U(mode,x1)-U(mode,x0);close(l.massIn,1,'mass in');close(l.massOut,1,'mass out');close(l.momentumChange,change,'momentum flux difference');close(l.pressureForce,pressure,'pressure end forces');close(l.wallForce,change-pressure,'required wall force');close(l.momentumResidual,0,'constructed momentum residual');const svg=lab.drawSvg(doc,d,'ledger'),bars=all(svg,'data-bar');const values=[U(mode,x0),U(mode,x1),change,pressure,change-pressure];bars.forEach((bar,k)=>{const value=values[k];close(+bar.attrs.height,Math.abs(value)*70,'signed bar height');close(+bar.attrs.y,350-Math.max(value,0)*70,'signed bar top');check(+bar.attrs.y>=210&&+bar.attrs.y+ +bar.attrs.height<=490,'signed bar inside fixed axis');if(value< -1e-12)check(+bar.attrs.y===350&&+bar.attrs.height>0,'negative bar below zero');});all(svg,'data-endpoint').forEach(e=>{const k=+e.attrs['data-endpoint'].split(':')[1];close((+e.attrs.x1-50)/290,k?x1:x0,'CV marker input sync');});}
}
// Independent boundary stresses for uniform pressure on the equivalent unit-width nozzle.
for(const [x0,x1] of [[.1,.5],[.2,.8],[.5,.9]])for(const c of [-2,.5,3]){const side=c*simpson(x=>derivative(A,x),x0,x1),ends=c*(A(x0)-A(x1));close(side+ends,0,'uniform pressure closed boundary cancellation',1e-8)}
const symmetric=lab.compute().ledger;close(symmetric.momentumChange,0,'symmetric momentum');check(symmetric.wallForce<0,'symmetric wall force negative');
// Exact shear solution: independent central derivatives and period averages.
for(const nu of [.01,.1,1])for(const k of [1,2,4])for(const t of [0,.5,2]){const amp=2*Math.exp(-nu*k*k*t),u=y=>amp*Math.sin(k*y);for(const y of [.2,.7,1.3]){const lap=(u(y+.0001)-2*u(y)+u(y-.0001))/.0001**2;close(-nu*k*k*u(y),nu*lap,'shear solves diffusion',1e-6)}const E=simpson(y=>u(y)**2/2,0,2*Math.PI)/(2*Math.PI),diss=nu*simpson(y=>(amp*k*Math.cos(k*y))**2,0,2*Math.PI)/(2*Math.PI);close(E,amp**2/4,'exact energy average');close(diss,2*nu*k*k*E,'energy dissipation balance')}
for(const input of [null,[],1,'constant',{densityMode:'bad'},{samples:8},{samples:42},{samples:9.5},{samples:'21'},{x0:0},{x0:.81},{x1:.1},{x1:1},{x0:.7,x1:.6},{x0:.5,x1:.5},{massFlow:2},{massFlow:null}]){checks++;assert.throws(()=>lab.compute(input))}for(const fn of [()=>lab.area(NaN),()=>lab.area(2),()=>lab.density('wrong',.5),()=>lab.density('constant','0.5'),()=>lab.velocity('constant',.5,Infinity),()=>lab.velocity('constant',.5,'1')]){checks++;assert.throws(fn)}check(lab.format(100,0)==='100','integer zeros');check(lab.format(1e-12)!=='0','nonzero residual shown');
const lecture=fs.readFileSync(path.join(__dirname,'../physics-course/lectures/fl-01-continuum.md'),'utf8');check(!/[\x00-\x09\x0b\x0c\x0e-\x1f]/.test(lecture),'TeX control integrity');check(!/^\+(?:$|\*\*)/m.test(lecture),'patch residue');for(const m of lecture.replace(/\$\$[\s\S]*?\$\$/g,'').matchAll(/(?<![\\$])\$(?!\$)([\s\S]*?)(?<!\\)\$(?!\$)/g))check(!m[1].includes('\n'),'inline TeX intact');check(/<\/div>\s*### 5/.test(lecture),'boundary outside lab');
const svg=fs.readFileSync(path.join(__dirname,'../physics-course/images/fl-01-continuum-re.svg'),'utf8');for(const sign of [-1,1]){const d=svg.match(new RegExp('data-wall="'+sign+'" d="([^"]+)"'))[1],pts=[...d.matchAll(/([\d.]+),([\d.]+)/g)];check(pts.length===129,'wall samples');pts.forEach((p,i)=>{close(+p[1],70+760*i/128,'wall x',1e-7);close((+p[2]-180)/80,sign*A(i/128),'wall equivalent half area',1e-7)})}for(const [name,sign]of [['pressure',1],['wall',-1]]){const line=svg.match(new RegExp('<line[^>]+data-force="'+name+'"[^>]*/>'))[0],x1=+line.match(/x1="([\d.]+)"/)[1],x2=+line.match(/x2="([\d.]+)"/)[1];close((x2-x1)/1000,sign*.18*A(.2),'static force magnitude and direction')}
console.log(`continuum conservation: PASS (${checks} independent checks; ${lab.selfTest().checks} self checks)`);
