'use strict';
const assert=require('assert'),g=require('../course-shared/labs/graph-certificates'),f=require('../course-shared/labs/max-flow-min-cut');let checks=0;
function eq(a,b){assert.deepStrictEqual(a,b);checks++;}function near(a,b,scale=1){assert(Number.isFinite(a)&&Number.isFinite(b)&&Math.abs(a-b)<=1e-12*scale,`${a} != ${b}`);checks++;}
// Independent subset DP for Hamilton cycles, and NetworkX's left-right planarity algorithm.
function hamilton(a){const n=a.length;if(n<3)return false;const dp=Array.from({length:1<<n},()=>Array(n).fill(false));dp[1][0]=true;for(let mask=1;mask<1<<n;mask++)for(let u=0;u<n;u++)if(dp[mask][u])for(let v=1;v<n;v++)if(!(mask>>v&1)&&a[u][v])dp[mask|1<<v][v]=true;return dp[(1<<n)-1].some((v,i)=>v&&a[i][0]===1);}
for(const c of require('./fixtures/graph-networkx.json').cases){const r=g.analyzeGraph(c.matrix);eq(r.planarity.planar,c.planar);eq(r.bipartite,c.bipartite);eq(r.components.length,c.components);eq(r.tree.isTree,c.tree);eq(r.hamiltonian.exists,hamilton(c.matrix));eq(r.degreeSum,2*r.edges.length);if(r.hamiltonian.exists){eq(new Set(r.hamiltonian.path).size,r.n);for(let i=0;i<r.n;i++)eq(c.matrix[r.hamiltonian.path[i]][r.hamiltonian.path[(i+1)%r.n]],1);}for(const p of r.planarity.componentResults)if(p.planar)eq(p.eulerCharacteristic,2);}
for(const bad of [null,[],[null],[[0,1],[1]],[[0,2],[2,0]],Array(2),[[0,,0],[0,0,0],[0,0,0]]])eq(g.analyzeGraph(bad).validation.valid,false);
// This fixed network has exactly four s-t cuts, enumerated directly, independently of DFS/residual reachability.
for(const scale of [1e-120,1e-12,1,1e12,1e120])for(let code=0;code<1024;code++){let k=code;const c=f.makeConfig('reroute');for(const id of ['sa','sb','ab','at','bt']){c.capacities[id]=(k%4)*scale;k=Math.floor(k/4);}const {sa,sb,ab,at,bt}=c.capacities,expected=Math.min(sa+sb,sb+ab+at,sa+bt,at+bt),r=f.runToCertificate(c);near(r.value,expected,scale);near(r.certificate.capacity,expected,scale);eq(r.certificate.separates,true);eq(f.findAugmentingPath(c,r.flow),null);for(const [id,v]of Object.entries(r.flow)){assert(v>=0&&v<=c.capacities[id]);checks++;}const bal=f.balances(c,r.flow);near(bal.a,0,scale);near(bal.b,0,scale);near(bal.s,-r.value,scale);near(bal.t,r.value,scale);}
const c=f.makeConfig('reroute');for(const bad of [{...f.zeroFlow(),sa:-1e-15},{...f.zeroFlow(),sa:1e-15}]){assert.throws(()=>f.runToCertificate(c,bad));checks++;}
const a=f.augment(c,f.zeroFlow()),b=f.augment(c,a.flow);eq(a.flow.ab,1);eq(b.flow.ab,0);eq(b.path.some(e=>e.id==='ab'&&e.direction===-1),true);
const P=[[0,1,0],[.5,0,.5],[1,0,0]],alpha=.85;let x=[1/3,1/3,1/3];for(let i=0;i<300;i++)x=P[0].map((_,j)=>(1-alpha)/3+alpha*x.reduce((v,p,k)=>v+p*P[k][j],0));near(x[0],.397399660825325,1);near(x[1],.387789711701526,1);near(x[2],.214810627473149,1);
console.log(`Graph/flow independent checks: ${checks} PASS`);
