'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path'),lab=require('../course-shared/labs/eigen-geometry.js');let checks=0;
function check(v,m){checks++;assert(v,m)}function close(a,b,m,t=1e-11){check(Math.abs(a-b)<=t*Math.max(1,Math.abs(b)),m+': '+a+' vs '+b)}
const mul=(a,b)=>a.map(r=>b[0].map((_,j)=>r.reduce((v,x,k)=>v+x*b[k][j],0))),identity=n=>Array.from({length:n},(_,i)=>Array.from({length:n},(_,j)=>+(i===j))),power=(a,k)=>{let v=identity(a.length);for(let i=0;i<k;i++)v=mul(v,a);return v},asArray=m=>[[m.a,m.b],[m.c,m.d]],matrices={diag:[[2,0],[0,.5]],symmetric:[[2,1],[1,2]],jordan:[[1,1],[0,1]],rotation:[[0,-1],[1,0]]};
function node(tag,attrs,children){return{tag,attrs:attrs||{},children:children===undefined?[]:Array.isArray(children)?children:[children],appendChild(c){this.children.push(c)}}}const api={svg:node};function all(n,tag){return(n.tag===tag?[n]:[]).concat(...n.children.filter(c=>typeof c==='object').map(c=>all(c,tag)));}
for(const [id,a]of Object.entries(matrices)){
 for(let k=0;k<=20;k++){const expected=power(a,k),d=lab.evaluate({presetId:id,k});asArray(d.power).flat().forEach((v,i)=>close(v,expected.flat()[i],'power via repeated multiplication'));close(d.powerE2.x,expected[0][1],'e2 x');close(d.powerE2.y,expected[1][1],'e2 y');close(d.normPower,Math.hypot(expected[0][1],expected[1][1]),'power norm');}
 for(let angle=0;angle<=360;angle++){const d=lab.evaluate({presetId:id,angle}),th=angle*Math.PI/180,x=[1.45*Math.cos(th),1.45*Math.sin(th)],ax=mul(a,[[x[0]],[x[1]]]).flat();close(d.x.x,x[0],'input x');close(d.x.y,x[1],'input y');close(d.ax.x,ax[0],'output x');close(d.ax.y,ax[1],'output y');close(d.normAx,Math.hypot(...ax),'output norm');if(angle%15===0){const svg=lab.scene(api,d,true,'test'),points=all(svg,'circle').filter(c=>c.attrs['data-vector']);check(points.length===2,'two actual vector endpoints');points.forEach((p,i)=>{close((p.attrs.cx-(185+370*i))/28,i?ax[0]:x[0],'diagram world x');close((235-p.attrs.cy)/28,i?ax[1]:x[1],'diagram world y');check(p.attrs.cx>=31+370*i&&p.attrs.cx<=339+370*i&&p.attrs.cy>=81&&p.attrs.cy<=389,'endpoints inside plot');});const curves=all(svg,'path');check(curves.length===2,'two circle curves');curves.forEach((curve,side)=>{const pts=[...curve.attrs.d.matchAll(/[ML]([-\d.]+),([-\d.]+)/g)];check(pts.length===129,'circle sampling');pts.forEach((p,i)=>{const t=2*Math.PI*i/128,v=[Math.cos(t),Math.sin(t)],w=side?mul(a,[[v[0]],[v[1]]]).flat():v;close(+p[1],185+370*side+28*w[0],'circle pixel x',.00001);close(+p[2],235-28*w[1],'circle pixel y',.00001);});});}
 }
}
for(const p of lab.PRESETS)for(const e of p.realDirections){const v=lab.applyMatrix(p.matrix,e.vector);close(v.x,e.value*e.vector.x,'exact eigen x');close(v.y,e.value*e.vector.y,'exact eigen y');}
for(const bad of [null,5,'diag',[]]){checks++;assert.throws(()=>lab.evaluate(bad));}for(const field of ['angle','k'])for(const value of [NaN,Infinity,-1,361,null,'1']){checks++;assert.throws(()=>lab.evaluate({[field]:value}));}for(const k of [.5,21]){checks++;assert.throws(()=>lab.powerMatrix('diag',k));}checks++;assert.throws(()=>lab.evaluate({presetId:'bad'}));checks++;assert.throws(()=>lab.applyMatrix({a:Infinity,b:0,c:0,d:1},{x:1,y:0}));checks++;assert.throws(()=>lab.applyMatrix({a:Number.MAX_VALUE,b:0,c:0,d:1},{x:2,y:0}));
check(lab.evaluate({angle:90}).x.x===0&&lab.evaluate({angle:360}).x.y===0,'cardinal exact model directions');check(lab.formatNumber(10000,0)==='10000','integer digits');check(lab.formatNumber(1e-16)!=='0','small nonzero preserved');
const A=[[4,6,0],[-3,-5,0],[-3,-6,1]],T=[[-2,0,-1],[1,0,1],[0,1,1]],D=[[1,0,0],[0,1,0],[0,0,-2]];check(JSON.stringify(mul(A,T))===JSON.stringify(mul(T,D)),'worked diagonalization A T=T D');
const B=[[.5,4],[0,.5]];for(let k=1;k<=30;k++){const b=power(B,k);close(b[0][1],4*k*2**(1-k),'transient power');close(b[1][1],2**(-k),'transient second coordinate');}check(Math.hypot(4,.5)>4&&Math.hypot(power(B,30)[0][1],power(B,30)[1][1])<.000001,'transient growth then decay');
function choose(n,k){let v=1;for(let j=1;j<=k;j++)v=v*(n-j+1)/j;return v;}
for(let size=1;size<=5;size++)for(const lambda of [0,-1,.5,2])for(let m=0;m<=12;m++){const J=identity(size).map((r,i)=>r.map((v,j)=>v*lambda+(j===i+1?1:0))),p=power(J,m);p.forEach((row,i)=>row.forEach((v,j)=>{const gap=j-i,expected=gap>=0&&gap<=m?choose(m,gap)*lambda**(m-gap):0;close(v,expected,'Jordan binomial includes zero eigenvalue');}));}
let fib=[0,1];for(let n=2;n<=35;n++)fib[n]=fib[n-1]+fib[n-2];for(let n=0;n<=35;n++)close((((1+Math.sqrt(5))/2)**n-((1-Math.sqrt(5))/2)**n)/Math.sqrt(5),fib[n],'Fibonacci initial values and recurrence');
const lecture=fs.readFileSync(path.join(__dirname,'../math-course/lectures/algebra-05-eigen.md'),'utf8');check(!/[\x00-\x08\x0b\x0c\x0e-\x1f]/.test(lecture),'no TeX control damage');for(const m of lecture.replace(/\$\$[\s\S]*?\$\$/g,'').matchAll(/(?<![\\$])\$(?!\$)([\s\S]*?)(?<!\\)\$(?!\$)/g))check(!m[1].includes('\n'),'no multiline inline TeX');
const staticSvg=fs.readFileSync(path.join(__dirname,'../math-course/images/algebra-05-eigenvectors.svg'),'utf8');for(const id of ['unit','image']){const m=staticSvg.match(new RegExp('<path d="([^"]+)"[^>]*data-curve="'+id+'"')),points=[...m[1].matchAll(/[ML]([-\d.]+),([-\d.]+)/g)];check(points.length===257,'static 257 samples');points.forEach((p,i)=>{let x=Math.cos(i*Math.PI/128),y=Math.sin(i*Math.PI/128);if(id==='image')[x,y]=[2*x+y,x+2*y];close(+p[1],180+40*x,'static curve x',1e-6);close(+p[2],245-40*y,'static curve y',1e-6);});}
const trajectory=[...staticSvg.matchAll(/<circle data-k="(\d+)" cx="([\d.]+)" cy="([\d.]+)"/g)];check(trajectory.length===6,'six iterates');trajectory.forEach(p=>{close((+p[2]-430)/40,+p[1],'Jordan position k');close((335-+p[3])/40,1,'Jordan position y');});
check(!/^\+(?:$|\*\*)/m.test(lecture),'no prose patch-prefix residue');
console.log(`eigen geometry: PASS (${checks} independent checks)`);
