'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path'),lab=require('../course-shared/labs/turbulence-cascade.js');let checks=0;
function check(v,m){checks++;assert(v,m)}function close(a,b,m,t=1e-9){check(Math.abs(a-b)<=t*Math.max(Math.abs(b),1e-20),m+': '+a+' vs '+b)}
function simpson(f,a,b,n=512){let s=f(a)+f(b);for(let j=1;j<n;j++)s+=(j%2?4:2)*f(a+(b-a)*j/n);return s*(b-a)/n/3}
class N{constructor(tag){this.tag=tag;this.attrs={};this.children=[];this.nodeType=1;this.textContent=''}setAttribute(k,v){this.attrs[k]=String(v)}appendChild(n){this.children.push(n);return n}removeChild(n){this.children.splice(this.children.indexOf(n),1)}get firstChild(){return this.children[0]}querySelectorAll(q){return this.all().filter(n=>q==='[data-tick="x"]'&&n.attrs['data-tick']==='x')}all(){return this.children.flatMap(n=>[n,...n.all()])}}
const doc={createElementNS:(_,t)=>new N(t),createElement:t=>new N(t),createTextNode:t=>{const n=new N('#text');n.textContent=t;return n}};
function drawing(fn,c){const svg=new N('svg');fn(doc,svg,c,'audit');svg.all().forEach(n=>{for(const [k,v]of Object.entries(n.attrs)){check(!/NaN|Infinity/.test(v),'finite actual SVG '+k);if(['x','x1','x2','cx','y','y1','y2','cy'].includes(k)){check(Number.isFinite(+v),'numeric coordinate');check(+v>=0&&+v<=760,'coordinate inside frame')}}});return svg}
function curve(svg,name){const n=svg.all().find(n=>n.attrs['data-curve']===name);check(!!n,'actual curve '+name);return [...n.attrs.d.matchAll(/[ML](-?[\d.]+),(-?[\d.]+)/g)].map(m=>[+m[1],+m[2]])}
const configs=[];
for(const L of [.01,.05,.1,.6,1,2,10])for(const nu of [1e-7,1e-6,3e-5,.001,.01])for(const epsilon of [1e-6,.01,.05,.4,1,2,100])configs.push({L,nu,epsilon,p:12});
for(const input of configs){const c=lab.compute(input),eta=(input.nu**3/input.epsilon)**.25,U=Math.cbrt(input.epsilon*input.L);close(c.eta,eta,'independent eta');close(c.U,U,'independent U');close(c.Re,U*input.L/input.nu,'Re');close(c.ratio,c.Re**.75,'scale identity');const expected=c.L/eta>=1000*(1-8*Number.EPSILON)&&(c.Re>=1000)&&c.samples.filter(row=>row.r>=10*eta*(1-1e-13)&&row.r<=c.L/10*(1+1e-13)).length>=2;check(c.teachingWindow.valid===expected,'display criterion');for(const row of c.samples){close(row.deltaUFormula,Math.cbrt(c.epsilon*row.r),'increment');close(row.turnoverFormula,row.r/Math.cbrt(c.epsilon*row.r),'turnover');close(row.spectrumFormula,c.Ck*c.epsilon**(2/3)*row.k**(-5/3),'energy density');if(row.certified){close(row.piOverEpsilon,1,'flux normalization');close(row.minusS3OverEpsilonR,.8,'4/5 normalization')}else check(row.spectrum===null&&row.fourFifth===null,'excluded readings');}drawing(lab.drawScale,c);}
for(const nu of [1e-6,3e-5,.001])for(const eps of [.01,1,2])for(let i=0;i<=100;i++){const eta=(nu**3/eps)**.25,r=eta*10**(-2+6*i/100),c=lab.viscousBalance(eps,nu,r);const b=30**.75,s2=x=>eps*x*x/(15*nu)*(1+(x/b/eta)**2)**(-2/3),h=r*1e-4;const derivative=(s2(r-2*h)-8*s2(r-h)+8*s2(r+h)-s2(r+2*h))/(12*h);close(c.S2,s2(r),'independent prescribed S2');close(c.viscous,6*nu*derivative/(eps*r),'five point viscous derivative',1e-8);close(c.total,.8,'balance closure');close(c.S3,-.8*eps*r+6*nu*derivative,'signed balance',2e-4);check(c.normalizedS3>=0&&c.normalizedS3<=.8,'signed direction');}
// Exact forcing integration with a nonconstant, smooth prescribed correlation.
for(const r of [.01,.1,.5,1,2]){const eps=.7,a=.2,F=s=>2*eps/3+a*s*s;const integ=simpson(s=>s**4*F(s),0,r);close(-6*integ/r**4,-.8*eps*r-6*a*r**3/7,'nonconstant forcing term',1e-9)}
for(let p=0;p<=12;p+=.125){close(lab.k41Exponent(p),p/3,'K41 exponent');close(lab.sheLevequeExponent(p),p/9+2*(1-(2/3)**(p/3)),'SL exponent');if(p>.125&&p<11.875)check(lab.sheLevequeExponent(p) >=(lab.sheLevequeExponent(p-.125)+lab.sheLevequeExponent(p+.125))/2,'concavity')}
close(lab.sheLevequeExponent(6),16/9,'sixth exponent');close((1e-3)**(16/9-2),10**(2/3),'migration ratio');close(16**(9/4),512,'grid migration');
for(const input of [{},{L:.01,nu:.01,epsilon:1e-6},{L:1,nu:.01,epsilon:1e-6},{L:10,nu:1e-7,epsilon:100},{presetId:'narrow'},...Array.from({length:12},(_,i)=>({p:i+1}))]){const c=lab.compute(input);const scale=drawing(lab.drawScale,c);check(scale.all().filter(n=>n.attrs['data-band']==='candidate').length===(c.inertialRange.geometricValid?1:0),'no false candidate band');for(const fn of [lab.drawSpectrum,lab.drawFlux,lab.drawBalance,lab.drawExponents])drawing(fn,c);const ex=drawing(lab.drawExponents,c);check(ex.all().filter(n=>n.attrs.d==='M90 80V290H730').every(n=>n.attrs.fill==='none'),'open axes never filled');for(const n of ex.all().filter(n=>n.attrs['data-selected']))close((+n.attrs.cx-90)/640*12,c.p,'selected p actual coordinate');
const bal=drawing(lab.drawBalance,c);const pts=curve(bal,'balance-s3'),vis=curve(bal,'balance-viscous'),tot=curve(bal,'balance-total');check(pts.length===161,'balance sampling');pts.forEach((pt,i)=>{close(pt[0],vis[i][0],'same scale x');close((290-pt[1])/210+(290-vis[i][1])/210,.8,'plotted closure',1e-7);close((290-tot[i][1])/210,.8,'plotted total',1e-7)});
const spec=drawing(lab.drawSpectrum,c),sp=curve(spec,'spectrum-formula');if(c.L/c.eta>1.001){for(let j=1;j<sp.length;j++)check(sp[j][0]<sp[j-1][0]&&sp[j][1]<sp[j-1][1],'inverse r k direction');}check(spec.all().filter(n=>n.attrs['data-tick']==='x').length===5,'numeric x ticks');check(spec.all().filter(n=>n.attrs['data-tick']==='y').length===5,'numeric y ticks');}
for(const key of ['L','nu','epsilon','Ck','p'])for(const bad of [null,'1',true,NaN,Infinity,-1,0]){checks++;assert.throws(()=>lab.compute({[key]:bad}))}
for(const input of [null,[],true,{presetId:'bad'},{p:1.5},{p:13},{L:11},{assumptions:{isotropic:'false'}},{assumptions:{typo:true}},{samples:10}]){checks++;assert.throws(()=>lab.compute(input))}
for(const count of [0,-1,1.5,402,'9']){checks++;assert.throws(()=>lab.inertialRange(1,.0001,count))}
for(const args of [[1,1],[1,1,1],[NaN,1,1,1]]){checks++;assert.throws(()=>lab.energyFlux(...args))}
check(!lab.compute({assumptions:{isotropic:false}}).teachingWindow.valid,'no silent true override');check(lab.format(100,0)==='100','zero-digit format');close(lab.energySpectrum(1,1,2),2,'Ck');checks++;assert.throws(()=>lab.energySpectrum(1,1,-1));
const body=fs.readFileSync(path.join(__dirname,'../physics-course/lectures/fl-03-turbulence.md'),'utf8');check(!/[\x00-\x09\x0b\x0c\x0e-\x1f]/.test(body),'no control chars');for(const m of body.replace(/\$\$[\s\S]*?\$\$/g,'').matchAll(/(?<![\\$])\$(?!\$)([\s\S]*?)(?<!\\)\$(?!\$)/g))check(!m[1].includes('\n'),'inline TeX intact');check(/<\/div>\s*### 4/.test(body),'boundary outside lab');
const svg=fs.readFileSync(path.join(__dirname,'../physics-course/images/fl-03-turbulence-spectrum.svg'),'utf8');for(const [name,type]of [['static-spectrum','spectrum'],['static-s3','s3'],['static-viscous','viscous']]){const d=svg.match(new RegExp('data-curve="'+name+'" d="([^"]+)"'))[1];[...d.matchAll(/[ML]([\d.]+),([\d.]+)/g)].forEach(m=>{if(type==='spectrum'){const k=10**((+m[1]-75)/90);close((345-+m[2])/30-7,Math.log10(1.5*k**(-5/3)),'static spectrum axes',1e-6)}else{const t=10**((+m[1]-555)/72-1),q=(t/30**.75)**2,v=.8*(1+q/3)/(1+q)**(5/3);close((345-+m[2])/240,type==='s3'?.8-v:v,'static viscous model',5e-5)}})}
console.log(`turbulence cascade: PASS (${checks} independent checks; ${lab.selfTest().checks} self checks)`);
