'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path'),lab=require('../course-shared/labs/rayleigh-benard.js'),ref=require('./fixtures/rbc-reference.json');let checks=0;
function check(v,m){checks++;assert(v,m)}function close(a,b,m,t=1e-9){check(Math.abs(a-b)<=t*Math.max(1,Math.abs(b)),m+': '+a+' vs '+b)}
ref.amplitudes.forEach(v=>close(lab.amplitudeAt(v.mu,1.2,v.a0,v.time),v.A,'independent adaptive IVP',2e-10));ref.growth.forEach(v=>{const g=lab.linearGrowth(v.ra,v.a,v.pr);close(g.minus,v.roots[0],'independent eigensolver -',1e-10);close(g.plus,v.roots[1],'independent eigensolver +',1e-10)});
const pi=Math.PI,ac=pi/Math.sqrt(2),rc=27*pi**4/4;
check(lab.controlMu(rc,ac)===0,'symbolic critical preset preserved');check(lab.linearGrowth(rc,ac,7).plus===0,'exact preset neutral root');check(lab.controlMu(657.51,ac)<0,'rounded number is not exact critical');
for(let j=0;j<=100;j++){const a=.8+.05*j,n=(a*a+pi*pi)**3/a**2;close(lab.neutralRayleigh(a),n,'neutral curve');check(n>=rc-1e-10,'global min');for(const ra of [400,657.51,900,1400])for(const pr of [.01,.1,1,7,100]){const c=lab.compute({ra,a,pr}),q=a*a+pi*pi,poly=c.growth.plus**2+(1+pr)*q*c.growth.plus+pr*q*q-pr*ra*a*a/q;close(poly,0,'characteristic residual',1e-9);check(Math.sign(c.growth.plus)===Math.sign(c.mu),'growth and neutral criterion');}}
for(const mu of [-.9,-1e-12,0,1e-12,1.1])for(const initial of [-.9,-.12,0,.12,.9])for(const t of [0,.1,3,12]){const A=lab.amplitudeAt(mu,1.2,initial,t);if(initial)check(Math.sign(A)===Math.sign(initial),'initial sign preserved');else check(A===0,'zero invariant');if(t>0){const h=1e-4,der=(lab.amplitudeAt(mu,1.2,initial,t-2*h)-8*lab.amplitudeAt(mu,1.2,initial,t-h)+8*lab.amplitudeAt(mu,1.2,initial,t+h)-lab.amplitudeAt(mu,1.2,initial,t+2*h))/(12*h);close(der,mu*A-1.2*A**3,'ODE derivative',1e-8)}close(lab.amplitudeAt(mu,1.2,-initial,t),-A,'odd normal form');}
for(const initial of [-.5,0,.5]){close(lab.amplitudeAt(.3,1.2,initial,1e4),lab.saturation(.3,1.2,initial),'long-time signed equilibrium');close(lab.amplitudeAt(0,1.2,initial,10),initial/Math.sqrt(1+24*initial**2),'critical algebraic decay');}
class N{constructor(tag,doc){this.tag=tag;this.ownerDocument=doc;this.attrs={};this.children=[];this.nodeType=1;this.textContent=''}setAttribute(k,v){this.attrs[k]=String(v)}appendChild(n){this.children.push(n);return n}removeChild(n){this.children.splice(this.children.indexOf(n),1)}get firstChild(){return this.children[0]}get lastChild(){return this.children.at(-1)}all(){return this.children.flatMap(n=>[n,...n.all()])}}
const doc={createElementNS:(_,t)=>new N(t,doc),createElement:t=>new N(t,doc),createTextNode:t=>{const n=new N('#text',doc);n.textContent=t;return n}};
function render(fn,c,...args){const svg=new N('svg',doc);fn(svg,c,...args);svg.all().forEach(n=>Object.values(n.attrs).forEach(v=>check(!/NaN|Infinity/.test(v),'finite SVG')));return svg}
function curve(svg,name){const n=svg.all().find(n=>n.attrs['data-curve']===name);check(!!n,'curve exists');return [...n.attrs.d.matchAll(/[ML](-?[\d.]+),(-?[\d.]+)/g)].map(m=>[+m[1],+m[2]])}
for(const a of [.8,ac,3.1,4.4,5.8])for(const a0 of [-.9,-.12,0,.12,.9]){const c=lab.compute({a,a0});const ns=render(lab.drawNeutral,c,'n');curve(ns,'neutral').forEach(pt=>{const av=.8+(pt[0]-75)/649*5,n=(av*av+pi*pi)**3/av**2;close((303-pt[1])/275*3000,n,'actual neutral curve geometry',2e-4)});const as=render(lab.drawAmplitude,c,'a'),max=Math.max(.8,Math.abs(a0)*1.18,Math.abs(c.saturation)*1.18);curve(as,'amplitude').forEach(pt=>{const t=(pt[0]-75)/649*12,A=(224-pt[1])/196*2*max-max;close(A,lab.amplitudeAt(c.mu,1.2,a0,t),'actual signed amplitude chart',1e-4)});
const cs=render(lab.drawCells,c,c.amplitude,'c'),arrows=cs.all().filter(n=>n.attrs['data-arrow']==='velocity');if(!a0)check(arrows.length===0,'zero field has no velocity arrows');for(const n of arrows){const at=n.attrs,x=+at['data-x'],z=+at['data-z'],u=Math.sign(a0)*pi*Math.cos(pi*z)*Math.sin(a*x)*65.4,w=-Math.sign(a0)*a*Math.sin(pi*z)*Math.cos(a*x)*254,dx=+at.x2-+at.x1,dy=-(+at.y2-+at.y1);close(dx*w-dy*u,0,'arrow transformed to screen metric',1e-9);check(dx*u+dy*w>0,'arrow orientation correct');}
for(const n of cs.all().filter(n=>n.tag==='path'&&n.attrs.fill==='none')){for(const m of n.attrs.d.matchAll(/[ML]([\d.]+),([\d.]+)/g)){const x=(+m[1]-70)/65.4,z=(300-+m[2])/254,psi=Math.abs(Math.sin(pi*z)*Math.sin(a*x));check(Math.min(...[.22,.46,.7].map(f=>Math.abs(psi-f)))<.0005,'contour uses same streamfunction');}}
}
for(const key of ['ra','a','a0','time','pr'])for(const bad of [null,'1',true,NaN,Infinity,-100,1e8]){checks++;assert.throws(()=>lab.compute({[key]:bad}))}for(const bad of [null,[],false,{extra:1}]){checks++;assert.throws(()=>lab.compute(bad))}checks++;assert.throws(()=>lab.amplitudeAt(1,1.2,Number.MIN_VALUE,1));
const body=fs.readFileSync(path.join(__dirname,'../physics-course/lectures/fl-04-instability.md'),'utf8');check(!/[\x00-\x09\x0b\x0c\x0e-\x1f]/.test(body),'TeX controls');for(const m of body.replace(/\$\$[\s\S]*?\$\$/g,'').matchAll(/(?<![\\$])\$(?!\$)([\s\S]*?)(?<!\\)\$(?!\$)/g))check(!m[1].includes('\n'),'inline TeX');
const svg=fs.readFileSync(path.join(__dirname,'../physics-course/images/fl-04-instability-bifurcation.svg'),'utf8');for(const name of ['positive','negative']){const d=svg.match(new RegExp('data-curve="'+name+'" d="([^"]+)"'))[1];[...d.matchAll(/[ML]([\d.]+),([\d.]+)/g)].forEach(m=>{const ra=400+(+m[1]-555)/360*1000,A=(225-+m[2])/120;close(A*A,Math.max(0,(ra/rc-1)/1.2),'static branch equation',2e-8);if(Math.abs(A)>1e-8)check(Math.sign(A)===(name==='positive'?1:-1),'static branch sign')})}
console.log(`Rayleigh–Benard: PASS (${checks} independent checks)`);
