'use strict';const assert=require('assert'),fs=require('fs'),path=require('path'),root=path.resolve(__dirname,'..'),m=require(path.join(root,'course-shared/labs/group-actions.js')),ref=require('./fixtures/group-reference.json');let checks=0;
function ok(v,msg){checks++;assert(v,msg)}function eq(a,b,msg){ok(JSON.stringify(a)===JSON.stringify(b),msg)}function sorted(cosets){return cosets.map(c=>c.members.slice().sort((a,b)=>a-b)).sort((a,b)=>{for(let i=0;i<a.length;i++)if(a[i]!==b[i])return a[i]-b[i];return 0;})}
for(const g of m.GROUPS){const source=ref.groups[g.id];eq(g.mul,source.table,'independent multiplication');ok(g.subgroups.length===source.subgroups.length,'all subgroups offered');ok(Object.isFrozen(g)&&Object.isFrozen(g.mul[0]),'preset immutable');for(const h of g.subgroups){const expected=source.subgroups.find(s=>JSON.stringify(s.elements)===JSON.stringify(h.elements)),r=m.analyze(g.id,h.id);ok(!!expected,'known subgroup');eq(sorted(r.leftCosets),expected.left,'left partition');eq(sorted(r.rightCosets),expected.right,'right partition');ok(r.normal===expected.normal,'normality');ok(r.lagrange&&r.index*h.elements.length===g.values.length,'Lagrange');const cosetOf=x=>r.leftCosets.findIndex(c=>c.members.includes(x));for(let i=0;i<r.leftCosets.length;i++)for(let j=0;j<r.leftCosets.length;j++)for(const a of r.leftCosets[i].members)for(const b of r.leftCosets[j].members){if(r.normal)ok(cosetOf(g.mul[a][b])===r.quotient.table[i][j],'all representative choices');}if(!r.normal){const f=r.quotient.failure;ok(cosetOf(f.left)===cosetOf(f.alternateLeft)&&cosetOf(f.right)===cosetOf(f.alternateRight),'same input blocks');ok(g.mul[f.left][f.right]===f.result&&g.mul[f.alternateLeft][f.alternateRight]===f.alternateResult,'actual products');ok(cosetOf(f.result)!==cosetOf(f.alternateResult),'different output blocks');ok(!r.quotient.available&&r.quotient.table.length===0,'no fake quotient');}else{const T=r.quotient.table,identity=cosetOf(g.identity);for(let a=0;a<T.length;a++){ok(T[a][identity]===a&&T[identity][a]===a,'quotient identity');ok(T[a].includes(identity),'quotient inverse');for(let b=0;b<T.length;b++)for(let c=0;c<T.length;c++)ok(T[T[a][b]][c]===T[a][T[b][c]],'quotient associativity');}}}}
// Changing the operation convention would change these noncommutative products.
const s3=m.getGroup('s3');ok(s3.mul[4][1]===2&&s3.mul[1][4]===3,'rs=(13), sr=(23)');eq(m.analyze('s3','transposition').leftCosets.find(c=>c.members.includes(4)).members.slice().sort(),[2,4],'rH');
for(const r of ref.necklaces){for(let mask=0;mask<2**r.n;mask++){const a=m.necklaceReport(r.n,mask,r.reflections);eq(a.fixCounts,r.fixCounts,'cycle-count reference');ok(a.burnside===r.burnside&&a.orbits.length===r.burnside,'Burnside vs actual partition');ok(a.orbit.length*a.stabilizers.length===a.groupOrder,'orbit-stabilizer');const cover=a.orbits.flatMap(o=>o.members).sort((x,y)=>x-y);eq(cover,Array.from({length:2**r.n},(_,i)=>i),'every coloring exactly once');ok(a.orbit.includes(mask),'identity acts');for(const g of a.operations){const transformed=m.colorAction(mask,g.permutation,r.n);ok(a.orbit.includes(transformed),'closure of selected orbit');}for(const x of a.orbit){const orbit=a.operations.map(g=>m.colorAction(x,g.permutation,r.n));ok(orbit.every(y=>a.orbit.includes(y)),'action stays in same orbit');}}}
ok(m.necklaceReport(4,3,false).orbit.length===4,'prediction 0011');ok(m.necklaceReport(4,5,false).stabilizers.length===2,'alternating');ok(m.necklaceReport(6,0,false).burnside===14&&m.necklaceReport(6,0,true).burnside===13,'exercise bracelet');
for(const bad of [null,'','missing',7]){checks++;assert.throws(()=>m.analyze(bad));}for(const bad of [null,'','missing',7]){checks++;assert.throws(()=>m.analyze('c4',bad));}
for(const elements of [[],[0,0],[1],[0,1],[0,9],['0']]){checks++;assert.throws(()=>m.cosetPartition(m.getGroup('c4'),{elements}));}
const malformed=JSON.parse(JSON.stringify(m.getGroup('c4')));malformed.mul[1][2]=0;checks++;assert.throws(()=>m.validateGroup(malformed));
for(const args of [[2,0,false],[9,0,false],[4,-1,false],[4,16,false],[4,0,'false'],['4',0,false]]){checks++;assert.throws(()=>m.necklaceReport(...args));}
class Node{constructor(t){this.tag=t;this.attrs={};this.children=[];this.nodeType=1;}setAttribute(k,v){this.attrs[k]=String(v)}appendChild(n){this.children.push(n);return n}}
const doc={createElementNS(ns,t){return new Node(t)},createTextNode(t){return{nodeType:3,text:t}}};function all(n){return[n,...(n.children||[]).flatMap(all)]}
for(const g of m.GROUPS)for(const h of g.subgroups){const r=m.analyze(g.id,h.id),svg=m.renderCosetSvg(doc,r,'check'),nodes=all(svg),height=+svg.attrs.viewBox.split(' ')[3],rects=nodes.filter(n=>Object.hasOwn(n.attrs||{},'data-coset'));ok(rects.length===r.index*2,'all coset blocks');for(const rect of rects){ok(rect.attrs.fill==='var(--bg)','explicit nonblack fill');ok(+rect.attrs.y+(+rect.attrs.height)<=height,'block not clipped');}const texts=nodes.filter(n=>Object.hasOwn(n.attrs||{},'data-member'));ok(texts.length===g.values.length*2,'each member twice in left/right diagrams');for(const t of texts)ok(+t.attrs.y<height,'member visible');}
const svg=fs.readFileSync(path.join(root,'math-course/images/alg-abs-01-cyclic-group.svg'),'utf8');for(let i=0;i<4;i++)for(let j=0;j<4;j++)ok(svg.includes('data-cayley="'+i+','+j+'">'+((i+j)%4)+'</text>'),'real Cayley cell');for(let i=0;i<2;i++)for(let j=0;j<2;j++)ok(svg.includes('data-quotient="'+i+','+j+'">H'+((i+j)%2)+'</text>'),'real quotient cell');const colorings=[...svg.matchAll(/data-coloring="(\d+)"/g)].map(x=>+x[1]).sort((a,b)=>a-b);eq(colorings,Array.from({length:16},(_,i)=>i),'static all16');for(let mask=0;mask<16;mask++)for(let k=0;k<4;k++){const tag=svg.match(new RegExp('<circle data-bead="'+mask+':'+k+'"[^>]+>'))[0];ok(tag.includes('fill="'+(((mask>>(3-k))&1)?'#5278a5':'#faf8f1')+'"'),'static bead matches mask');}ok(!svg.includes('data and control'),'placeholder removed');console.log('group actions independent: PASS',{checks});

for(const args of [[0,[0,0,2],3],[8,[0,1,2],3],[0,[0,1],3],[0,[0,1,4],3],[0,[0,1,2],'3']]){checks++;assert.throws(()=>m.colorAction(...args));}console.log('action input regression: PASS');
